// Code generated by tools/rustcarve. DO NOT EDIT.

use super::{
    MIGRATION_IR_DIGEST_SHA256, MIGRATION_IR_VERSION, RUST_IMPLEMENTATION_REVISION,
    RUSTCARVE_TOOL_REVISION, SUBJECT_ID, contracts,
};

#[test]
fn generated_contract_is_closed_and_revision_bound() {
    assert_eq!(RUSTCARVE_TOOL_REVISION, "cerebro.rustcarve/v1");
    assert_eq!(MIGRATION_IR_VERSION, "provider-source/v1");
    assert_eq!(
        MIGRATION_IR_DIGEST_SHA256,
        "sha256:5c54836bc6e28ae59038178ac30fa6f61ce7624427725f526b938b05b7b0b402"
    );
    assert_eq!(
        RUST_IMPLEMENTATION_REVISION,
        "5ff8021ab1a2d971e772fd6bf7f3275ff596aa6b"
    );
    assert_eq!(SUBJECT_ID, "deepseek");
    assert_eq!(contracts::FIXTURE_CORPUS.len(), 2);
    assert_eq!(contracts::PORT_TRACES.len(), 1);
    assert_eq!(contracts::REQUIRED_RECEIPT_MODES.len(), 1);
    assert_eq!(contracts::ACCEPTED_RECEIPTS.len(), 0);
    assert_eq!(contracts::DELETION_ELIGIBLE, false);
    assert_eq!(contracts::DELETION_REASON_CODES.len(), 2);
    // This scaffold is intentionally not deletion-eligible without exact differential receipts.
}
