// Code generated by tools/rustcarve. DO NOT EDIT.

#[path = "contracts.rs"]
pub mod contracts;
#[cfg(test)]
#[path = "parity_test.rs"]
mod parity_test;

pub const RUSTCARVE_TOOL_REVISION: &str = "cerebro.rustcarve/v2";
pub const MIGRATION_IR_VERSION: &str = "provider-source/v2";
pub const MIGRATION_IR_DIGEST_SHA256: &str =
    "sha256:82c2d471afa88404539b9411c9088bb2ef7abb2e09ed802d1d808d3c95f319c7";
pub const SUBJECT_ID: &str = "deepseek";
pub const RUST_IMPLEMENTATION_REVISION: &str = "5ff8021ab1a2d971e772fd6bf7f3275ff596aa6b";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct AuthenticatedScope<'a> {
    pub tenant_id: &'a str,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ScopeError {
    MissingTenant,
    MissingWorkspace,
    ForbiddenWorkspace,
}

pub fn validate_scope(scope: AuthenticatedScope<'_>) -> Result<(), ScopeError> {
    if scope.tenant_id.trim().is_empty() {
        return Err(ScopeError::MissingTenant);
    }
    Ok(())
}
