// Code generated by tools/rustcarve. DO NOT EDIT.

use super::{
    MIGRATION_IR_DIGEST_SHA256, MIGRATION_IR_VERSION, RUST_IMPLEMENTATION_REVISION,
    RUSTCARVE_TOOL_REVISION, SUBJECT_ID, contracts,
};

#[test]
fn generated_contract_is_closed_and_revision_bound() {
    assert_eq!(RUSTCARVE_TOOL_REVISION, "cerebro.rustcarve/v2");
    assert_eq!(MIGRATION_IR_VERSION, "finding-rule/v1");
    assert_eq!(
        MIGRATION_IR_DIGEST_SHA256,
        "sha256:cab6fdd1e13b86d5b0b9ceb52c24858f901ce167e65d4f33d7cbf168219bedc5"
    );
    assert_eq!(
        RUST_IMPLEMENTATION_REVISION,
        "9a0d21b5b87996019ac78aec5a426129e6114558"
    );
    assert_eq!(SUBJECT_ID, "tailscale-tailnet-device-approval-disabled");
    assert_eq!(contracts::FIXTURE_CORPUS.len(), 2);
    assert_eq!(contracts::PORT_TRACES.len(), 1);
    assert_eq!(contracts::REQUIRED_RECEIPT_MODES.len(), 1);
    assert_eq!(contracts::ACCEPTED_RECEIPTS.len(), 0);
    assert_eq!(contracts::DELETION_ELIGIBLE, false);
    assert_eq!(contracts::DELETION_REASON_CODES.len(), 1);
    assert_eq!(contracts::AUTHORITY_GATES.len(), 0);
    // This scaffold is intentionally not deletion-eligible without exact differential receipts.
}
