// Code generated by tools/rustcarve. DO NOT EDIT.

#[path = "contracts.rs"]
pub mod contracts;
#[cfg(test)]
#[path = "parity_test.rs"]
mod parity_test;

pub const RUSTCARVE_TOOL_REVISION: &str = "cerebro.rustcarve/v1";
pub const MIGRATION_IR_VERSION: &str = "finding-rule/v1";
pub const MIGRATION_IR_DIGEST_SHA256: &str =
    "sha256:5ac4f7373b29b022169314155601c663dd646f4d8dd7f54c72ee412a82283bd0";
pub const SUBJECT_ID: &str = "tailscale-tailnet-device-approval-disabled";
pub const RUST_IMPLEMENTATION_REVISION: &str = "9a0d21b5b87996019ac78aec5a426129e6114558";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct AuthenticatedScope<'a> {
    pub tenant_id: &'a str,
    pub workspace_id: Option<&'a str>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ScopeError {
    MissingTenant,
    MissingWorkspace,
    ForbiddenWorkspace,
}

pub fn validate_scope(scope: AuthenticatedScope<'_>) -> Result<(), ScopeError> {
    if scope.tenant_id.trim().is_empty() {
        return Err(ScopeError::MissingTenant);
    }
    if scope
        .workspace_id
        .is_some_and(|value| value.trim().is_empty())
    {
        return Err(ScopeError::MissingWorkspace);
    }
    Ok(())
}
