// Code generated by tools/rustcarve. DO NOT EDIT.

#[path = "contracts.rs"]
pub mod contracts;
#[cfg(test)]
#[path = "parity_test.rs"]
mod parity_test;

pub const RUSTCARVE_TOOL_REVISION: &str = "cerebro.rustcarve/v2";
pub const MIGRATION_IR_VERSION: &str = "graph-query/v1";
pub const MIGRATION_IR_DIGEST_SHA256: &str =
    "sha256:15830b42b702c0ad8140752a6278ab590904ff40768ec0ac3cca2b0893b4dce7";
pub const SUBJECT_ID: &str = "policycandidate.grounding";
pub const RUST_IMPLEMENTATION_REVISION: &str = "unimplemented";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct AuthenticatedScope<'a> {
    pub tenant_id: &'a str,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ScopeError {
    MissingTenant,
    MissingWorkspace,
    ForbiddenWorkspace,
}

pub fn validate_scope(scope: AuthenticatedScope<'_>) -> Result<(), ScopeError> {
    if scope.tenant_id.trim().is_empty() {
        return Err(ScopeError::MissingTenant);
    }
    Ok(())
}
