package knowledge

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	cerebrov1 "github.com/writer/cerebro/gen/cerebro/v1"
	"github.com/writer/cerebro/internal/ports"
	"github.com/writer/cerebro/internal/workflowevents"
	"github.com/writer/cerebro/internal/workflowprojection"
)

const (
	defaultSourceSystem     = "platform.knowledge"
	defaultDecisionStatus   = "proposed"
	defaultActionType       = "recommendation"
	defaultActionStatus     = "recorded"
	defaultGraphLookupLimit = 1
	decisionEntityType      = "decision"
	outcomeEntityType       = "outcome"
	actionEntityType        = "action"
	relationTargets         = "targets"
	relationBasedOn         = "based_on"
	relationExecutedBy      = "executed_by"
	relationEvaluates       = "evaluates"
	defaultPlatformTenant   = "platform"
)

// ErrRuntimeUnavailable indicates that the graph read/write boundaries are unavailable.
var ErrRuntimeUnavailable = errors.New("knowledge runtime is unavailable")

// Service records workflow primitives onto the graph-backed platform layer.
type Service struct {
	query     ports.GraphQueryStore
	graph     ports.ProjectionGraphStore
	appendLog ports.AppendLog
}

// DecisionWriteRequest scopes one platform decision write.
type DecisionWriteRequest struct {
	ID            string
	DecisionType  string
	Status        string
	MadeBy        string
	Rationale     string
	TargetIDs     []string
	EvidenceIDs   []string
	ActionIDs     []string
	SourceSystem  string
	SourceEventID string
	ObservedAt    time.Time
	ValidFrom     time.Time
	ValidTo       time.Time
	Confidence    float64
	Metadata      map[string]any
}

// DecisionWriteResult reports one recorded platform decision.
type DecisionWriteResult struct {
	DecisionID  string
	TargetCount uint32
}

// ActionWriteRequest scopes one platform action write.
type ActionWriteRequest struct {
	ID               string
	RecommendationID string
	InsightType      string
	Title            string
	Summary          string
	DecisionID       string
	TargetIDs        []string
	SourceSystem     string
	SourceEventID    string
	ObservedAt       time.Time
	ValidFrom        time.Time
	ValidTo          time.Time
	Confidence       float64
	AutoGenerated    bool
	Metadata         map[string]any
}

// ActionWriteResult reports one recorded action.
type ActionWriteResult struct {
	ActionID    string
	DecisionID  string
	TargetCount uint32
}

// OutcomeWriteRequest scopes one outcome write tied back to one decision.
type OutcomeWriteRequest struct {
	ID            string
	DecisionID    string
	OutcomeType   string
	Verdict       string
	ImpactScore   float64
	TargetIDs     []string
	SourceSystem  string
	SourceEventID string
	ObservedAt    time.Time
	ValidFrom     time.Time
	ValidTo       time.Time
	Confidence    float64
	Metadata      map[string]any
}

// OutcomeWriteResult reports one recorded outcome.
type OutcomeWriteResult struct {
	OutcomeID   string
	DecisionID  string
	TargetCount uint32
}

// New constructs one platform knowledge write service.
func New(query ports.GraphQueryStore, graph ports.ProjectionGraphStore) *Service {
	return &Service{query: query, graph: graph}
}

// WithAppendLog wires an optional durable append log for workflow events.
func (s *Service) WithAppendLog(appendLog ports.AppendLog) *Service {
	if s == nil {
		return nil
	}
	s.appendLog = appendLog
	return s
}

// WriteDecision records one decision node plus its target, evidence, and action links.
func (s *Service) WriteDecision(ctx context.Context, request DecisionWriteRequest) (*DecisionWriteResult, error) {
	if s == nil || s.query == nil || s.graph == nil {
		return nil, ErrRuntimeUnavailable
	}
	decisionType := strings.TrimSpace(request.DecisionType)
	if decisionType == "" {
		return nil, errors.New("decision type is required")
	}
	targetIDs := normalizeIDs(request.TargetIDs)
	if len(targetIDs) == 0 {
		return nil, errors.New("decision target ids are required")
	}
	tenantID := inferTenantID(request.Metadata, targetIDs...)
	sourceSystem := firstNonEmpty(strings.TrimSpace(request.SourceSystem), defaultSourceSystem)
	decisionID := workflowevents.CanonicalWorkflowID(tenantID, decisionEntityType, request.ID, decisionType, targetIDs, request.ObservedAt)
	observedAt := normalizeObservedAt(request.ObservedAt)
	validFrom := normalizeValidFrom(request.ValidFrom, observedAt)
	status := firstNonEmpty(strings.TrimSpace(request.Status), defaultDecisionStatus)
	for _, targetID := range targetIDs {
		if err := s.requireEntity(ctx, targetID); err != nil {
			return nil, err
		}
	}
	validTo := ""
	if !request.ValidTo.UTC().IsZero() {
		validTo = request.ValidTo.UTC().Format(time.RFC3339Nano)
	}
	event, err := workflowevents.NewDecisionRecordedEvent(workflowevents.DecisionRecorded{
		TenantID:      tenantID,
		DecisionID:    decisionID,
		DecisionType:  decisionType,
		Status:        status,
		MadeBy:        strings.TrimSpace(request.MadeBy),
		Rationale:     strings.TrimSpace(request.Rationale),
		TargetIDs:     targetIDs,
		EvidenceIDs:   normalizeIDs(request.EvidenceIDs),
		ActionIDs:     normalizeIDs(request.ActionIDs),
		SourceSystem:  sourceSystem,
		SourceEventID: strings.TrimSpace(request.SourceEventID),
		ObservedAt:    observedAt.Format(time.RFC3339Nano),
		ValidFrom:     validFrom.Format(time.RFC3339Nano),
		ValidTo:       validTo,
		Confidence:    request.Confidence,
		Metadata:      request.Metadata,
	})
	if err != nil {
		return nil, err
	}
	if err := s.recordWorkflowEvent(ctx, event); err != nil {
		return nil, fmt.Errorf("append decision workflow event %q: %w", event.GetId(), err)
	}
	if _, err := workflowprojection.New(s.graph).Project(ctx, event); err != nil {
		return nil, fmt.Errorf("project decision workflow event %q: %w", event.GetId(), err)
	}
	return &DecisionWriteResult{
		DecisionID:  decisionID,
		TargetCount: uint32(len(targetIDs)),
	}, nil
}

// WriteAction records one action node plus its target links and optional decision context.
func (s *Service) WriteAction(ctx context.Context, request ActionWriteRequest) (*ActionWriteResult, error) {
	if s == nil || s.query == nil || s.graph == nil {
		return nil, ErrRuntimeUnavailable
	}
	title := strings.TrimSpace(request.Title)
	if title == "" {
		return nil, errors.New("action title is required")
	}
	targetIDs := normalizeIDs(request.TargetIDs)
	if len(targetIDs) == 0 {
		return nil, errors.New("action target ids are required")
	}
	tenantID := inferTenantID(request.Metadata, append(targetIDs, request.DecisionID)...)
	sourceSystem := firstNonEmpty(strings.TrimSpace(request.SourceSystem), defaultSourceSystem)
	decisionID := ""
	if strings.TrimSpace(request.DecisionID) != "" {
		decisionID = workflowevents.CanonicalWorkflowID(tenantID, decisionEntityType, request.DecisionID, decisionEntityType, targetIDs, request.ValidFrom)
		if err := s.requireEntity(ctx, decisionID); err != nil {
			return nil, err
		}
	}
	observedAt := normalizeObservedAt(request.ObservedAt)
	validFrom := normalizeValidFrom(request.ValidFrom, observedAt)
	actionType := firstNonEmpty(strings.TrimSpace(request.InsightType), defaultActionType)
	actionID := workflowevents.CanonicalWorkflowID(tenantID, actionEntityType, request.ID, actionType, append([]string{decisionID}, targetIDs...), request.ObservedAt)
	for _, targetID := range targetIDs {
		if err := s.requireEntity(ctx, targetID); err != nil {
			return nil, err
		}
	}
	validTo := ""
	if !request.ValidTo.UTC().IsZero() {
		validTo = request.ValidTo.UTC().Format(time.RFC3339Nano)
	}
	event, err := workflowevents.NewActionRecordedEvent(workflowevents.ActionRecorded{
		TenantID:         tenantID,
		ActionID:         actionID,
		ActionType:       actionType,
		Status:           defaultActionStatus,
		RecommendationID: strings.TrimSpace(request.RecommendationID),
		InsightType:      strings.TrimSpace(request.InsightType),
		Title:            title,
		Summary:          strings.TrimSpace(request.Summary),
		DecisionID:       decisionID,
		TargetIDs:        targetIDs,
		SourceSystem:     sourceSystem,
		SourceEventID:    strings.TrimSpace(request.SourceEventID),
		ObservedAt:       observedAt.Format(time.RFC3339Nano),
		ValidFrom:        validFrom.Format(time.RFC3339Nano),
		ValidTo:          validTo,
		Confidence:       request.Confidence,
		AutoGenerated:    request.AutoGenerated,
		Metadata:         request.Metadata,
	})
	if err != nil {
		return nil, err
	}
	if err := s.recordWorkflowEvent(ctx, event); err != nil {
		return nil, fmt.Errorf("append action workflow event %q: %w", event.GetId(), err)
	}
	if _, err := workflowprojection.New(s.graph).Project(ctx, event); err != nil {
		return nil, fmt.Errorf("project action workflow event %q: %w", event.GetId(), err)
	}
	return &ActionWriteResult{
		ActionID:    actionID,
		DecisionID:  decisionID,
		TargetCount: uint32(len(targetIDs)),
	}, nil
}

// WriteOutcome records one outcome node tied back to one decision.
func (s *Service) WriteOutcome(ctx context.Context, request OutcomeWriteRequest) (*OutcomeWriteResult, error) {
	if s == nil || s.query == nil || s.graph == nil {
		return nil, ErrRuntimeUnavailable
	}
	outcomeType := strings.TrimSpace(request.OutcomeType)
	if outcomeType == "" {
		return nil, errors.New("outcome type is required")
	}
	verdict := strings.TrimSpace(request.Verdict)
	if verdict == "" {
		return nil, errors.New("outcome verdict is required")
	}
	targetIDs := normalizeIDs(request.TargetIDs)
	tenantID := inferTenantID(request.Metadata, append(targetIDs, request.DecisionID)...)
	sourceSystem := firstNonEmpty(strings.TrimSpace(request.SourceSystem), defaultSourceSystem)
	decisionID := workflowevents.CanonicalWorkflowID(tenantID, decisionEntityType, request.DecisionID, decisionEntityType, targetIDs, request.ValidFrom)
	if strings.TrimSpace(request.DecisionID) == "" {
		return nil, errors.New("outcome decision id is required")
	}
	if err := s.requireEntity(ctx, decisionID); err != nil {
		return nil, err
	}
	observedAt := normalizeObservedAt(request.ObservedAt)
	validFrom := normalizeValidFrom(request.ValidFrom, observedAt)
	outcomeID := workflowevents.CanonicalWorkflowID(tenantID, outcomeEntityType, request.ID, outcomeType, append([]string{decisionID}, targetIDs...), request.ObservedAt)
	for _, targetID := range targetIDs {
		if err := s.requireEntity(ctx, targetID); err != nil {
			return nil, err
		}
	}
	validTo := ""
	if !request.ValidTo.UTC().IsZero() {
		validTo = request.ValidTo.UTC().Format(time.RFC3339Nano)
	}
	event, err := workflowevents.NewOutcomeRecordedEvent(workflowevents.OutcomeRecorded{
		TenantID:      tenantID,
		OutcomeID:     outcomeID,
		DecisionID:    decisionID,
		OutcomeType:   outcomeType,
		Verdict:       verdict,
		ImpactScore:   request.ImpactScore,
		TargetIDs:     targetIDs,
		SourceSystem:  sourceSystem,
		SourceEventID: strings.TrimSpace(request.SourceEventID),
		ObservedAt:    observedAt.Format(time.RFC3339Nano),
		ValidFrom:     validFrom.Format(time.RFC3339Nano),
		ValidTo:       validTo,
		Confidence:    request.Confidence,
		Metadata:      request.Metadata,
	})
	if err != nil {
		return nil, err
	}
	if err := s.recordWorkflowEvent(ctx, event); err != nil {
		return nil, fmt.Errorf("append outcome workflow event %q: %w", event.GetId(), err)
	}
	if _, err := workflowprojection.New(s.graph).Project(ctx, event); err != nil {
		return nil, fmt.Errorf("project outcome workflow event %q: %w", event.GetId(), err)
	}
	return &OutcomeWriteResult{
		OutcomeID:   outcomeID,
		DecisionID:  decisionID,
		TargetCount: uint32(len(targetIDs)),
	}, nil
}

func (s *Service) requireEntity(ctx context.Context, id string) error {
	if s == nil || s.query == nil {
		return ErrRuntimeUnavailable
	}
	entityID := strings.TrimSpace(id)
	if entityID == "" {
		return errors.New("graph entity id is required")
	}
	if _, err := s.query.GetEntityNeighborhood(ctx, entityID, defaultGraphLookupLimit); err != nil {
		if errors.Is(err, ports.ErrGraphEntityNotFound) {
			return fmt.Errorf("%w: %s", ports.ErrGraphEntityNotFound, entityID)
		}
		return fmt.Errorf("load graph entity %q: %w", entityID, err)
	}
	return nil
}

func (s *Service) recordWorkflowEvent(ctx context.Context, event *cerebrov1.EventEnvelope) error {
	if s == nil || s.appendLog == nil {
		return nil
	}
	return s.appendLog.Append(ctx, event)
}

func inferTenantID(metadata map[string]any, ids ...string) string {
	if value, ok := metadata["tenant_id"].(string); ok && strings.TrimSpace(value) != "" {
		return strings.TrimSpace(value)
	}
	for _, id := range ids {
		trimmed := strings.TrimSpace(id)
		if !strings.HasPrefix(trimmed, "urn:cerebro:") {
			continue
		}
		parts := strings.Split(trimmed, ":")
		if len(parts) >= 4 && strings.TrimSpace(parts[2]) != "" {
			return strings.TrimSpace(parts[2])
		}
	}
	return defaultPlatformTenant
}

func normalizeIDs(values []string) []string {
	seen := make(map[string]struct{}, len(values))
	normalized := make([]string, 0, len(values))
	for _, value := range values {
		trimmed := strings.TrimSpace(value)
		if trimmed == "" {
			continue
		}
		if _, ok := seen[trimmed]; ok {
			continue
		}
		seen[trimmed] = struct{}{}
		normalized = append(normalized, trimmed)
	}
	return normalized
}

func normalizeObservedAt(value time.Time) time.Time {
	observedAt := value.UTC()
	if observedAt.IsZero() {
		return time.Now().UTC()
	}
	return observedAt
}

func normalizeValidFrom(value time.Time, observedAt time.Time) time.Time {
	validFrom := value.UTC()
	if validFrom.IsZero() {
		return observedAt
	}
	return validFrom
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if trimmed := strings.TrimSpace(value); trimmed != "" {
			return trimmed
		}
	}
	return ""
}
