package knowledge

import (
	"context"
	"errors"
	"fmt"
	"math"
	"strings"
	"time"

	cerebrov1 "github.com/writer/cerebro/gen/cerebro/v1"
	"github.com/writer/cerebro/internal/fabriccontract"
	"github.com/writer/cerebro/internal/ports"
	"github.com/writer/cerebro/internal/telemetry"
	"github.com/writer/cerebro/internal/workflowevents"
	"github.com/writer/cerebro/internal/workflowprojection"
)

const (
	defaultSourceSystem      = "platform.knowledge"
	defaultDecisionStatus    = "proposed"
	defaultActionType        = "recommendation"
	defaultActionStatus      = "recorded"
	decisionEntityType       = "decision"
	packetDecisionEntityType = "packet_decision"
	outcomeEntityType        = "outcome"
	actionEntityType         = "action"
	relationTargets          = fabriccontract.RelationTargets
	relationBasedOn          = fabriccontract.RelationBasedOn
	relationExecutedBy       = fabriccontract.RelationExecutedBy
	relationEvaluates        = fabriccontract.RelationEvaluates
	defaultPlatformTenant    = "platform"
	DurabilityRecorded       = "recorded"
	DurabilityNotRecorded    = "not_recorded"
	ProjectionProjected      = "projected"
	ProjectionPending        = "pending"
	ProjectionNotConfigured  = "not_configured"
	ProjectionFailed         = "failed"
	ProjectionErrorGraph     = "graph_projection_failed"
)

type DurabilityMode string

const (
	DurabilityLegacyProjectionOnly DurabilityMode = "legacy_projection_only"
	DurabilityRequired             DurabilityMode = "durable_required"
)

var (
	// ErrRuntimeUnavailable indicates that the graph read/write boundaries are unavailable.
	ErrRuntimeUnavailable = errors.New("knowledge runtime is unavailable")
	// ErrInvalidRequest indicates that a knowledge write request failed validation.
	ErrInvalidRequest = errors.New("invalid knowledge request")
)

// Service records workflow primitives onto the graph-backed platform layer.
type Service struct {
	graph          ports.ProjectionGraphStore
	appendLog      ports.AppendLog
	durabilityMode DurabilityMode
}

// DecisionWriteRequest scopes one platform decision write.
type DecisionWriteRequest struct {
	ID            string
	DecisionType  string
	Status        string
	MadeBy        string
	Rationale     string
	TargetIDs     []string
	EvidenceIDs   []string
	ActionIDs     []string
	SourceSystem  string
	SourceEventID string
	ObservedAt    time.Time
	ValidFrom     time.Time
	ValidTo       time.Time
	Confidence    float64
	Metadata      map[string]any
}

// DecisionWriteResult reports one recorded platform decision.
type DecisionWriteResult struct {
	DecisionID              string
	TargetCount             uint32
	EventID                 string
	DurabilityStatus        string
	ProjectionStatus        string
	ProjectionErrorCategory string
}

// ActionWriteRequest scopes one platform action write.
type ActionWriteRequest struct {
	ID               string
	RecommendationID string
	InsightType      string
	Title            string
	Summary          string
	DecisionID       string
	TargetIDs        []string
	SourceSystem     string
	SourceEventID    string
	ObservedAt       time.Time
	ValidFrom        time.Time
	ValidTo          time.Time
	Confidence       float64
	AutoGenerated    bool
	Metadata         map[string]any
}

// ActionWriteResult reports one recorded action.
type ActionWriteResult struct {
	ActionID                string
	DecisionID              string
	TargetCount             uint32
	EventID                 string
	DurabilityStatus        string
	ProjectionStatus        string
	ProjectionErrorCategory string
}

// OutcomeWriteRequest scopes one outcome write tied back to one decision.
type OutcomeWriteRequest struct {
	ID            string
	DecisionID    string
	OutcomeType   string
	Verdict       string
	ImpactScore   float64
	TargetIDs     []string
	SourceSystem  string
	SourceEventID string
	ObservedAt    time.Time
	ValidFrom     time.Time
	ValidTo       time.Time
	Confidence    float64
	Metadata      map[string]any
}

// OutcomeWriteResult reports one recorded outcome.
type OutcomeWriteResult struct {
	OutcomeID               string
	DecisionID              string
	TargetCount             uint32
	EventID                 string
	DurabilityStatus        string
	ProjectionStatus        string
	ProjectionErrorCategory string
}

// New constructs one platform knowledge write service.
func New(query ports.GraphQueryStore, graph ports.ProjectionGraphStore) *Service {
	_ = query // Retained in the constructor for compatibility; graph lookup is not a durability precondition.
	return &Service{graph: graph, durabilityMode: DurabilityRequired}
}

func (s *Service) WithDurabilityMode(mode DurabilityMode) *Service {
	if s == nil {
		return nil
	}
	if mode == DurabilityLegacyProjectionOnly {
		s.durabilityMode = mode
	} else {
		s.durabilityMode = DurabilityRequired
	}
	return s
}

// WithAppendLog wires an optional durable append log for workflow events.
func (s *Service) WithAppendLog(appendLog ports.AppendLog) *Service {
	if s == nil {
		return nil
	}
	s.appendLog = appendLog
	return s
}

// WriteDecision records one decision node plus its target, evidence, and action links.
func (s *Service) WriteDecision(ctx context.Context, request DecisionWriteRequest) (*DecisionWriteResult, error) {
	return s.writeDecision(ctx, request, false)
}

// WriteAuthenticatedPacketDecision records a decision reached through the authenticated
// decision-packet workflow. This method is intentionally separate from the public knowledge
// write path so replay consumers can distinguish server-routed packet decisions from
// client-supplied metadata claims.
func (s *Service) WriteAuthenticatedPacketDecision(ctx context.Context, request DecisionWriteRequest) (*DecisionWriteResult, error) {
	return s.writeDecision(ctx, request, true)
}

func (s *Service) writeDecision(ctx context.Context, request DecisionWriteRequest, authenticatedPacket bool) (*DecisionWriteResult, error) {
	if s == nil {
		return nil, ErrRuntimeUnavailable
	}
	decisionType := strings.TrimSpace(request.DecisionType)
	if decisionType == "" {
		return nil, fmt.Errorf("%w: decision type is required", ErrInvalidRequest)
	}
	targetIDs := normalizeIDs(request.TargetIDs)
	if len(targetIDs) == 0 {
		return nil, fmt.Errorf("%w: decision target ids are required", ErrInvalidRequest)
	}
	tenantID := inferTenantID(request.Metadata, targetIDs...)
	if err := validateTenantScopedIDs(tenantID, append(append(append([]string{request.ID}, targetIDs...), request.EvidenceIDs...), request.ActionIDs...)...); err != nil {
		return nil, err
	}
	entityType := decisionEntityType
	if authenticatedPacket {
		entityType = packetDecisionEntityType
	} else if strings.HasPrefix(strings.TrimSpace(request.ID), "urn:cerebro:"+tenantID+":"+packetDecisionEntityType+":") {
		return nil, fmt.Errorf("%w: packet decision id namespace is server-owned", ErrInvalidRequest)
	}
	sourceSystem := firstNonEmpty(strings.TrimSpace(request.SourceSystem), defaultSourceSystem)
	decisionID := workflowevents.CanonicalWorkflowID(tenantID, entityType, request.ID, decisionType, targetIDs, request.ObservedAt)
	observedAt := normalizeObservedAt(request.ObservedAt)
	validFrom := normalizeValidFrom(request.ValidFrom, observedAt)
	status := firstNonEmpty(strings.TrimSpace(request.Status), defaultDecisionStatus)
	validTo := ""
	if !request.ValidTo.UTC().IsZero() {
		validTo = request.ValidTo.UTC().Format(time.RFC3339Nano)
	}
	event, err := workflowevents.NewDecisionRecordedEvent(workflowevents.DecisionRecorded{
		TenantID:      tenantID,
		DecisionID:    decisionID,
		DecisionType:  decisionType,
		Status:        status,
		MadeBy:        strings.TrimSpace(request.MadeBy),
		Rationale:     strings.TrimSpace(request.Rationale),
		TargetIDs:     targetIDs,
		EvidenceIDs:   normalizeIDs(request.EvidenceIDs),
		ActionIDs:     normalizeIDs(request.ActionIDs),
		SourceSystem:  sourceSystem,
		SourceEventID: strings.TrimSpace(request.SourceEventID),
		ObservedAt:    observedAt.Format(time.RFC3339Nano),
		ValidFrom:     validFrom.Format(time.RFC3339Nano),
		ValidTo:       validTo,
		Confidence:    request.Confidence,
		Metadata:      request.Metadata,
	})
	if err != nil {
		return nil, err
	}
	if authenticatedPacket {
		event.Attributes[workflowevents.EventAttributeDecisionTrust] = workflowevents.DecisionTrustAuthenticatedPacket
	}
	statuses, err := s.recordAndProject(ctx, event)
	if err != nil {
		return nil, fmt.Errorf("record decision workflow event %q: %w", event.GetId(), err)
	}
	return &DecisionWriteResult{
		DecisionID:              decisionID,
		TargetCount:             boundedUint32(len(targetIDs)),
		EventID:                 event.GetId(),
		DurabilityStatus:        statuses.DurabilityStatus,
		ProjectionStatus:        statuses.ProjectionStatus,
		ProjectionErrorCategory: statuses.ProjectionErrorCategory,
	}, nil
}

// WriteAction records one action node plus its target links and optional decision context.
func (s *Service) WriteAction(ctx context.Context, request ActionWriteRequest) (*ActionWriteResult, error) {
	if s == nil {
		return nil, ErrRuntimeUnavailable
	}
	title := strings.TrimSpace(request.Title)
	if title == "" {
		return nil, fmt.Errorf("%w: action title is required", ErrInvalidRequest)
	}
	targetIDs := normalizeIDs(request.TargetIDs)
	if len(targetIDs) == 0 {
		return nil, fmt.Errorf("%w: action target ids are required", ErrInvalidRequest)
	}
	tenantID := inferTenantID(request.Metadata, append(targetIDs, request.DecisionID)...)
	if err := validateTenantScopedIDs(tenantID, append(targetIDs, request.DecisionID)...); err != nil {
		return nil, err
	}
	sourceSystem := firstNonEmpty(strings.TrimSpace(request.SourceSystem), defaultSourceSystem)
	decisionID := ""
	if strings.TrimSpace(request.DecisionID) != "" {
		decisionID = workflowevents.CanonicalWorkflowID(tenantID, decisionEntityType, request.DecisionID, decisionEntityType, targetIDs, request.ValidFrom)
	}
	observedAt := normalizeObservedAt(request.ObservedAt)
	validFrom := normalizeValidFrom(request.ValidFrom, observedAt)
	actionType := firstNonEmpty(strings.TrimSpace(request.InsightType), defaultActionType)
	actionID := workflowevents.CanonicalWorkflowID(tenantID, actionEntityType, request.ID, actionType, append([]string{decisionID}, targetIDs...), request.ObservedAt)
	validTo := ""
	if !request.ValidTo.UTC().IsZero() {
		validTo = request.ValidTo.UTC().Format(time.RFC3339Nano)
	}
	event, err := workflowevents.NewActionRecordedEvent(workflowevents.ActionRecorded{
		TenantID:         tenantID,
		ActionID:         actionID,
		ActionType:       actionType,
		Status:           defaultActionStatus,
		RecommendationID: strings.TrimSpace(request.RecommendationID),
		InsightType:      strings.TrimSpace(request.InsightType),
		Title:            title,
		Summary:          strings.TrimSpace(request.Summary),
		DecisionID:       decisionID,
		TargetIDs:        targetIDs,
		SourceSystem:     sourceSystem,
		SourceEventID:    strings.TrimSpace(request.SourceEventID),
		ObservedAt:       observedAt.Format(time.RFC3339Nano),
		ValidFrom:        validFrom.Format(time.RFC3339Nano),
		ValidTo:          validTo,
		Confidence:       request.Confidence,
		AutoGenerated:    request.AutoGenerated,
		Metadata:         request.Metadata,
	})
	if err != nil {
		return nil, err
	}
	statuses, err := s.recordAndProject(ctx, event)
	if err != nil {
		return nil, fmt.Errorf("record action workflow event %q: %w", event.GetId(), err)
	}
	return &ActionWriteResult{
		ActionID:                actionID,
		DecisionID:              decisionID,
		TargetCount:             boundedUint32(len(targetIDs)),
		EventID:                 event.GetId(),
		DurabilityStatus:        statuses.DurabilityStatus,
		ProjectionStatus:        statuses.ProjectionStatus,
		ProjectionErrorCategory: statuses.ProjectionErrorCategory,
	}, nil
}

// WriteOutcome records one outcome node tied back to one decision.
func (s *Service) WriteOutcome(ctx context.Context, request OutcomeWriteRequest) (*OutcomeWriteResult, error) {
	if s == nil {
		return nil, ErrRuntimeUnavailable
	}
	outcomeType := strings.TrimSpace(request.OutcomeType)
	if outcomeType == "" {
		return nil, fmt.Errorf("%w: outcome type is required", ErrInvalidRequest)
	}
	verdict := strings.TrimSpace(request.Verdict)
	if verdict == "" {
		return nil, fmt.Errorf("%w: outcome verdict is required", ErrInvalidRequest)
	}
	targetIDs := normalizeIDs(request.TargetIDs)
	tenantID := inferTenantID(request.Metadata, append(targetIDs, request.DecisionID)...)
	if err := validateTenantScopedIDs(tenantID, append(targetIDs, request.DecisionID)...); err != nil {
		return nil, err
	}
	sourceSystem := firstNonEmpty(strings.TrimSpace(request.SourceSystem), defaultSourceSystem)
	decisionID := workflowevents.CanonicalWorkflowID(tenantID, decisionEntityType, request.DecisionID, decisionEntityType, targetIDs, request.ValidFrom)
	if strings.TrimSpace(request.DecisionID) == "" {
		return nil, fmt.Errorf("%w: outcome decision id is required", ErrInvalidRequest)
	}
	observedAt := normalizeObservedAt(request.ObservedAt)
	validFrom := normalizeValidFrom(request.ValidFrom, observedAt)
	outcomeID := workflowevents.CanonicalWorkflowID(tenantID, outcomeEntityType, request.ID, outcomeType, append([]string{decisionID}, targetIDs...), request.ObservedAt)
	validTo := ""
	if !request.ValidTo.UTC().IsZero() {
		validTo = request.ValidTo.UTC().Format(time.RFC3339Nano)
	}
	event, err := workflowevents.NewOutcomeRecordedEvent(workflowevents.OutcomeRecorded{
		TenantID:      tenantID,
		OutcomeID:     outcomeID,
		DecisionID:    decisionID,
		OutcomeType:   outcomeType,
		Verdict:       verdict,
		ImpactScore:   request.ImpactScore,
		TargetIDs:     targetIDs,
		SourceSystem:  sourceSystem,
		SourceEventID: strings.TrimSpace(request.SourceEventID),
		ObservedAt:    observedAt.Format(time.RFC3339Nano),
		ValidFrom:     validFrom.Format(time.RFC3339Nano),
		ValidTo:       validTo,
		Confidence:    request.Confidence,
		Metadata:      request.Metadata,
	})
	if err != nil {
		return nil, err
	}
	statuses, err := s.recordAndProject(ctx, event)
	if err != nil {
		return nil, fmt.Errorf("record outcome workflow event %q: %w", event.GetId(), err)
	}
	return &OutcomeWriteResult{
		OutcomeID:               outcomeID,
		DecisionID:              decisionID,
		TargetCount:             boundedUint32(len(targetIDs)),
		EventID:                 event.GetId(),
		DurabilityStatus:        statuses.DurabilityStatus,
		ProjectionStatus:        statuses.ProjectionStatus,
		ProjectionErrorCategory: statuses.ProjectionErrorCategory,
	}, nil
}

func boundedUint32(value int) uint32 {
	if value <= 0 {
		return 0
	}
	if value > math.MaxUint32 {
		return math.MaxUint32
	}
	return uint32(value)
}

type writeStatuses struct {
	DurabilityStatus        string
	ProjectionStatus        string
	ProjectionErrorCategory string
}

func (s *Service) recordAndProject(ctx context.Context, event *cerebrov1.EventEnvelope) (writeStatuses, error) {
	statuses := writeStatuses{DurabilityStatus: DurabilityNotRecorded, ProjectionStatus: ProjectionNotConfigured}
	if s == nil {
		return statuses, ErrRuntimeUnavailable
	}
	if s.appendLog == nil {
		if s.durabilityMode == DurabilityRequired {
			recordKnowledgeWriteTelemetry(ctx, event, statuses, "append_log_not_configured")
			return statuses, fmt.Errorf("%w: durable append log is required", ErrRuntimeUnavailable)
		}
	} else {
		if err := s.appendLog.Append(ctx, event); err != nil {
			recordKnowledgeWriteTelemetry(ctx, event, statuses, "append_failed")
			return statuses, err
		}
		statuses.DurabilityStatus = DurabilityRecorded
	}
	if s.graph == nil {
		recordKnowledgeWriteTelemetry(ctx, event, statuses, "")
		return statuses, nil
	}
	if _, err := workflowprojection.New(s.graph).Project(ctx, event); err != nil {
		statuses.ProjectionStatus = ProjectionFailed
		statuses.ProjectionErrorCategory = ProjectionErrorGraph
		recordKnowledgeWriteTelemetry(ctx, event, statuses, ProjectionErrorGraph)
		return statuses, nil //nolint:nilerr // The append succeeded; projection failure is an explicit replayable result state.
	}
	statuses.ProjectionStatus = ProjectionProjected
	recordKnowledgeWriteTelemetry(ctx, event, statuses, "")
	return statuses, nil
}

func recordKnowledgeWriteTelemetry(ctx context.Context, event *cerebrov1.EventEnvelope, statuses writeStatuses, errorCategory string) {
	eventKind := ""
	if event != nil {
		eventKind = event.GetKind()
	}
	telemetry.Event(ctx, "knowledge.write", telemetry.Attrs(
		telemetry.Field{Key: "knowledge.event_kind", Value: eventKind},
		telemetry.Field{Key: "knowledge.durability_status", Value: statuses.DurabilityStatus},
		telemetry.Field{Key: "knowledge.projection_status", Value: statuses.ProjectionStatus},
		telemetry.Field{Key: "error_category", Value: errorCategory},
	))
	telemetry.IncrementMain(ctx, "knowledge.write.count", 1)
	telemetry.IncrementMain(ctx, "knowledge.write."+statuses.DurabilityStatus+".count", 1)
	telemetry.IncrementMain(ctx, "knowledge.write.projection."+statuses.ProjectionStatus+".count", 1)
}

func inferTenantID(metadata map[string]any, ids ...string) string {
	if value, ok := metadata["tenant_id"].(string); ok && strings.TrimSpace(value) != "" {
		return strings.TrimSpace(value)
	}
	for _, id := range ids {
		trimmed := strings.TrimSpace(id)
		if !strings.HasPrefix(trimmed, "urn:cerebro:") {
			continue
		}
		parts := strings.Split(trimmed, ":")
		if len(parts) >= 4 && strings.TrimSpace(parts[2]) != "" {
			return strings.TrimSpace(parts[2])
		}
	}
	return defaultPlatformTenant
}

func validateTenantScopedIDs(tenantID string, ids ...string) error {
	tenantID = strings.TrimSpace(tenantID)
	for _, id := range ids {
		trimmed := strings.TrimSpace(id)
		if !strings.HasPrefix(trimmed, "urn:cerebro:") {
			continue
		}
		parts := strings.Split(trimmed, ":")
		if len(parts) < 4 || strings.TrimSpace(parts[2]) != tenantID {
			return fmt.Errorf("%w: cross-tenant knowledge reference", ErrInvalidRequest)
		}
	}
	return nil
}

func normalizeIDs(values []string) []string {
	seen := make(map[string]struct{}, len(values))
	normalized := make([]string, 0, len(values))
	for _, value := range values {
		trimmed := strings.TrimSpace(value)
		if trimmed == "" {
			continue
		}
		if _, ok := seen[trimmed]; ok {
			continue
		}
		seen[trimmed] = struct{}{}
		normalized = append(normalized, trimmed)
	}
	return normalized
}

func normalizeObservedAt(value time.Time) time.Time {
	observedAt := value.UTC()
	if observedAt.IsZero() {
		return time.Now().UTC()
	}
	return observedAt
}

func normalizeValidFrom(value time.Time, observedAt time.Time) time.Time {
	validFrom := value.UTC()
	if validFrom.IsZero() {
		return observedAt
	}
	return validFrom
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if trimmed := strings.TrimSpace(value); trimmed != "" {
			return trimmed
		}
	}
	return ""
}
