// Code generated by sourceplangen; DO NOT EDIT.

package sourceworker

import (
	cerebrov1 "github.com/writer/cerebro/gen/cerebro/v1"
)

// AzureAuthorizationPolicyPlan returns the generated, credential-free plan for
// the first-party Azure authorization policy family. Runtime code does not read
// the connector catalog YAML.
func AzureAuthorizationPolicyPlan() *cerebrov1.SourceExecutionPlanV1 {
	plan := &cerebrov1.SourceExecutionPlanV1{
		PlanId:              "source-plan-v1:azure:authorization_policy",
		SourceId:            "azure",
		FamilyId:            "authorization_policy",
		ProviderKernel:      "azure.authorization_policy",
		Method:              "GET",
		Origin:              "https://graph.microsoft.com",
		Path:                "/v1.0/policies/authorizationPolicy",
		RecordSelector:      "$",
		IdField:             "id",
		SingletonFallbackId: "authorizationPolicy",
		MaxResponseBytes:    maxResponseBytes,
		EventKind:           "azure.authorization_policy",
		SchemaRef:           "azure/authorization_policy/v1",
		RequiredAttributes:    []string{"family", "resource_id", "resource_name", "resource_provider", "resource_type"},
		RequiredPayloadFields: []string{"id"},
	}
	plan.PlanDigestSha256 = executionPlanDigest(plan)
	return plan
}
