"""Utility helpers for findings producers."""

from __future__ import annotations

__all__ = [
    "AnonymousLinkSummary",
    "CiPipelineExposureEvidence",
    "ExternalSharingEvidence",
    "ExternalUserAccess",
    "IdentityUserEvidence",
    "NetworkExposureDetail",
    "NetworkExposureEvidence",
    "ProducerRunContext",
    "RunnerGroupExposureEvidence",
    "RunnerHostExposureEvidence",
    "RunnerMetadata",
    "SecretArtifactSummary",
    "SecurityGroupExposureEvidence",
    "SecurityGroupRuleSummary",
    "SharePointAnonymousLinkEvidence",
    "StorageSecretExposureEvidence",
    "TelemetryIncidentEvidence",
    "WorkflowPermissionEvidence",
    "analyze_instance_network_exposure",
    "build_ci_pipeline_exposure",
    "build_external_sharing_evidence",
    "build_identity_user_evidence",
    "build_network_exposure_evidence",
    "build_runner_group_exposure",
    "build_runner_host_exposure",
    "build_security_group_exposure",
    "build_sharepoint_anonymous_link_evidence",
    "build_storage_secret_evidence",
    "build_telemetry_incident_evidence",
    "build_workflow_permission_evidence",
    "clip_sequence",
    "coerce_mapping",
    "coerce_mapping_sequence",
    "coerce_rule_id",
    "coerce_str_sequence",
    "compact_mapping",
    "downgrade_severity_for_namespace_policy",
    "exposures_contain_public",
    "exposures_contain_type",
    "get_namespace_network_posture",
    "has_public_interface",
    "max_severity",
    "resolve_rule_id",
    "security_group_rule_allows_public",
]

from .collections import coerce_mapping, coerce_mapping_sequence, coerce_str_sequence
from .context import ProducerRunContext, get_namespace_network_posture
from .evidence import (
    AnonymousLinkSummary,
    CiPipelineExposureEvidence,
    ExternalSharingEvidence,
    ExternalUserAccess,
    IdentityUserEvidence,
    NetworkExposureDetail,
    NetworkExposureEvidence,
    RunnerGroupExposureEvidence,
    RunnerHostExposureEvidence,
    RunnerMetadata,
    SecretArtifactSummary,
    SecurityGroupExposureEvidence,
    SecurityGroupRuleSummary,
    SharePointAnonymousLinkEvidence,
    StorageSecretExposureEvidence,
    TelemetryIncidentEvidence,
    WorkflowPermissionEvidence,
    build_ci_pipeline_exposure,
    build_external_sharing_evidence,
    build_identity_user_evidence,
    build_network_exposure_evidence,
    build_runner_group_exposure,
    build_runner_host_exposure,
    build_security_group_exposure,
    build_sharepoint_anonymous_link_evidence,
    build_storage_secret_evidence,
    build_telemetry_incident_evidence,
    build_workflow_permission_evidence,
    clip_sequence,
    compact_mapping,
)
from .exposure import (
    analyze_instance_network_exposure,
    has_public_interface,
    security_group_rule_allows_public,
)
from .rules import coerce_rule_id, resolve_rule_id
from .severity import (
    downgrade_severity_for_namespace_policy,
    exposures_contain_public,
    exposures_contain_type,
    max_severity,
)
