package graphactionworkflow

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/writer/cerebro/internal/graphactions"
	"github.com/writer/cerebro/internal/ports"
	"github.com/writer/cerebro/internal/workflowevents"
)

func BeforeLink(appendLog ports.AppendLog) func(context.Context, *ports.FindingRecord, *graphactions.GraphAction, string) error {
	return func(ctx context.Context, finding *ports.FindingRecord, action *graphactions.GraphAction, target string) error {
		return Record(ctx, appendLog, finding, action, target)
	}
}

func Record(ctx context.Context, appendLog ports.AppendLog, finding *ports.FindingRecord, action *graphactions.GraphAction, target string) error {
	if appendLog == nil || finding == nil || action == nil {
		return nil
	}
	observedAt := time.Now().UTC()
	if action.UpdatedAtUnix > 0 {
		observedAt = time.Unix(action.UpdatedAtUnix, 0).UTC()
	} else if action.CreatedAtUnix > 0 {
		observedAt = time.Unix(action.CreatedAtUnix, 0).UTC()
	}
	externalID := strings.TrimSpace(action.ExternalID)
	if externalID == "" {
		externalID = strings.TrimSpace(action.ID)
	}
	actionID := fmt.Sprintf("urn:cerebro:%s:graph_action:%s", strings.TrimSpace(finding.TenantID), externalID)
	event, err := workflowevents.NewActionRecordedEvent(workflowevents.ActionRecorded{
		TenantID:      strings.TrimSpace(finding.TenantID),
		ActionID:      actionID,
		ActionType:    strings.TrimSpace(action.Action),
		Status:        strings.TrimSpace(firstNonEmpty(action.ExternalStatus, action.Status, "queued")),
		Title:         "Graph action " + strings.TrimSpace(action.Action),
		Summary:       strings.TrimSpace(action.Reason),
		TargetIDs:     targets(finding, action, target),
		SourceSystem:  strings.TrimSpace(action.Provider),
		SourceEventID: externalID,
		ObservedAt:    observedAt.Format(time.RFC3339Nano),
		ValidFrom:     observedAt.Format(time.RFC3339Nano),
		AutoGenerated: true,
		Metadata: map[string]any{
			"finding_id":      strings.TrimSpace(finding.ID),
			"finding_rule_id": strings.TrimSpace(finding.RuleID),
			"provider":        strings.TrimSpace(action.Provider),
			"external_id":     externalID,
			"external_url":    strings.TrimSpace(action.ExternalURL),
			"target":          strings.TrimSpace(firstNonEmpty(target, action.Target)),
			"idempotency_key": strings.TrimSpace(action.IdempotencyKey),
			"external_status": strings.TrimSpace(action.ExternalStatus),
			"source":          strings.TrimSpace(action.Source),
		},
	})
	if err != nil {
		return err
	}
	return appendLog.Append(ctx, event)
}

func targets(finding *ports.FindingRecord, action *graphactions.GraphAction, target string) []string {
	values := []string{}
	if action != nil && action.Metadata != nil {
		for _, key := range []string{"subject_urn", "resource_urn"} {
			if value := strings.TrimSpace(action.Metadata[key]); value != "" {
				values = append(values, value)
			}
		}
	}
	if finding != nil {
		if value := strings.TrimSpace(finding.Attributes["primary_resource_urn"]); value != "" {
			values = append(values, value)
		}
		values = append(values, finding.ResourceURNs...)
	}
	if value := strings.TrimSpace(firstNonEmpty(target, actionTarget(action))); value != "" {
		values = append(values, "graph_action_target:"+value)
	}
	return dedupe(values)
}

func actionTarget(action *graphactions.GraphAction) string {
	if action == nil {
		return ""
	}
	return action.Target
}

func dedupe(values []string) []string {
	seen := map[string]struct{}{}
	out := []string{}
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value == "" {
			continue
		}
		if _, ok := seen[value]; ok {
			continue
		}
		seen[value] = struct{}{}
		out = append(out, value)
	}
	return out
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if trimmed := strings.TrimSpace(value); trimmed != "" {
			return trimmed
		}
	}
	return ""
}
