package graphactionworkflow

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net/url"
	"strings"
	"time"

	"github.com/writer/cerebro/internal/graphactions"
	"github.com/writer/cerebro/internal/observability"
	"github.com/writer/cerebro/internal/ports"
	"github.com/writer/cerebro/internal/workflowevents"
)

func BeforeLink(appendLog ports.AppendLog) func(context.Context, *ports.FindingRecord, *graphactions.GraphAction, string) error {
	return func(ctx context.Context, finding *ports.FindingRecord, action *graphactions.GraphAction, target string) error {
		return Record(ctx, appendLog, finding, action, target)
	}
}

func Record(ctx context.Context, appendLog ports.AppendLog, finding *ports.FindingRecord, action *graphactions.GraphAction, target string) error {
	if appendLog == nil || finding == nil || action == nil {
		return nil
	}
	observedAt := time.Now().UTC()
	if action.UpdatedAtUnix > 0 {
		observedAt = time.Unix(action.UpdatedAtUnix, 0).UTC()
	} else if action.CreatedAtUnix > 0 {
		observedAt = time.Unix(action.CreatedAtUnix, 0).UTC()
	}
	externalID := strings.TrimSpace(action.ExternalID)
	if externalID == "" {
		externalID = strings.TrimSpace(action.ID)
	}
	actionID := canonicalActionID(finding.TenantID, action.Provider, action.Action, externalID)
	status := strings.TrimSpace(firstNonEmpty(action.ExternalStatus, action.Status, "queued"))
	reconciliationStatus := graphactions.NormalizeActionStatus(firstNonEmpty(action.Status, status))
	targetIDs := targets(finding, action, target)
	dryRun := action.Metadata != nil && strings.EqualFold(action.Metadata["dry_run"], "true")
	event, err := workflowevents.NewActionRecordedEvent(workflowevents.ActionRecorded{
		TenantID:      strings.TrimSpace(finding.TenantID),
		ActionID:      actionID,
		ActionType:    strings.TrimSpace(action.Action),
		Status:        status,
		Title:         "Graph action " + strings.TrimSpace(action.Action),
		Summary:       strings.TrimSpace(action.Reason),
		TargetIDs:     targetIDs,
		SourceSystem:  strings.TrimSpace(action.Provider),
		SourceEventID: externalID,
		ObservedAt:    observedAt.Format(time.RFC3339Nano),
		ValidFrom:     observedAt.Format(time.RFC3339Nano),
		AutoGenerated: true,
		Metadata: map[string]any{
			"finding_id":            strings.TrimSpace(finding.ID),
			"finding_rule_id":       strings.TrimSpace(finding.RuleID),
			"provider":              strings.TrimSpace(action.Provider),
			"external_id":           externalID,
			"external_url":          strings.TrimSpace(action.ExternalURL),
			"target_urn":            firstNonEmpty(targetIDs...),
			"target":                strings.TrimSpace(firstNonEmpty(target, action.Target)),
			"idempotency_key":       strings.TrimSpace(action.IdempotencyKey),
			"external_status":       strings.TrimSpace(action.ExternalStatus),
			"reconciliation_status": reconciliationStatus,
			"dry_run":               dryRun,
			"source":                strings.TrimSpace(action.Source),
		},
	})
	if err != nil {
		return err
	}
	if err := appendLog.Append(ctx, event); err != nil {
		return err
	}
	observability.RecordGraphAction(ctx, observability.GraphActionMetrics{
		Provider:       action.Provider,
		Action:         action.Action,
		Status:         status,
		ExternalStatus: action.ExternalStatus,
		DryRun:         dryRun,
	})
	return nil
}

func targets(finding *ports.FindingRecord, action *graphactions.GraphAction, target string) []string {
	values := []string{}
	if action != nil && action.Metadata != nil {
		for _, key := range []string{"subject_urn", "resource_urn"} {
			if value := strings.TrimSpace(action.Metadata[key]); value != "" {
				values = append(values, value)
			}
		}
	}
	if finding != nil {
		if value := strings.TrimSpace(finding.Attributes["primary_resource_urn"]); value != "" {
			values = append(values, value)
		}
		values = append(values, finding.ResourceURNs...)
	}
	if value := strings.TrimSpace(firstNonEmpty(target, actionTarget(action))); value != "" {
		values = append(values, "graph_action_target:"+value)
	}
	return dedupe(values)
}

func actionTarget(action *graphactions.GraphAction) string {
	if action == nil {
		return ""
	}
	return action.Target
}

func canonicalActionID(tenantID string, provider string, action string, externalID string) string {
	tenantID = strings.TrimSpace(tenantID)
	sum := sha256.Sum256([]byte(strings.Join([]string{
		tenantID,
		strings.TrimSpace(provider),
		strings.TrimSpace(action),
		strings.TrimSpace(externalID),
	}, "\x00")))
	return fmt.Sprintf("urn:cerebro:%s:graph_action:%s", urnSegment(tenantID), hex.EncodeToString(sum[:]))
}

func urnSegment(value string) string {
	escaped := url.PathEscape(strings.TrimSpace(value))
	return strings.ReplaceAll(escaped, ":", "%3A")
}

func dedupe(values []string) []string {
	seen := map[string]struct{}{}
	out := []string{}
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value == "" {
			continue
		}
		if _, ok := seen[value]; ok {
			continue
		}
		seen[value] = struct{}{}
		out = append(out, value)
	}
	return out
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if trimmed := strings.TrimSpace(value); trimmed != "" {
			return trimmed
		}
	}
	return ""
}
