export const actionIds = {
  refreshHome: "cerebro_refresh_home",
  findingNote: "cerebro_finding_note",
  findingAssign: "cerebro_finding_assign",
  findingDue: "cerebro_finding_due",
  findingResolve: "cerebro_finding_resolve",
  findingSuppress: "cerebro_finding_suppress",
  findingEvidence: "cerebro_finding_evidence",
  graphActionDryRun: "cerebro_graph_action_dry_run",
  runtimeSync: "cerebro_runtime_sync",
  runtimeIngest: "cerebro_runtime_ingest",
  runtimeEvaluate: "cerebro_runtime_evaluate",
  autonomyApprove: "cerebro_autonomy_approve",
  autonomyReject: "cerebro_autonomy_reject",
  proactiveSuggestionAccept: "cerebro_proactive_suggestion_accept",
  proactiveSuggestionDismiss: "cerebro_proactive_suggestion_dismiss",
  monitorSuggestionAccept: "cerebro_monitor_suggestion_accept",
  monitorSuggestionDismiss: "cerebro_monitor_suggestion_dismiss",
  assistantFeedbackHelpful: "cerebro_assistant_feedback_helpful",
  assistantFeedbackHelpfulDetail: "cerebro_assistant_feedback_helpful_detail",
  assistantFeedbackNeedsWork: "cerebro_assistant_feedback_needs_work",
  assistantFeedbackEvidence: "cerebro_assistant_feedback_evidence",
  riskAttestationResponse: "cerebro_risk_attestation_response",
} as const;
