**

!package.json
!package-lock.json

!apps/
!apps/slack-companion/
!apps/slack-companion/package.json
!apps/web/
!apps/web/**

!sdk/
!sdk/typescript/
!sdk/typescript/package.json

apps/web/.env
apps/web/.env.*
apps/web/.next
apps/web/coverage
apps/web/node_modules
apps/web/npm-debug.log*
apps/web/*.pem
