[package]
name = "cerebro-graphagent-staticvalidator-fuzz"
version = "0.0.0"
publish = false
edition = "2024"
license = "Apache-2.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
cerebro-graphagent-staticvalidator = { path = "..", version = "0.1.0" }

[[bin]]
name = "validate"
path = "fuzz_targets/validate.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
