package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func generateArtifacts(ir migrationIR, manifest deletionManifest) (map[string][]byte, error) {
	artifacts := map[string][]byte{}
	irPayload, err := marshalJSON(ir)
	if err != nil {
		return nil, err
	}
	manifestPayload, err := marshalJSON(manifest)
	if err != nil {
		return nil, err
	}
	artifacts["migration-ir.json"] = irPayload
	artifacts["deletion-manifest.json"] = manifestPayload
	schemaPayload, err := marshalJSON(buildClosedSchemaContract())
	if err != nil {
		return nil, err
	}
	artifacts["schema/closed-contract.json"] = schemaPayload
	for path, payload := range map[string][]byte{
		"rust/scaffold.rs":    generateRustScaffold(ir),
		"rust/contracts.rs":   generateRustContracts(ir, manifest),
		"rust/parity_test.rs": generateRustParityTest(ir, manifest),
	} {
		formatted, err := formatGeneratedRust(payload)
		if err != nil {
			return nil, fmt.Errorf("format %s: %w", path, err)
		}
		artifacts[path] = formatted
	}
	if source := sourceIR(ir); source != nil {
		artifacts["registry/standard_source_plan_index.txt"] = []byte(
			"standard-source-plan-index/v1\n" + ir.Subject.ID + "\t" + strings.Join(source.RuntimeFamilies, ",") + "\n",
		)
	}
	return artifacts, nil
}

func formatGeneratedRust(payload []byte) ([]byte, error) {
	command := exec.Command("rustfmt", "--edition", "2024", "--emit", "stdout") // #nosec G204 -- fixed repository toolchain command and arguments.
	command.Stdin = bytes.NewReader(payload)
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	command.Stdout = &stdout
	command.Stderr = &stderr
	if err := command.Run(); err != nil {
		return nil, fmt.Errorf("rustfmt: %w: %s", err, strings.TrimSpace(stderr.String()))
	}
	return stdout.Bytes(), nil
}

func generateRustScaffold(ir migrationIR) []byte {
	var output strings.Builder
	output.WriteString("// Code generated by tools/rustcarve. DO NOT EDIT.\n\n")
	output.WriteString("#[path = \"contracts.rs\"]\npub mod contracts;\n")
	output.WriteString("#[cfg(test)]\n#[path = \"parity_test.rs\"]\nmod parity_test;\n\n")
	fmt.Fprintf(&output, "pub const RUSTCARVE_TOOL_REVISION: &str = %s;\n", strconv.Quote(ir.ToolRevision))
	fmt.Fprintf(&output, "pub const MIGRATION_IR_VERSION: &str = %s;\n", strconv.Quote(ir.IRVersion))
	fmt.Fprintf(&output, "pub const MIGRATION_IR_DIGEST_SHA256: &str = %s;\n", strconv.Quote(ir.DigestSHA256))
	fmt.Fprintf(&output, "pub const SUBJECT_ID: &str = %s;\n", strconv.Quote(ir.Subject.ID))
	fmt.Fprintf(&output, "pub const RUST_IMPLEMENTATION_REVISION: &str = %s;\n\n", strconv.Quote(ir.Subject.RustImplementationRevision))
	output.WriteString("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n")
	output.WriteString("pub struct AuthenticatedScope<'a> {\n    pub tenant_id: &'a str,\n")
	if ir.Scope.WorkspacePolicy != "forbidden" {
		output.WriteString("    pub workspace_id: Option<&'a str>,\n")
	}
	output.WriteString("}\n\n")
	output.WriteString("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub enum ScopeError { MissingTenant, MissingWorkspace, ForbiddenWorkspace }\n\n")
	output.WriteString("pub fn validate_scope(scope: AuthenticatedScope<'_>) -> Result<(), ScopeError> {\n")
	output.WriteString("    if scope.tenant_id.trim().is_empty() { return Err(ScopeError::MissingTenant); }\n")
	switch ir.Scope.WorkspacePolicy {
	case "required":
		output.WriteString("    if scope.workspace_id.is_none_or(|value| value.trim().is_empty()) { return Err(ScopeError::MissingWorkspace); }\n")
	case "optional":
		output.WriteString("    if scope.workspace_id.is_some_and(|value| value.trim().is_empty()) { return Err(ScopeError::MissingWorkspace); }\n")
	}
	output.WriteString("    Ok(())\n}\n")
	return []byte(output.String())
}

func generateRustContracts(ir migrationIR, manifest deletionManifest) []byte {
	var output strings.Builder
	output.WriteString("// Code generated by tools/rustcarve. DO NOT EDIT.\n\n")
	output.WriteString("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub struct ArtifactDigest { pub path: &'static str, pub role: &'static str, pub digest_sha256: &'static str }\n\n")
	output.WriteString("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub struct AuthorityGate { pub kind: &'static str, pub satisfied: bool, pub reason_code: Option<&'static str>, pub path: &'static str, pub symbol: &'static str, pub digest_sha256: &'static str }\n\n")
	output.WriteString("pub const FIXTURE_CORPUS: &[ArtifactDigest] = &[\n")
	for _, artifact := range ir.Evidence.Fixtures {
		fmt.Fprintf(&output, "    ArtifactDigest { path: %s, role: %s, digest_sha256: %s },\n", strconv.Quote(artifact.Path), strconv.Quote(artifact.Role), strconv.Quote(artifact.DigestSHA256))
	}
	output.WriteString("];\n\npub const PORT_TRACES: &[ArtifactDigest] = &[\n")
	for _, artifact := range ir.Evidence.Traces {
		fmt.Fprintf(&output, "    ArtifactDigest { path: %s, role: %s, digest_sha256: %s },\n", strconv.Quote(artifact.Path), strconv.Quote(artifact.Role), strconv.Quote(artifact.DigestSHA256))
	}
	output.WriteString("];\n")
	fmt.Fprintf(&output, "\npub const REQUIRED_RECEIPT_MODES: &[&str] = &%s;\n", rustStringSlice(manifest.RequiredReceiptModes))
	output.WriteString("pub const ACCEPTED_RECEIPTS: &[ArtifactDigest] = &[\n")
	for _, receipt := range manifest.AcceptedReceipts {
		fmt.Fprintf(&output, "    ArtifactDigest { path: %s, role: %s, digest_sha256: %s },\n", strconv.Quote(receipt.Path), strconv.Quote(receipt.Role), strconv.Quote(receipt.DigestSHA256))
	}
	output.WriteString("];\n")
	fmt.Fprintf(&output, "pub const DELETION_ELIGIBLE: bool = %t;\n", manifest.Eligible)
	reasons := make([]string, len(manifest.ReasonCodes))
	for index, reason := range manifest.ReasonCodes {
		reasons[index] = string(reason)
	}
	fmt.Fprintf(&output, "pub const DELETION_REASON_CODES: &[&str] = &%s;\n", rustStringSlice(reasons))
	output.WriteString("pub const AUTHORITY_GATES: &[AuthorityGate] = &[\n")
	for _, gate := range manifest.AuthorityGates {
		reason := "None"
		if gate.ReasonCode != "" {
			reason = "Some(" + strconv.Quote(string(gate.ReasonCode)) + ")"
		}
		fmt.Fprintf(&output, "    AuthorityGate { kind: %s, satisfied: %t, reason_code: %s, path: %s, symbol: %s, digest_sha256: %s },\n", strconv.Quote(gate.Kind), gate.Satisfied, reason, strconv.Quote(gate.Path), strconv.Quote(gate.Symbol), strconv.Quote(gate.DigestSHA256))
	}
	output.WriteString("];\n")
	var behaviorContract any
	switch {
	case ir.Standard != nil:
		behaviorContract = ir.Standard
	case ir.Provider != nil:
		behaviorContract = ir.Provider
	case ir.GraphQuery != nil:
		behaviorContract = ir.GraphQuery
	case ir.FindingRule != nil:
		behaviorContract = ir.FindingRule
	}
	if behaviorContract != nil {
		payload, _ := json.Marshal(behaviorContract)
		fmt.Fprintf(&output, "\npub const BEHAVIOR_KIND: &str = %s;\n", strconv.Quote(string(ir.BehaviorKind)))
		fmt.Fprintf(&output, "pub const BEHAVIOR_CONTRACT_JSON: &str = %s;\n", strconv.Quote(string(payload)))
	}
	if source := sourceIR(ir); source != nil {
		output.WriteString("\npub const RUNTIME_FAMILIES: &[&str] = &[\n")
		for _, family := range source.RuntimeFamilies {
			fmt.Fprintf(&output, "    %s,\n", strconv.Quote(family))
		}
		output.WriteString("];\n\n")
		output.WriteString("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub struct EventContract { pub kind: &'static str, pub schema_ref: &'static str, pub required_attributes: &'static [&'static str], pub required_payload_fields: &'static [&'static str] }\n\n")
		output.WriteString("pub const EVENT_CONTRACTS: &[EventContract] = &[\n")
		for _, contract := range source.EventContracts {
			fmt.Fprintf(&output, "    EventContract { kind: %s, schema_ref: %s, required_attributes: &%s, required_payload_fields: &%s },\n", strconv.Quote(contract.Kind), strconv.Quote(contract.SchemaRef), rustStringSlice(contract.RequiredAttributes), rustStringSlice(contract.RequiredPayloadFields))
		}
		output.WriteString("];\n")
	}
	return []byte(output.String())
}

func generateRustParityTest(ir migrationIR, manifest deletionManifest) []byte {
	var output strings.Builder
	output.WriteString("// Code generated by tools/rustcarve. DO NOT EDIT.\n\n")
	output.WriteString("use super::{contracts, MIGRATION_IR_DIGEST_SHA256, MIGRATION_IR_VERSION, RUSTCARVE_TOOL_REVISION, RUST_IMPLEMENTATION_REVISION, SUBJECT_ID};\n\n")
	output.WriteString("#[test]\nfn generated_contract_is_closed_and_revision_bound() {\n")
	fmt.Fprintf(&output, "    assert_eq!(RUSTCARVE_TOOL_REVISION, %s);\n", strconv.Quote(ir.ToolRevision))
	fmt.Fprintf(&output, "    assert_eq!(MIGRATION_IR_VERSION, %s);\n", strconv.Quote(ir.IRVersion))
	fmt.Fprintf(&output, "    assert_eq!(MIGRATION_IR_DIGEST_SHA256, %s);\n", strconv.Quote(ir.DigestSHA256))
	fmt.Fprintf(&output, "    assert_eq!(RUST_IMPLEMENTATION_REVISION, %s);\n", strconv.Quote(ir.Subject.RustImplementationRevision))
	fmt.Fprintf(&output, "    assert_eq!(SUBJECT_ID, %s);\n", strconv.Quote(ir.Subject.ID))
	fmt.Fprintf(&output, "    assert_eq!(contracts::FIXTURE_CORPUS.len(), %d);\n", len(ir.Evidence.Fixtures))
	fmt.Fprintf(&output, "    assert_eq!(contracts::PORT_TRACES.len(), %d);\n", len(ir.Evidence.Traces))
	fmt.Fprintf(&output, "    assert_eq!(contracts::REQUIRED_RECEIPT_MODES.len(), %d);\n", len(manifest.RequiredReceiptModes))
	fmt.Fprintf(&output, "    assert_eq!(contracts::ACCEPTED_RECEIPTS.len(), %d);\n", len(manifest.AcceptedReceipts))
	fmt.Fprintf(&output, "    assert_eq!(contracts::DELETION_ELIGIBLE, %t);\n", manifest.Eligible)
	fmt.Fprintf(&output, "    assert_eq!(contracts::DELETION_REASON_CODES.len(), %d);\n", len(manifest.ReasonCodes))
	fmt.Fprintf(&output, "    assert_eq!(contracts::AUTHORITY_GATES.len(), %d);\n", len(manifest.AuthorityGates))
	if manifest.Eligible {
		output.WriteString("    // Deletion eligibility is bound to accepted differential receipts in deletion-manifest.json.\n")
	} else {
		output.WriteString("    // This scaffold is intentionally not deletion-eligible without exact differential receipts.\n")
	}
	output.WriteString("}\n")
	return []byte(output.String())
}

func sourceIR(ir migrationIR) *standardSourceIR {
	if ir.Standard != nil {
		return ir.Standard
	}
	return ir.Provider
}

func rustStringSlice(values []string) string {
	quoted := make([]string, len(values))
	for index, value := range values {
		quoted[index] = strconv.Quote(value)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func marshalJSON(value any) ([]byte, error) {
	payload, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(payload, '\n'), nil
}

func sortedArtifactPaths(artifacts map[string][]byte) []string {
	paths := make([]string, 0, len(artifacts))
	for path := range artifacts {
		paths = append(paths, filepath.Clean(path))
	}
	sort.Strings(paths)
	return paths
}

func checkGenerated(existing, expected []byte) error {
	if bytes.Equal(existing, expected) {
		return nil
	}
	return fmt.Errorf("generated artifact differs")
}
