FROM alpine:3.20

RUN apk add --no-cache curl && addgroup -S cerebro && adduser -S -G cerebro -u 10001 cerebro

COPY .dist/cerebro /usr/local/bin/cerebro
COPY policies /app/policies

WORKDIR /app

USER cerebro

EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/cerebro"]
CMD ["serve"]
