[package]
name = "cerebro-panopticon-resources"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cerebro-wasm-guest = { path = "../../wasmguest" }
serde_json = { version = "1.0.149", features = ["preserve_order"] }

[lints.rust]
unsafe_code = "allow"
