import { writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import openapiTS from "openapi-typescript";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const openapiUrl = process.env.CEREBRO_OPENAPI_URL ?? "http://localhost:8000/openapi.json";
const outputDir = path.resolve(__dirname, "../src/generated");
const outputFile = path.join(outputDir, "openapi.ts");

console.log(`Generating types from ${openapiUrl}`);

try {
  const headers = process.env.CEREBRO_OPENAPI_AUTH_TOKEN
    ? { Authorization: `Bearer ${process.env.CEREBRO_OPENAPI_AUTH_TOKEN}` }
    : undefined;

  const contents = await openapiTS(openapiUrl, {
    httpHeaders: headers,
  });

  await mkdir(outputDir, { recursive: true });
  const banner = "/* eslint-disable */\n// Auto-generated by npm run generate:types\n\n";
  await writeFile(outputFile, banner + contents, "utf8");

  console.log(`✅ Wrote OpenAPI types to ${path.relative(process.cwd(), outputFile)}`);
} catch (error) {
  console.error("❌ Failed to generate types:", error instanceof Error ? error.message : error);
  process.exitCode = 1;
}
