import { writeFile, mkdir, readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import openapiTS, { astToString } from "openapi-typescript";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const openapiUrl = process.env.CEREBRO_OPENAPI_URL ?? "http://localhost:8000/openapi.json";
const specPath = process.env.CEREBRO_OPENAPI_SPEC_PATH;
const outputDir = path.resolve(__dirname, "../src/generated");
const outputFile = path.join(outputDir, "openapi.ts");

if (specPath) {
  console.log(`Generating types from local spec ${specPath}`);
} else {
  console.log(`Generating types from ${openapiUrl}`);
}

try {
  let ast;

  if (specPath) {
    const resolved = path.resolve(process.cwd(), specPath);
    const raw = await readFile(resolved, "utf8");
    const schema = JSON.parse(raw);
    ast = await openapiTS(schema);
  } else {
    const headers = process.env.CEREBRO_OPENAPI_AUTH_TOKEN
      ? { Authorization: `Bearer ${process.env.CEREBRO_OPENAPI_AUTH_TOKEN}` }
      : undefined;

    ast = await openapiTS(openapiUrl, {
      httpHeaders: headers,
    });
  }

  await mkdir(outputDir, { recursive: true });
  const banner = "/* eslint-disable */\n// Auto-generated by npm run generate:types\n\n";
  const contents = astToString(ast);
  await writeFile(outputFile, banner + contents, "utf8");

  console.log(`✅ Wrote OpenAPI types to ${path.relative(process.cwd(), outputFile)}`);
} catch (error) {
  console.error("❌ Failed to generate types:", error instanceof Error ? error.message : error);
  process.exitCode = 1;
}
