apiVersion: cerebro.writer.com/v1alpha1
kind: PolicyFindingRuleTest
cases:
    - name: matching resource produces a finding
      resource:
        resolution: false_positive
        secret_type: azure_storage_account_key
        state: resolved
      wantFinding: true
    - name: non-matching resource passes
      resource:
        resolution: false_positive
        secret_type: azure_storage_account_key
        state: resolved-passing
      wantFinding: false
