import type { AppConfig } from "../src/config/index.js";

type AppConfigOverrides = Omit<Partial<AppConfig>, "slack" | "cerebro" | "evidenceCas" | "infisical" | "pantherMcp" | "triage" | "learning" | "code" | "ticketing" | "complianceContext" | "selfRepair" | "improvement" | "autonomy" | "schedules" | "telemetry" | "coordination" | "a2a"> & {
  slack?: Partial<AppConfig["slack"]>;
  cerebro?: Partial<AppConfig["cerebro"]>;
  evidenceCas?: Partial<AppConfig["evidenceCas"]>;
  infisical?: Partial<AppConfig["infisical"]>;
  pantherMcp?: Partial<AppConfig["pantherMcp"]>;
  triage?: Omit<Partial<AppConfig["triage"]>, "pi"> & { pi?: Partial<AppConfig["triage"]["pi"]> };
  learning?: Partial<AppConfig["learning"]>;
  code?: Partial<AppConfig["code"]>;
  ticketing?: Omit<Partial<AppConfig["ticketing"]>, "jira" | "linear"> & {
    jira?: Partial<AppConfig["ticketing"]["jira"]>;
    linear?: Partial<AppConfig["ticketing"]["linear"]>;
  };
  complianceContext?: Partial<AppConfig["complianceContext"]>;
  selfRepair?: Partial<AppConfig["selfRepair"]>;
  improvement?: Partial<AppConfig["improvement"]>;
  autonomy?: Partial<AppConfig["autonomy"]>;
  schedules?: Partial<AppConfig["schedules"]>;
  telemetry?: Partial<AppConfig["telemetry"]>;
  coordination?: Partial<AppConfig["coordination"]>;
  a2a?: Partial<AppConfig["a2a"]>;
};

export function testConfig(overrides: AppConfigOverrides = {}): AppConfig {
  const base: AppConfig = {
    nodeEnv: "test",
    port: 3000,
    slack: {
      botToken: "xoxb-test",
      socketMode: true,
      appToken: "xapp-test",
      allowedTeamIds: new Set<string>(),
      findingWriteUserIds: new Set<string>(),
      sourceWriteUserIds: new Set<string>(),
      responseWriteUserIds: new Set<string>(),
      graphActionUserIds: new Set<string>(),
      autonomyApprovalUserIds: new Set<string>(),
      operatorUserIds: new Set<string>(),
      triageChannelIds: new Set<string>(["CSEC"]),
      riskAttestationChannelIds: new Set<string>(["CSEC"]),
      riskAttestationTimeoutMs: 10_000,
      triageChannelPolicies: new Map(),
      triageAutoReply: true,
      lifecycleNoticesEnabled: true,
      lifecycleChannelIds: new Set<string>(["CSEC"]),
      researchMaxChannels: 30,
      researchHistoryLimit: 500,
      assistantBotUserIds: new Set<string>(),
      assistantBotCooldownSeconds: 600,
      assistantBotMaxHandoffsPerThread: 2,
      assistantBotHandoffWindowSeconds: 3_600,
      assistantBotHandoffPolicies: [],
    },
    cerebro: {
      baseUrl: "https://cerebro.example.com",
      tenantId: "writer",
      requestTimeoutMs: 15_000,
      webBaseUrl: "https://cerebro.example.com",
      defaultRuntimeIds: ["writer-okta"],
      companionRuntimeId: "writer-slack-companion",
      assistantHelpMention: undefined,
      apiKeys: { read: "read-key" },
      slackUsers: new Map(),
    },
    evidenceCas: {
      defaultBucket: "cases",
      timeoutMs: 15000,
    },
    infisical: {
      enabled: true,
      baseUrl: "https://app.infisical.com",
      projectId: "project-test",
      projectSlug: "wi-cerebro-slack-companion",
      environment: "dev",
      secretPath: "/",
      identityId: "identity-test",
      awsRegion: "us-east-1",
      stsEndpoint: "https://sts.us-east-1.amazonaws.com/",
      timeoutMs: 15000,
      cacheTtlMs: 600_000,
      allowSecretValues: false,
    },
    pantherMcp: {
      enabled: false,
      allowedTools: new Set(["list_alerts", "get_alert"]),
      allowMutatingTools: false,
      timeoutMs: 15_000,
    },
    triage: {
      enabled: true,
      threadStateTableName: undefined,
      minConfidence: 0,
      maxResearchSteps: 12,
      timeoutMs: 300_000,
      maxConcurrent: 2,
      promptMaxChars: 240_000,
      promptCompactionTargetChars: 180_000,
      duplicateQuestionCooldownMs: 600_000,
      workQueueEnabled: false,
      workQueueUrl: undefined,
      workQueuePublisherIntervalMs: 1_000,
      workQueuePublisherBatchSize: 50,
      workQueueConsumerCount: 2,
      workQueueVisibilityTimeoutSeconds: 90,
      assistantRuntime: "pi",
      pi: {
        enabled: true,
        provider: "amazon-bedrock",
        model: "us.anthropic.claude-opus-4-8",
        thinkingLevel: "medium",
        executionModel: "us.anthropic.claude-opus-4-8",
        executionThinkingLevel: "medium",
      },
    },
    learning: {
      enabled: true,
      maxSearchResults: 6,
      channelLearningEnabled: true,
      channelLearningExcludedChannelIds: new Set<string>(),
      channelLearningBatchSize: 12,
      channelLearningFlushIntervalMs: 600_000,
      dailyNotesEnabled: true,
      dailyNotesTimeZone: "America/Los_Angeles",
      dailyNotesConsolidationHour: 2,
      dailyNotesConsolidationMinute: 30,
      dailyNotesNightStartHour: 0,
      dailyNotesNightEndHour: 6,
      dailyNotesCheckIntervalMs: 900_000,
      dailyNotesRetentionDays: 30,
      workingMemoryEnabled: true,
      workingMemoryCharLimit: 2200,
      teamMemoryCharLimit: 1375,
      learningDocsEnabled: true,
      learningDocsCharLimit: 12_000,
    },
    code: {
      enabled: true,
      workspaceDir: "/tmp/cerebro-code-test",
      defaultRepo: "WriterInternal/cerebro-slack-companion",
      repoPathPrefix: "",
      writeAllowedOrgs: new Set(["Writer", "WriterColab", "WriterInternal"]),
      branchPrefix: "cerebro/runtime",
      maxFileBytes: 120_000,
      maxFiles: 12,
      shellEnabled: true,
      shellTimeoutMs: 15_000,
      shellMaxOutputBytes: 24_000,
      shellMaxCommandBytes: 4_000,
    },
    ticketing: {
      jira: {
        apiTokenInfisicalSecretName: "JIRA_API_TOKEN",
        defaultIssueType: "Task",
      },
      linear: {
        apiKeyInfisicalSecretName: "LINEAR_API_KEY",
      },
      maxDescriptionChars: 6000,
      timeoutMs: 15_000,
    },
    complianceContext: {
      enabled: true,
      repo: "writer/cerebro",
      ref: "main",
      cacheTtlMs: 3_600_000,
      fetchTimeoutMs: 10_000,
      maxFileBytes: 250_000,
      maxTotalBytes: 600_000,
    },
    selfRepair: {
      enabled: true,
      createPr: true,
      threshold: 2,
      lookbackHours: 24,
      cooldownHours: 168,
    },
    improvement: {
      enabled: false,
      delegationRolloutMode: "active",
      delegationCanaryBasisPoints: 1_000,
      delegationTtlSeconds: 1_200,
      delegationPolicyVersion: "cerebro-improvement-author-v1",
      delegationToolsetVersion: "candidate-author-v1",
      delegationMaxSourceCalls: 8,
      delegationMaxRuntimeMs: 300_000,
      signalThreshold: 2,
      pollIntervalMs: 5_000,
      staleRunHours: 72,
    },
    autonomy: {
      goalsEnabled: true,
      maxListedGoals: 10,
      runnerEnabled: true,
      runnerPollIntervalMs: 60_000,
      runnerLeaseMs: 120_000,
      runnerMaxGoalsPerTick: 1,
      queueEnabled: false,
      queuePublisherIntervalMs: 1_000,
      queuePublisherBatchSize: 50,
      queueReconcileIntervalMs: 300_000,
      queueConsumerCount: 2,
      queueVisibilityTimeoutSeconds: 900,
    },
    schedules: {
      enabled: true,
      pollIntervalMs: 60_000,
      maxConcurrent: 1,
      defaultTimeZone: "America/Los_Angeles",
    },
    telemetry: {
      enabled: false,
      metricsEnabled: false,
      serviceName: "cerebro-slack-companion",
      deploymentEnvironment: "test",
    },
    coordination: {
      version: "test",
      eventDedupeEnabled: true,
      eventDedupeTtlSeconds: 86_400,
      lifecycleNoticeTtlSeconds: 3_600,
      deploymentFenceEnabled: false,
      deploymentFenceCacheMs: 5_000,
    },
    a2a: {
      enabled: true,
      instanceId: "primary-test-1",
      label: "primary",
      role: "generalist",
      capabilities: ["slack", "security", "goals", "research"],
      heartbeatIntervalMs: 5_000,
      instanceTtlSeconds: 30,
      inboxPollIntervalMs: 2_000,
      drainTimeoutMs: 4_000,
      ensembleEnabled: true,
      ensembleMaxPeers: 2,
      ensembleTimeoutMs: 45_000,
      workFleetEnabled: true,
      workFleetMaxPeers: 3,
      workFleetTimeoutMs: 60_000,
      modelMaxConcurrent: 6,
      sourceMaxConcurrent: 8,
      rateLeaseMs: 120_000,
      rateWaitMs: 15_000,
    },
  };

  return {
    ...base,
    ...overrides,
    slack: { ...base.slack, ...overrides.slack },
    cerebro: { ...base.cerebro, ...overrides.cerebro },
    evidenceCas: { ...base.evidenceCas, ...overrides.evidenceCas },
    infisical: { ...base.infisical, ...overrides.infisical },
    pantherMcp: { ...base.pantherMcp, ...overrides.pantherMcp },
    triage: {
      ...base.triage,
      ...overrides.triage,
      pi: { ...base.triage.pi, ...overrides.triage?.pi },
    },
    learning: { ...base.learning, ...overrides.learning },
    code: { ...base.code, ...overrides.code },
    ticketing: {
      ...base.ticketing,
      ...overrides.ticketing,
      jira: { ...base.ticketing.jira, ...overrides.ticketing?.jira },
      linear: { ...base.ticketing.linear, ...overrides.ticketing?.linear },
    },
    complianceContext: { ...base.complianceContext, ...overrides.complianceContext },
    selfRepair: { ...base.selfRepair, ...overrides.selfRepair },
    improvement: { ...base.improvement, ...overrides.improvement },
    autonomy: { ...base.autonomy, ...overrides.autonomy },
    schedules: { ...base.schedules, ...overrides.schedules },
    telemetry: { ...base.telemetry, ...overrides.telemetry },
    coordination: { ...base.coordination, ...overrides.coordination },
    a2a: { ...base.a2a, ...overrides.a2a },
  };
}
