apiVersion: cerebro.writer.com/v1alpha1
kind: PolicyFindingRuleTest
cases:
    - name: matching resource produces a finding
      resource:
        network_rule_set:
            default_action: Allow
      wantFinding: true
    - name: non-matching resource passes
      resource:
        network_rule_set:
            default_action: Allow-passing
      wantFinding: false
