package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const defaultOutputPath = "internal/findings/policy_rule_catalog_gen.go"

type policyFile struct {
	ID               string            `json:"id"`
	Name             string            `json:"name"`
	Description      string            `json:"description"`
	Severity         string            `json:"severity"`
	Category         string            `json:"category"`
	Resource         string            `json:"resource"`
	ResourceType     string            `json:"resource_type"`
	Conditions       []string          `json:"conditions"`
	ConditionFormat  string            `json:"condition_format"`
	Query            string            `json:"query"`
	Tags             []string          `json:"tags"`
	Remediation      string            `json:"remediation"`
	RemediationSteps []string          `json:"remediation_steps"`
	Frameworks       []policyFramework `json:"frameworks"`
	Enabled          *bool             `json:"enabled"`
	relPath          string
	domain           string
}

type policyFramework struct {
	Name     string   `json:"name"`
	Controls []string `json:"controls"`
}

func main() {
	root := flag.String("root", ".", "repository root")
	output := flag.String("output", defaultOutputPath, "generated Go output path relative to root")
	write := flag.Bool("write", false, "write the generated policy rule catalog")
	check := flag.Bool("check", false, "check that the generated policy rule catalog is fresh")
	flag.Parse()

	if !*write && !*check {
		fmt.Fprintln(os.Stderr, "policyrulegen: one of --write or --check is required")
		os.Exit(2)
	}
	content, err := generate(filepath.Clean(*root))
	if err != nil {
		fmt.Fprintf(os.Stderr, "policyrulegen: %v\n", err)
		os.Exit(1)
	}
	path := filepath.Join(filepath.Clean(*root), filepath.FromSlash(*output))
	if *write {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			fmt.Fprintf(os.Stderr, "policyrulegen: create output directory: %v\n", err)
			os.Exit(1)
		}
		if err := rejectSymlink(path); err != nil {
			fmt.Fprintf(os.Stderr, "policyrulegen: write %s: %v\n", *output, err)
			os.Exit(1)
		}
		if err := os.WriteFile(path, content, 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "policyrulegen: write %s: %v\n", *output, err)
			os.Exit(1)
		}
	}
	if *check {
		if err := rejectSymlink(path); err != nil {
			fmt.Fprintf(os.Stderr, "policyrulegen: read %s: %v\n", *output, err)
			os.Exit(1)
		}
		existing, err := os.ReadFile(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "policyrulegen: read %s: %v\n", *output, err)
			os.Exit(1)
		}
		if !bytes.Equal(bytes.TrimSpace(existing), bytes.TrimSpace(content)) {
			fmt.Fprintf(os.Stderr, "policyrulegen: %s is stale; run `make policy-rule-generate`\n", *output)
			os.Exit(1)
		}
	}
}

func rejectSymlink(path string) error {
	info, err := os.Lstat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("symlinked generated files are not allowed")
	}
	return nil
}

func generate(root string) ([]byte, error) {
	policies, err := loadPolicies(root)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	buf.WriteString("// Code generated by go run ./tools/policyrulegen --write; DO NOT EDIT.\n")
	buf.WriteString("package findings\n\n")
	buf.WriteString("import \"github.com/writer/cerebro/internal/ports\"\n\n")
	fmt.Fprintf(&buf, "var generatedPolicyRuleCatalog = []policyRuleConfig{\n")
	for _, policy := range policies {
		writePolicyRuleConfig(&buf, policy)
	}
	buf.WriteString("}\n")
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated Go: %w", err)
	}
	return formatted, nil
}

func loadPolicies(root string) ([]policyFile, error) {
	policiesRoot := filepath.Join(root, "policies")
	var policies []policyFile
	err := filepath.WalkDir(policiesRoot, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || filepath.Ext(path) != ".json" {
			return nil
		}
		rel := slashRel(root, path)
		if rel == "policies/cerebro/control-mapping.json" {
			return nil
		}
		if entry.Type()&os.ModeSymlink != 0 {
			return fmt.Errorf("%s: symlinked policy files are not allowed", rel)
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read %s: %w", rel, err)
		}
		var policy policyFile
		if err := json.Unmarshal(content, &policy); err != nil {
			return fmt.Errorf("decode %s: %w", rel, err)
		}
		policy.relPath = rel
		policy.domain = policyDomain(rel)
		policies = append(policies, policy)
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(policies, func(i, j int) bool {
		if policies[i].ID == policies[j].ID {
			return policies[i].relPath < policies[j].relPath
		}
		return policies[i].ID < policies[j].ID
	})
	return policies, nil
}

func writePolicyRuleConfig(buf *bytes.Buffer, policy policyFile) {
	evidenceMode := policyEvidenceMode(policy)
	fmt.Fprintf(buf, "{\n")
	fmt.Fprintf(buf, "Definition: RuleDefinition{\n")
	fmt.Fprintf(buf, "ID: %s,\n", quote(policy.ID))
	fmt.Fprintf(buf, "Name: %s,\n", quote(policy.Name))
	fmt.Fprintf(buf, "Description: %s,\n", quote(policy.Description))
	fmt.Fprintf(buf, "SourceID: policyRuleSourceID,\n")
	fmt.Fprintf(buf, "EventKinds: []string{policyRuleEvidenceKind, policyRuleResultEventKind},\n")
	fmt.Fprintf(buf, "OutputKind: policyRuleOutputKind,\n")
	fmt.Fprintf(buf, "Severity: %s,\n", quote(normalizeSeverity(policy.Severity)))
	fmt.Fprintf(buf, "Status: %s,\n", quote(policyStatus(policy)))
	fmt.Fprintf(buf, "Maturity: RuleMaturityCandidate,\n")
	writeStringSlice(buf, "Tags", policyTags(policy, evidenceMode))
	fmt.Fprintf(buf, "FalsePositives: []string{%s},\n", quote("Approved exception, compensating control, stale inventory, or evidence sync lag reviewed by the control owner."))
	fmt.Fprintf(buf, "Runbook: %s,\n", quote(policyRunbook(policy)))
	fmt.Fprintf(buf, "FingerprintFields: []string{%s, %s, %s, %s},\n", quote("tenant_id"), quote("policy_id"), quote("resource_urn"), quote("resource_id"))
	writeControlRefs(buf, policy.Frameworks)
	fmt.Fprintf(buf, "Lifecycle: Lifecycle{Kind: LifecycleAuditEvidence, Anchor: AnchorNone},\n")
	fmt.Fprintf(buf, "},\n")
	writeStringSlice(buf, "Conditions", trimStrings(policy.Conditions))
	fmt.Fprintf(buf, "Query: %s,\n", quote(strings.TrimSpace(policy.Query)))
	fmt.Fprintf(buf, "Resource: %s,\n", quote(firstNonEmpty(policy.Resource, policy.ResourceType)))
	fmt.Fprintf(buf, "ResourceType: %s,\n", quote(firstNonEmpty(policy.ResourceType, policy.Resource)))
	fmt.Fprintf(buf, "Category: %s,\n", quote(firstNonEmpty(policy.Category, policy.domain)))
	fmt.Fprintf(buf, "EvidenceMode: %s,\n", quote(evidenceMode))
	fmt.Fprintf(buf, "Enabled: %t,\n", policy.Enabled == nil || *policy.Enabled)
	fmt.Fprintf(buf, "},\n")
}

func writeStringSlice(buf *bytes.Buffer, field string, values []string) {
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(buf, "%s: []string{", field)
	for _, value := range values {
		fmt.Fprintf(buf, "%s,", quote(value))
	}
	fmt.Fprintf(buf, "},\n")
}

func writeControlRefs(buf *bytes.Buffer, frameworks []policyFramework) {
	seen := map[string]struct{}{}
	var refs [][2]string
	for _, framework := range frameworks {
		frameworkName := strings.TrimSpace(framework.Name)
		for _, control := range framework.Controls {
			controlID := strings.TrimSpace(control)
			if frameworkName == "" || controlID == "" {
				continue
			}
			key := frameworkName + "\x00" + controlID
			if _, ok := seen[key]; ok {
				continue
			}
			seen[key] = struct{}{}
			refs = append(refs, [2]string{frameworkName, controlID})
		}
	}
	if len(refs) == 0 {
		return
	}
	fmt.Fprintf(buf, "ControlRefs: []ports.FindingControlRef{\n")
	for _, ref := range refs {
		fmt.Fprintf(buf, "{FrameworkName: %s, ControlID: %s},\n", quote(ref[0]), quote(ref[1]))
	}
	fmt.Fprintf(buf, "},\n")
}

func policyEvidenceMode(policy policyFile) string {
	if strings.TrimSpace(policy.Query) != "" {
		return "query"
	}
	if len(trimStrings(policy.Conditions)) != 0 {
		return "cel"
	}
	return "manual"
}

func policyStatus(policy policyFile) string {
	if policy.Enabled != nil && !*policy.Enabled {
		return "disabled"
	}
	return "active"
}

func policyTags(policy policyFile, evidenceMode string) []string {
	values := append([]string{}, policy.Tags...)
	values = append(values, "policy", evidenceMode, policy.domain)
	if category := strings.TrimSpace(policy.Category); category != "" {
		values = append(values, category)
	}
	return uniqueSorted(trimStrings(values))
}

func policyRunbook(policy policyFile) string {
	if remediation := strings.TrimSpace(policy.Remediation); remediation != "" {
		return remediation
	}
	steps := trimStrings(policy.RemediationSteps)
	if len(steps) != 0 {
		return "Review and complete these remediation steps: " + strings.Join(steps, "; ") + "."
	}
	return "Review the failing policy evidence, confirm scope and owner, remediate the underlying control gap, or document an approved exception."
}

func normalizeSeverity(value string) string {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "critical":
		return "CRITICAL"
	case "high":
		return "HIGH"
	case "medium", "moderate":
		return "MEDIUM"
	case "low":
		return "LOW"
	case "info", "informational":
		return "INFO"
	default:
		return "MEDIUM"
	}
}

func trimStrings(values []string) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		if trimmed := strings.TrimSpace(value); trimmed != "" {
			out = append(out, trimmed)
		}
	}
	return out
}

func uniqueSorted(values []string) []string {
	seen := map[string]struct{}{}
	out := make([]string, 0, len(values))
	for _, value := range values {
		trimmed := strings.TrimSpace(value)
		if trimmed == "" {
			continue
		}
		key := strings.ToLower(trimmed)
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		out = append(out, trimmed)
	}
	sort.Strings(out)
	return out
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if trimmed := strings.TrimSpace(value); trimmed != "" {
			return trimmed
		}
	}
	return ""
}

func policyDomain(rel string) string {
	parts := strings.Split(filepath.ToSlash(rel), "/")
	if len(parts) >= 2 && parts[0] == "policies" {
		return strings.TrimSpace(parts[1])
	}
	return "policy"
}

func quote(value string) string {
	return strconv.Quote(strings.TrimSpace(value))
}

func slashRel(root string, path string) string {
	rel, err := filepath.Rel(root, path)
	if err != nil {
		return filepath.ToSlash(path)
	}
	return filepath.ToSlash(rel)
}
