// Command steampipeconvert is a THROWAWAY harvesting tool.
//
// It maps Steampipe plugins (github.com/turbot/steampipe-plugin-*, Apache-2.0)
// to connector-import targets and emits a tools/connectorimport manifest for the
// providers whose API also exists in the APIs.guru directory (CC0). The
// permanent importer (tools/connectorimport) then turns those specs into catalog
// connectors. This tool is intended to be deleted ("yeeted") after the one-time
// harvest; it carries no tests and is not wired into make verify.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
)

type plugin struct {
	SourceID    string
	DisplayName string
	Domain      string
	APIsGuru    string
	AuthModel   string
}

// steampipePlugins is the Steampipe-plugin -> provider mapping, intersected with
// providers that publish an OpenAPI spec in the APIs.guru directory. Plugins
// whose upstream API is not in APIs.guru (datadog, pagerduty, crowdstrike,
// cloudflare, fastly, ...) are intentionally absent and must be hand-authored.
var steampipePlugins = []plugin{
	{"github", "GitHub", "devops-ci-cd", "github.com", "bearer_token"},
	{"okta", "Okta", "identity-access-secrets", "okta.local", "api_key"},
	{"google_directory", "Google Directory", "identity-access-secrets", "googleapis.com:admin", "oauth_client_credentials"},
	{"google_search_console", "Google Search Console", "business-data-grc", "googleapis.com:searchconsole", "oauth_client_credentials"},
	{"hetzner", "Hetzner Cloud", "devops-ci-cd", "hetzner.cloud", "bearer_token"},
	{"godaddy", "GoDaddy", "devops-ci-cd", "ote-godaddy.com:domains", "api_key"},
	{"ip2locationio", "ip2location.io", "observability-soar-threat-intel", "ip2location.io", "api_key"},
	{"slack", "Slack", "collaboration-productivity", "slack.com", "bearer_token"},
	{"trello", "Trello", "collaboration-productivity", "trello.com", "api_key"},
	{"mastodon", "Mastodon", "collaboration-productivity", "mastodon.local", "bearer_token"},
	{"twitter", "Twitter", "collaboration-productivity", "twitter.com:current", "bearer_token"},
	{"openai", "OpenAI", "business-data-grc", "openai.com", "bearer_token"},
}

func main() {
	var apisGuruList, existingPath, out string
	flag.StringVar(&apisGuruList, "apisguru-list", "", "path to APIs.guru list.json used to validate keys (required)")
	flag.StringVar(&existingPath, "existing", "", "optional newline-delimited file of source_ids already in the catalog")
	flag.StringVar(&out, "out", "tmp/steampipe-manifest.yaml", "output connectorimport manifest path")
	flag.Parse()

	if strings.TrimSpace(apisGuruList) == "" {
		fail("-apisguru-list is required")
	}
	registry, err := loadKeys(apisGuruList)
	if err != nil {
		fail(err.Error())
	}
	existing := loadSet(existingPath)

	kept := make([]plugin, 0, len(steampipePlugins))
	var droppedKey, droppedExisting []string
	for _, p := range steampipePlugins {
		if _, ok := existing[p.SourceID]; ok {
			droppedExisting = append(droppedExisting, p.SourceID)
			continue
		}
		if _, ok := registry[p.APIsGuru]; !ok {
			droppedKey = append(droppedKey, p.SourceID+"("+p.APIsGuru+")")
			continue
		}
		kept = append(kept, p)
	}
	sort.Slice(kept, func(i, j int) bool { return kept[i].SourceID < kept[j].SourceID })

	if err := os.WriteFile(out, []byte(renderManifest(kept)), 0o600); err != nil {
		fail(err.Error())
	}
	fmt.Printf("steampipe-convert: kept=%d dropped_key_missing=%d dropped_existing=%d out=%s\n",
		len(kept), len(droppedKey), len(droppedExisting), out)
	if len(droppedKey) > 0 {
		fmt.Println("  key-missing:", strings.Join(droppedKey, ", "))
	}
	if len(droppedExisting) > 0 {
		fmt.Println("  already-exists:", strings.Join(droppedExisting, ", "))
	}
}

func renderManifest(plugins []plugin) string {
	var b strings.Builder
	b.WriteString("# Generated by tools/steampipeconvert (throwaway). Steampipe plugins mapped to\n")
	b.WriteString("# APIs.guru OpenAPI specs. Feed to tools/connectorimport, then delete this tool.\n")
	b.WriteString("targets:\n")
	for _, p := range plugins {
		fmt.Fprintf(&b, "  - source_id: %s\n", p.SourceID)
		fmt.Fprintf(&b, "    display_name: %q\n", p.DisplayName)
		fmt.Fprintf(&b, "    domain: %s\n", p.Domain)
		fmt.Fprintf(&b, "    categories: [saas]\n")
		fmt.Fprintf(&b, "    apis_guru: %q\n", p.APIsGuru)
		if strings.TrimSpace(p.AuthModel) != "" {
			fmt.Fprintf(&b, "    auth_model: %s\n", p.AuthModel)
		}
		fmt.Fprintf(&b, "    max_families: 6\n")
	}
	return b.String()
}

func loadKeys(path string) (map[string]struct{}, error) {
	payload, err := os.ReadFile(path) //nolint:gosec // operator-provided cache path for a throwaway tool.
	if err != nil {
		return nil, fmt.Errorf("read apisguru list: %w", err)
	}
	raw := map[string]json.RawMessage{}
	if err := json.Unmarshal(payload, &raw); err != nil {
		return nil, fmt.Errorf("parse apisguru list: %w", err)
	}
	keys := make(map[string]struct{}, len(raw))
	for key := range raw {
		keys[key] = struct{}{}
	}
	return keys, nil
}

func loadSet(path string) map[string]struct{} {
	set := map[string]struct{}{}
	if strings.TrimSpace(path) == "" {
		return set
	}
	payload, err := os.ReadFile(path) //nolint:gosec // operator-provided path for a throwaway tool.
	if err != nil {
		return set
	}
	for _, line := range strings.Split(string(payload), "\n") {
		if trimmed := strings.TrimSpace(line); trimmed != "" {
			set[trimmed] = struct{}{}
		}
	}
	return set
}

func fail(message string) {
	fmt.Fprintln(os.Stderr, "steampipeconvert:", message)
	os.Exit(1)
}
