apiVersion: cerebro.writer.com/v1alpha1
kind: PolicyFindingRuleTest
cases:
    - name: matching resource produces a finding
      resource:
        ingress: INGRESS_TRAFFIC_ALL
      wantFinding: true
    - name: non-matching resource passes
      resource:
        ingress: INGRESS_TRAFFIC_ALL-passing
      wantFinding: false
