package findingdsl

import (
	"fmt"
	"strconv"
	"strings"
)

// CodegenResult holds the generated Go code for a policy finding rule.
type CodegenResult struct {
	RuleFile    string
	TestFile    string
	Constructor string
	RuleID      string
}

// GenerateEventRule generates Go source code for a simple event-matching rule
// from a PolicyFindingRule DSL spec. This is appropriate for rules that match
// events by kind and required fields using the assertion conditions.
func GenerateEventRule(rule PolicyFindingRule) (CodegenResult, error) {
	if err := validateForCodegen(rule); err != nil {
		return CodegenResult{}, err
	}

	ruleID := rule.Metadata.ID
	pascal := toPascalCase(ruleID)
	camel := toCamelCase(ruleID)
	snake := toSnakeCase(ruleID)

	result := CodegenResult{
		RuleID:      ruleID,
		Constructor: "new" + pascal + "Rule",
	}
	result.RuleFile = renderEventRuleGo(rule, pascal, camel)
	result.TestFile = renderEventRuleTestGo(pascal, snake)
	return result, nil
}

func validateForCodegen(rule PolicyFindingRule) error {
	if rule.Metadata.ID == "" {
		return fmt.Errorf("rule metadata.id is required for codegen")
	}
	if len(rule.Spec.Input.EventKinds) == 0 && len(rule.Spec.Input.SourceKinds) == 0 {
		return fmt.Errorf("rule %s: spec.input.eventKinds or spec.input.sourceKinds is required", rule.Metadata.ID)
	}
	if rule.Spec.Severity == "" {
		return fmt.Errorf("rule %s: spec.severity is required", rule.Metadata.ID)
	}
	return nil
}

func renderEventRuleGo(rule PolicyFindingRule, pascal string, camel string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by findingdsl codegen from %s. DO NOT EDIT.\n", rule.Metadata.ID)
	fmt.Fprintf(&b, "package findings\n\n")
	fmt.Fprintf(&b, "import (\n")
	fmt.Fprintf(&b, "\t\"context\"\n")
	fmt.Fprintf(&b, "\t\"strings\"\n")
	fmt.Fprintf(&b, "\t\"time\"\n\n")
	fmt.Fprintf(&b, "\tcerebrov1 \"github.com/writer/cerebro/gen/cerebro/v1\"\n")
	fmt.Fprintf(&b, "\t\"github.com/writer/cerebro/internal/ports\"\n")
	fmt.Fprintf(&b, ")\n\n")

	// Constants.
	fmt.Fprintf(&b, "const (\n")
	fmt.Fprintf(&b, "\t%sRuleID = %s\n", camel, strconv.Quote(rule.Metadata.ID))
	fmt.Fprintf(&b, "\t%sTitle = %s\n", camel, strconv.Quote(rule.Metadata.Name))
	fmt.Fprintf(&b, "\t%sSeverity = %s\n", camel, strconv.Quote(rule.Spec.Severity))
	fmt.Fprintf(&b, "\t%sStatus = \"open\"\n", camel)
	fmt.Fprintf(&b, ")\n\n")

	// Control refs.
	controlRefs := renderControlRefsFromFrameworks(rule.Spec.Frameworks)
	fmt.Fprintf(&b, "var %sControlRefs = []ports.FindingControlRef{%s}\n\n", camel, controlRefs)

	// Event kinds.
	eventKinds := rule.Spec.Input.EventKinds
	if len(eventKinds) == 0 {
		eventKinds = rule.Spec.Input.SourceKinds
	}
	fmt.Fprintf(&b, "var %sEventKinds = %s\n\n", camel, goStringSlice(eventKinds))

	// Required fields.
	requiredFields := rule.Spec.Input.RequiredFields
	fmt.Fprintf(&b, "var %sRequiredFields = %s\n\n", camel, goStringSlice(requiredFields))

	// Fingerprint fields.
	fingerprintFields := rule.Spec.Evidence.FingerprintFields
	if len(fingerprintFields) == 0 {
		fingerprintFields = []string{"resource_urn"}
	}
	fmt.Fprintf(&b, "var %sFingerprintFields = %s\n\n", camel, goStringSlice(fingerprintFields))

	// Rule definition.
	fmt.Fprintf(&b, "var %sDefinition = RuleDefinition{\n", camel)
	fmt.Fprintf(&b, "\tID:                 %sRuleID,\n", camel)
	fmt.Fprintf(&b, "\tName:               %sTitle,\n", camel)
	fmt.Fprintf(&b, "\tDescription:        %s,\n", strconv.Quote(rule.Metadata.Description))
	fmt.Fprintf(&b, "\tEventKinds:         %sEventKinds,\n", camel)
	fmt.Fprintf(&b, "\tSeverity:           %sSeverity,\n", camel)
	fmt.Fprintf(&b, "\tStatus:             %sStatus,\n", camel)
	fmt.Fprintf(&b, "\tTags:               %s,\n", goStringSlice(rule.Metadata.Tags))
	fmt.Fprintf(&b, "\tReferences:         %s,\n", goStringSlice(rule.Metadata.References))
	fmt.Fprintf(&b, "\tRequiredAttributes: %sRequiredFields,\n", camel)
	fmt.Fprintf(&b, "\tFingerprintFields:  %sFingerprintFields,\n", camel)
	fmt.Fprintf(&b, "\tControlRefs:        %sControlRefs,\n", camel)
	fmt.Fprintf(&b, "}\n\n")

	// Kind matcher.
	fmt.Fprintf(&b, "var %sKindMatcher = eventKindMatcher(%sEventKinds...)\n\n", camel, camel)

	// Constructor.
	fmt.Fprintf(&b, "func new%sRule() Rule {\n", pascal)
	fmt.Fprintf(&b, "\treturn newEventRule(eventRuleConfig{\n")
	fmt.Fprintf(&b, "\t\tdefinition: %sDefinition,\n", camel)
	fmt.Fprintf(&b, "\t\tmatch: matches%s,\n", pascal)
	fmt.Fprintf(&b, "\t\tbuild: func(ctx context.Context, runtime *cerebrov1.SourceRuntime, event *cerebrov1.EventEnvelope) (*ports.FindingRecord, error) {\n")
	fmt.Fprintf(&b, "\t\t\treturn %sFinding(ctx, event, runtime.GetId())\n", camel)
	fmt.Fprintf(&b, "\t\t},\n")
	fmt.Fprintf(&b, "\t})\n")
	fmt.Fprintf(&b, "}\n\n")

	// Match function with assertion conditions.
	fmt.Fprintf(&b, "func matches%s(event *cerebrov1.EventEnvelope) bool {\n", pascal)
	fmt.Fprintf(&b, "\tif !%sKindMatcher(event) {\n\t\treturn false\n\t}\n", camel)
	if len(requiredFields) > 0 {
		fmt.Fprintf(&b, "\tif !hasRequiredAttributes(event, %sRequiredFields...) {\n\t\treturn false\n\t}\n", camel)
	}
	// Emit assertion conditions.
	if len(rule.Spec.Assert.All) > 0 {
		for _, assertion := range rule.Spec.Assert.All {
			emitAssertion(&b, assertion)
		}
	}
	fmt.Fprintf(&b, "\treturn true\n")
	fmt.Fprintf(&b, "}\n\n")

	// Build function.
	fmt.Fprintf(&b, "func %sFinding(_ context.Context, event *cerebrov1.EventEnvelope, runtimeID string) (*ports.FindingRecord, error) {\n", camel)
	fmt.Fprintf(&b, "\tfindingAttributes := map[string]string{\n")
	fmt.Fprintf(&b, "\t\t\"event_id\":           strings.TrimSpace(requiredAttributeValue(event, \"event_id\")),\n")
	fmt.Fprintf(&b, "\t\t\"source_runtime_id\":  strings.TrimSpace(requiredAttributeValue(event, ports.EventAttributeSourceRuntimeID)),\n")
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\tfor _, key := range %sDefinition.RequiredAttributes {\n", camel)
	fmt.Fprintf(&b, "\t\tfindingAttributes[key] = strings.TrimSpace(requiredAttributeValue(event, key))\n")
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\tfor key, value := range %sDefinition.AttributeMap() {\n", camel)
	fmt.Fprintf(&b, "\t\tfindingAttributes[\"rule_\"+key] = value\n")
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\ttrimEmptyAttributes(findingAttributes)\n\n")
	fmt.Fprintf(&b, "\tobservedAt := time.Time{}\n")
	fmt.Fprintf(&b, "\tif timestamp := event.GetOccurredAt(); timestamp != nil {\n")
	fmt.Fprintf(&b, "\t\tobservedAt = timestamp.AsTime().UTC()\n")
	fmt.Fprintf(&b, "\t}\n\n")
	fmt.Fprintf(&b, "\tfingerprintParts := []string{%sRuleID}\n", camel)
	fmt.Fprintf(&b, "\tfor _, field := range %sFingerprintFields {\n", camel)
	fmt.Fprintf(&b, "\t\tfingerprintParts = append(fingerprintParts, requiredAttributeValue(event, field))\n")
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\tfingerprint := hashFindingFingerprint(fingerprintParts...)\n\n")
	fmt.Fprintf(&b, "\treturn &ports.FindingRecord{\n")
	fmt.Fprintf(&b, "\t\tID:              fingerprint,\n")
	fmt.Fprintf(&b, "\t\tFingerprint:     fingerprint,\n")
	fmt.Fprintf(&b, "\t\tTenantID:        strings.TrimSpace(event.GetTenantId()),\n")
	fmt.Fprintf(&b, "\t\tRuntimeID:       strings.TrimSpace(runtimeID),\n")
	fmt.Fprintf(&b, "\t\tRuleID:          %sRuleID,\n", camel)
	fmt.Fprintf(&b, "\t\tTitle:           %sTitle,\n", camel)
	fmt.Fprintf(&b, "\t\tSeverity:        normalizeFindingSeverity(%sSeverity),\n", camel)
	fmt.Fprintf(&b, "\t\tStatus:          %sStatus,\n", camel)
	fmt.Fprintf(&b, "\t\tSummary:         %sTitle,\n", camel)
	fmt.Fprintf(&b, "\t\tEventIDs:        []string{strings.TrimSpace(event.GetId())},\n")
	fmt.Fprintf(&b, "\t\tControlRefs:     cloneFindingControlRefs(%sControlRefs),\n", camel)
	fmt.Fprintf(&b, "\t\tAttributes:      findingAttributes,\n")
	fmt.Fprintf(&b, "\t\tFirstObservedAt: observedAt,\n")
	fmt.Fprintf(&b, "\t\tLastObservedAt:  observedAt,\n")
	fmt.Fprintf(&b, "\t}, nil\n")
	fmt.Fprintf(&b, "}\n")

	return b.String()
}

func emitAssertion(b *strings.Builder, assertion PolicyRuleAssertion) {
	field := strings.TrimSpace(assertion.Field)
	op := strings.TrimSpace(assertion.Op)
	if field == "" || op == "" {
		return
	}
	valueStr := fmt.Sprintf("%v", assertion.Value)

	switch op {
	case "eq", "equals":
		fmt.Fprintf(b, "\tif requiredAttributeValue(event, %s) != %s {\n\t\treturn false\n\t}\n",
			strconv.Quote(field), strconv.Quote(valueStr))
	case "ne", "not_equals":
		fmt.Fprintf(b, "\tif requiredAttributeValue(event, %s) == %s {\n\t\treturn false\n\t}\n",
			strconv.Quote(field), strconv.Quote(valueStr))
	case "contains":
		fmt.Fprintf(b, "\tif !strings.Contains(requiredAttributeValue(event, %s), %s) {\n\t\treturn false\n\t}\n",
			strconv.Quote(field), strconv.Quote(valueStr))
	case "not_empty", "exists":
		fmt.Fprintf(b, "\tif strings.TrimSpace(requiredAttributeValue(event, %s)) == \"\" {\n\t\treturn false\n\t}\n",
			strconv.Quote(field))
	case "in":
		// Emit inline membership check against a comma-separated allowlist.
		fmt.Fprintf(b, "\t{\n")
		fmt.Fprintf(b, "\t\tv := requiredAttributeValue(event, %s)\n", strconv.Quote(field))
		fmt.Fprintf(b, "\t\tallowed := strings.Split(%s, \",\")\n", strconv.Quote(valueStr))
		fmt.Fprintf(b, "\t\tfound := false\n")
		fmt.Fprintf(b, "\t\tfor _, a := range allowed {\n")
		fmt.Fprintf(b, "\t\t\tif strings.TrimSpace(a) == v { found = true; break }\n")
		fmt.Fprintf(b, "\t\t}\n")
		fmt.Fprintf(b, "\t\tif !found { return false }\n")
		fmt.Fprintf(b, "\t}\n")
	}
}

func renderEventRuleTestGo(pascal string, snake string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by findingdsl codegen. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "package findings\n\n")
	fmt.Fprintf(&b, "import \"testing\"\n\n")
	fmt.Fprintf(&b, "func Test%sFixture(t *testing.T) {\n", pascal)
	fmt.Fprintf(&b, "\tassertRuleFixture(t, new%sRule(), %s)\n", pascal, strconv.Quote("testdata/rules/"+snake+".json"))
	fmt.Fprintf(&b, "}\n")
	return b.String()
}

func renderControlRefsFromFrameworks(frameworks []PolicyFramework) string {
	if len(frameworks) == 0 {
		return ""
	}
	var parts []string
	for _, fw := range frameworks {
		for _, control := range fw.Controls {
			parts = append(parts, fmt.Sprintf("{Framework: %s, Control: %s}",
				strconv.Quote(fw.Name), strconv.Quote(control)))
		}
	}
	return strings.Join(parts, ", ")
}

func goStringSlice(items []string) string {
	if len(items) == 0 {
		return "nil"
	}
	parts := make([]string, len(items))
	for i, item := range items {
		parts[i] = strconv.Quote(item)
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}

func toPascalCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || r == '.'
	})
	var result strings.Builder
	for _, part := range parts {
		if len(part) > 0 {
			result.WriteString(strings.ToUpper(part[:1]) + part[1:])
		}
	}
	return result.String()
}

func toCamelCase(s string) string {
	pascal := toPascalCase(s)
	if len(pascal) == 0 {
		return ""
	}
	return strings.ToLower(pascal[:1]) + pascal[1:]
}

func toSnakeCase(s string) string {
	s = strings.ReplaceAll(s, "-", "_")
	s = strings.ReplaceAll(s, ".", "_")
	return strings.ToLower(s)
}
