package transport

import (
	"time"

	cerebrov1 "github.com/writer/cerebro/gen/cerebro/v1"
	"github.com/writer/cerebro/internal/knowledge"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// Metadata is the decoded protobuf metadata supplied to a knowledge write.
type Metadata map[string]any

// DecisionRequest maps the public protobuf request to the durable knowledge boundary.
func DecisionRequest(request *cerebrov1.WriteDecisionRequest, metadata Metadata) knowledge.DecisionWriteRequest {
	return knowledge.DecisionWriteRequest{
		ID: request.GetId(), DecisionType: request.GetDecisionType(), Status: request.GetStatus(),
		MadeBy: request.GetMadeBy(), Rationale: request.GetRationale(), TargetIDs: request.GetTargetIds(),
		EvidenceIDs: request.GetEvidenceIds(), ActionIDs: request.GetActionIds(), SourceSystem: request.GetSourceSystem(),
		SourceEventID: request.GetSourceEventId(), ObservedAt: timestampValue(request.GetObservedAt()),
		ValidFrom: timestampValue(request.GetValidFrom()), ValidTo: timestampValue(request.GetValidTo()),
		Confidence: request.GetConfidence(), Metadata: metadata,
	}
}

// ActionRequest maps the public protobuf request to the durable knowledge boundary.
func ActionRequest(request *cerebrov1.WriteActionRequest, metadata Metadata) knowledge.ActionWriteRequest {
	return knowledge.ActionWriteRequest{
		ID: request.GetId(), RecommendationID: request.GetRecommendationId(), InsightType: request.GetInsightType(),
		Title: request.GetTitle(), Summary: request.GetSummary(), DecisionID: request.GetDecisionId(),
		TargetIDs: request.GetTargetIds(), SourceSystem: request.GetSourceSystem(), SourceEventID: request.GetSourceEventId(),
		ObservedAt: timestampValue(request.GetObservedAt()), ValidFrom: timestampValue(request.GetValidFrom()),
		ValidTo: timestampValue(request.GetValidTo()), Confidence: request.GetConfidence(),
		AutoGenerated: request.GetAutoGenerated(), Metadata: metadata,
	}
}

// OutcomeRequest maps the public protobuf request to the durable knowledge boundary.
func OutcomeRequest(request *cerebrov1.WriteOutcomeRequest, metadata Metadata) knowledge.OutcomeWriteRequest {
	return knowledge.OutcomeWriteRequest{
		ID: request.GetId(), DecisionID: request.GetDecisionId(), OutcomeType: request.GetOutcomeType(),
		Verdict: request.GetVerdict(), ImpactScore: request.GetImpactScore(), TargetIDs: request.GetTargetIds(),
		SourceSystem: request.GetSourceSystem(), SourceEventID: request.GetSourceEventId(),
		ObservedAt: timestampValue(request.GetObservedAt()), ValidFrom: timestampValue(request.GetValidFrom()),
		ValidTo: timestampValue(request.GetValidTo()), Confidence: request.GetConfidence(), Metadata: metadata,
	}
}

func timestampValue(value *timestamppb.Timestamp) time.Time {
	if value == nil || (value.GetSeconds() == 0 && value.GetNanos() == 0) {
		return time.Time{}
	}
	return value.AsTime().UTC()
}
