[package]
name = "cerebro-graphagent-staticvalidator"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cerebro-wasm-guest.workspace = true
regex.workspace = true

[lints]
workspace = true
