package workflowprojection

import (
	"context"
	"testing"

	"github.com/writer/cerebro/internal/ports"
	"github.com/writer/cerebro/internal/workflowevents"
)

type projectionRecorder struct {
	entities map[string]*ports.ProjectedEntity
	links    map[string]*ports.ProjectedLink
}

func (r *projectionRecorder) Ping(context.Context) error { return nil }

func (r *projectionRecorder) UpsertProjectedEntity(_ context.Context, entity *ports.ProjectedEntity) error {
	if r.entities == nil {
		r.entities = make(map[string]*ports.ProjectedEntity)
	}
	r.entities[entity.URN] = cloneProjectedEntity(entity)
	return nil
}

func (r *projectionRecorder) UpsertProjectedLink(_ context.Context, link *ports.ProjectedLink) error {
	if r.links == nil {
		r.links = make(map[string]*ports.ProjectedLink)
	}
	r.links[link.FromURN+"|"+link.Relation+"|"+link.ToURN] = cloneProjectedLink(link)
	return nil
}

func TestProjectKnowledgeWorkflowEvents(t *testing.T) {
	graph := &projectionRecorder{}
	service := New(graph)
	targetURN := "urn:cerebro:writer:okta_resource:policyrule:pol-1"
	decisionEvent, err := workflowevents.NewDecisionRecordedEvent(workflowevents.DecisionRecorded{
		TenantID:     "writer",
		DecisionID:   "urn:cerebro:writer:decision:decision-1",
		DecisionType: "finding-triage",
		Status:       "approved",
		Rationale:    "accepted risk pending remediation",
		TargetIDs:    []string{targetURN},
		EvidenceIDs:  []string{"finding-evidence-1"},
		SourceSystem: "findings",
		ObservedAt:   "2026-04-27T12:00:00Z",
		ValidFrom:    "2026-04-27T12:00:00Z",
	})
	if err != nil {
		t.Fatalf("NewDecisionRecordedEvent() error = %v", err)
	}
	decisionResult, err := service.Project(context.Background(), decisionEvent)
	if err != nil {
		t.Fatalf("Project(decision) error = %v", err)
	}
	if decisionResult.EntitiesProjected != 2 {
		t.Fatalf("decision entities projected = %d, want 2", decisionResult.EntitiesProjected)
	}
	if _, ok := graph.links["urn:cerebro:writer:decision:decision-1|targets|"+targetURN]; !ok {
		t.Fatal("decision target link missing")
	}
	if _, ok := graph.links["urn:cerebro:writer:decision:decision-1|based_on|urn:cerebro:writer:evidence:finding-evidence-1"]; !ok {
		t.Fatal("decision evidence link missing")
	}

	actionEvent, err := workflowevents.NewActionRecordedEvent(workflowevents.ActionRecorded{
		TenantID:         "writer",
		ActionID:         "urn:cerebro:writer:action:action-1",
		ActionType:       "remediation",
		Status:           "recorded",
		RecommendationID: "recommendation-1",
		Title:            "Open remediation ticket",
		DecisionID:       "urn:cerebro:writer:decision:decision-1",
		TargetIDs:        []string{targetURN},
		SourceSystem:     "platform.recommendations",
		ObservedAt:       "2026-04-27T13:00:00Z",
		ValidFrom:        "2026-04-27T13:00:00Z",
		AutoGenerated:    true,
	})
	if err != nil {
		t.Fatalf("NewActionRecordedEvent() error = %v", err)
	}
	if _, err := service.Project(context.Background(), actionEvent); err != nil {
		t.Fatalf("Project(action) error = %v", err)
	}
	if _, ok := graph.links["urn:cerebro:writer:action:action-1|targets|"+targetURN]; !ok {
		t.Fatal("action target link missing")
	}
	if _, ok := graph.links["urn:cerebro:writer:decision:decision-1|executed_by|urn:cerebro:writer:action:action-1"]; !ok {
		t.Fatal("decision action link missing")
	}

	outcomeEvent, err := workflowevents.NewOutcomeRecordedEvent(workflowevents.OutcomeRecorded{
		TenantID:     "writer",
		OutcomeID:    "urn:cerebro:writer:outcome:outcome-1",
		DecisionID:   "urn:cerebro:writer:decision:decision-1",
		OutcomeType:  "finding-resolution",
		Verdict:      "resolved",
		TargetIDs:    []string{targetURN},
		SourceSystem: "findings",
		ObservedAt:   "2026-04-27T14:00:00Z",
		ValidFrom:    "2026-04-27T14:00:00Z",
	})
	if err != nil {
		t.Fatalf("NewOutcomeRecordedEvent() error = %v", err)
	}
	if _, err := service.Project(context.Background(), outcomeEvent); err != nil {
		t.Fatalf("Project(outcome) error = %v", err)
	}
	if _, ok := graph.links["urn:cerebro:writer:outcome:outcome-1|evaluates|urn:cerebro:writer:decision:decision-1"]; !ok {
		t.Fatal("outcome evaluates link missing")
	}

	if _, err := service.Project(context.Background(), outcomeEvent); err != nil {
		t.Fatalf("Project(outcome replay) error = %v", err)
	}
	if got := len(graph.entities); got != 4 {
		t.Fatalf("len(entities) after replay = %d, want 4", got)
	}
}

func TestProjectFindingWorkflowEvents(t *testing.T) {
	graph := &projectionRecorder{}
	service := New(graph)
	finding := workflowevents.FindingSnapshot{
		TenantID:           "writer",
		SourceSystem:       "writer-okta-audit",
		FindingID:          "finding-1",
		Title:              "Okta Policy Rule Lifecycle Tampering",
		RuleID:             "identity-okta-policy-rule-lifecycle-tampering",
		Severity:           "high",
		Status:             "open",
		RuntimeID:          "writer-okta-audit",
		PrimaryResourceURN: "urn:cerebro:writer:okta_resource:policyrule:pol-1",
		ResourceURNs:       []string{"urn:cerebro:writer:okta_resource:policyrule:pol-1"},
	}
	recordedEvent, err := workflowevents.NewFindingRecordedEvent(workflowevents.FindingRecorded{
		Finding:    finding,
		RecordedAt: "2026-04-27T11:59:00Z",
	})
	if err != nil {
		t.Fatalf("NewFindingRecordedEvent() error = %v", err)
	}
	if _, err := service.Project(context.Background(), recordedEvent); err != nil {
		t.Fatalf("Project(recorded) error = %v", err)
	}
	if _, ok := graph.entities["urn:cerebro:writer:finding:finding-1"]; !ok {
		t.Fatal("finding anchor missing after recorded event")
	}
	if _, ok := graph.links["urn:cerebro:writer:okta_resource:policyrule:pol-1|has_finding|urn:cerebro:writer:finding:finding-1"]; !ok {
		t.Fatal("resource finding link missing after recorded event")
	}
	noteEvent, err := workflowevents.NewFindingNoteAddedEvent(workflowevents.FindingNoteAdded{
		Finding:   finding,
		NoteID:    "note-1",
		Body:      "Escalate to identity engineering.",
		CreatedAt: "2026-04-27T12:00:00Z",
	})
	if err != nil {
		t.Fatalf("NewFindingNoteAddedEvent() error = %v", err)
	}
	if _, err := service.Project(context.Background(), noteEvent); err != nil {
		t.Fatalf("Project(note) error = %v", err)
	}
	annotationURN := "urn:cerebro:writer:annotation:finding-note:finding-1:note-1"
	if _, ok := graph.links["urn:cerebro:writer:finding:finding-1|annotated_with|"+annotationURN]; !ok {
		t.Fatal("finding annotation link missing")
	}

	ticketEvent, err := workflowevents.NewFindingTicketLinkedEvent(workflowevents.FindingTicketLinked{
		Finding:    finding,
		URL:        "https://jira.writer.com/browse/ENG-123",
		Name:       "ENG-123",
		ExternalID: "ENG-123",
		LinkedAt:   "2026-04-27T12:30:00Z",
	})
	if err != nil {
		t.Fatalf("NewFindingTicketLinkedEvent() error = %v", err)
	}
	if _, err := service.Project(context.Background(), ticketEvent); err != nil {
		t.Fatalf("Project(ticket) error = %v", err)
	}
	if _, ok := graph.entities["urn:cerebro:writer:finding:finding-1"]; !ok {
		t.Fatal("finding anchor missing")
	}
	if _, ok := graph.links["urn:cerebro:writer:okta_resource:policyrule:pol-1|has_finding|urn:cerebro:writer:finding:finding-1"]; !ok {
		t.Fatal("resource finding link missing")
	}
}

func cloneProjectedEntity(entity *ports.ProjectedEntity) *ports.ProjectedEntity {
	attributes := make(map[string]string, len(entity.Attributes))
	for key, value := range entity.Attributes {
		attributes[key] = value
	}
	return &ports.ProjectedEntity{
		URN:        entity.URN,
		TenantID:   entity.TenantID,
		SourceID:   entity.SourceID,
		EntityType: entity.EntityType,
		Label:      entity.Label,
		Attributes: attributes,
	}
}

func cloneProjectedLink(link *ports.ProjectedLink) *ports.ProjectedLink {
	attributes := make(map[string]string, len(link.Attributes))
	for key, value := range link.Attributes {
		attributes[key] = value
	}
	return &ports.ProjectedLink{
		TenantID:   link.TenantID,
		SourceID:   link.SourceID,
		FromURN:    link.FromURN,
		ToURN:      link.ToURN,
		Relation:   link.Relation,
		Attributes: attributes,
	}
}
