package bootstrap

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/writer/cerebro/internal/ports"
	"github.com/writer/cerebro/internal/runtimeresponse"
	"github.com/writer/cerebro/internal/workflowevents"
)

type runtimeCapabilitiesResponse struct {
	Capabilities []runtimeresponse.Capability `json:"capabilities"`
}

type runtimeBlocklistResponse struct {
	Entry *ports.RuntimeBlocklistEntry `json:"entry"`
}

type runtimeBlocklistListResponse struct {
	Entries []*ports.RuntimeBlocklistEntry `json:"entries"`
}

func (a *App) runtimeResponseService() *runtimeresponse.Service {
	return runtimeresponse.New(runtimeBlocklistStore(a.deps.StateStore))
}

func (a *App) handleRuntimeResponseCapabilities(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, runtimeCapabilitiesResponse{Capabilities: a.runtimeResponseService().Capabilities()})
}

func (a *App) handleExecuteRuntimeResponse(w http.ResponseWriter, r *http.Request) {
	var request runtimeresponse.ExecuteRequest
	if err := json.NewDecoder(http.MaxBytesReader(w, r.Body, maxProtoJSONBodyBytes)).Decode(&request); err != nil {
		writeRuntimeResponseError(w, fmt.Errorf("%w: decode runtime response request: %w", runtimeresponse.ErrInvalidRequest, err))
		return
	}
	tenantID, err := effectiveTenantFilter(r.Context(), request.TenantID)
	if err != nil {
		writeRuntimeResponseError(w, err)
		return
	}
	request.TenantID = tenantID
	request.Action = strings.TrimSpace(request.Action)
	request.TrustedScope = hasRuntimeResponseTrustedScope(r.Context())
	entry, err := a.runtimeResponseService().Execute(r.Context(), request)
	if err != nil {
		writeRuntimeResponseError(w, err)
		return
	}
	if err := a.recordRuntimeResponseWorkflow(r.Context(), request, entry); err != nil {
		writeRuntimeResponseError(w, err)
		return
	}
	writeJSON(w, http.StatusAccepted, runtimeBlocklistResponse{Entry: entry})
}

func (a *App) recordRuntimeResponseWorkflow(ctx context.Context, request runtimeresponse.ExecuteRequest, entry *ports.RuntimeBlocklistEntry) error {
	if a == nil || a.deps.AppendLog == nil || entry == nil {
		return nil
	}
	observedAt := entry.CreatedAt
	if observedAt.IsZero() {
		observedAt = time.Now().UTC()
	}
	action := strings.TrimSpace(request.Action)
	actionID := fmt.Sprintf("urn:cerebro:%s:runtime_response_action:%s", entry.TenantID, entry.ID)
	targetID := fmt.Sprintf("runtime_response:%s:%s", entry.Type, entry.Value)
	event, err := workflowevents.NewActionRecordedEvent(workflowevents.ActionRecorded{
		TenantID:      entry.TenantID,
		ActionID:      actionID,
		ActionType:    action,
		Status:        "completed",
		Title:         "Runtime response " + action,
		Summary:       entry.Reason,
		TargetIDs:     []string{targetID},
		SourceSystem:  "runtime_response",
		SourceEventID: entry.ID,
		ObservedAt:    observedAt.Format(time.RFC3339Nano),
		ValidFrom:     observedAt.Format(time.RFC3339Nano),
		AutoGenerated: true,
		Metadata: map[string]any{
			"blocklist_entry_id": entry.ID,
			"source_job_id":      strings.TrimSpace(entry.SourceJobID),
			"target_type":        entry.Type,
		},
	})
	if err != nil {
		return err
	}
	return a.deps.AppendLog.Append(ctx, event)
}

func (a *App) handleListRuntimeBlocklist(w http.ResponseWriter, r *http.Request) {
	limit, err := uint32QueryParam(r, "limit")
	if err != nil {
		writeRuntimeResponseError(w, err)
		return
	}
	filter := ports.RuntimeBlocklistFilter{
		Type:           strings.TrimSpace(r.URL.Query().Get("type")),
		IncludeRevoked: false,
		Limit:          limit,
	}
	if includeRevoked := strings.TrimSpace(r.URL.Query().Get("include_revoked")); includeRevoked != "" {
		parsed, err := boolQueryParam(r, "include_revoked")
		if err != nil {
			writeRuntimeResponseError(w, err)
			return
		}
		filter.IncludeRevoked = parsed
	}
	tenantID, err := effectiveTenantFilter(r.Context(), r.URL.Query().Get("tenant_id"))
	if err != nil {
		writeRuntimeResponseError(w, err)
		return
	}
	filter.TenantID = tenantID
	entries, err := a.runtimeResponseService().List(r.Context(), filter)
	if err != nil {
		writeRuntimeResponseError(w, err)
		return
	}
	writeJSON(w, http.StatusOK, runtimeBlocklistListResponse{Entries: entries})
}

func (a *App) handleRevokeRuntimeBlocklistEntry(w http.ResponseWriter, r *http.Request) {
	tenantID, err := effectiveTenantFilter(r.Context(), r.URL.Query().Get("tenant_id"))
	if err != nil {
		writeRuntimeResponseError(w, err)
		return
	}
	entry, err := a.runtimeResponseService().Revoke(r.Context(), tenantID, r.PathValue("entryID"))
	if err != nil {
		writeRuntimeResponseError(w, err)
		return
	}
	writeJSON(w, http.StatusOK, runtimeBlocklistResponse{Entry: entry})
}

func writeRuntimeResponseError(w http.ResponseWriter, err error) {
	status := http.StatusInternalServerError
	switch {
	case errors.Is(err, runtimeresponse.ErrInvalidRequest), errors.Is(err, errInvalidHTTPRequest):
		status = http.StatusBadRequest
	case errors.Is(err, runtimeresponse.ErrUnsupportedAction):
		status = http.StatusUnprocessableEntity
	case errors.Is(err, runtimeresponse.ErrRuntimeUnavailable):
		status = http.StatusServiceUnavailable
	case errors.Is(err, ports.ErrRuntimeBlocklistEntryNotFound):
		status = http.StatusNotFound
	case errors.Is(err, errTenantForbidden):
		status = http.StatusForbidden
	}
	writeJSON(w, status, map[string]string{"error": err.Error()})
}
