apiVersion: cerebro.writer.com/v1alpha1
kind: PolicyFindingRuleTest
cases:
    - name: matching resource produces a finding
      resource:
        auth_level: anonymous
      wantFinding: true
    - name: non-matching resource passes
      resource:
        auth_level: anonymous-passing
      wantFinding: false
