package sourceprojection

import (
	"testing"

	cerebrov1 "github.com/writer/cerebro/gen/cerebro/v1"
)

func TestRuntimeDepthPromotedSourcesProjectMissingKinds(t *testing.T) {
	tests := []struct {
		name  string
		event *cerebrov1.EventEnvelope
	}{
		{name: "auth0_connections", event: &cerebrov1.EventEnvelope{Id: "evt-auth0-connections", TenantId: "tenant", SourceId: "auth0", Kind: "auth0.connections", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "auth0_guardian_factors", event: &cerebrov1.EventEnvelope{Id: "evt-auth0-guardian-factors", TenantId: "tenant", SourceId: "auth0", Kind: "auth0.guardian_factors", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "auth0_organizations", event: &cerebrov1.EventEnvelope{Id: "evt-auth0-organizations", TenantId: "tenant", SourceId: "auth0", Kind: "auth0.organizations", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "auth0_user_roles", event: &cerebrov1.EventEnvelope{Id: "evt-auth0-user-roles", TenantId: "tenant", SourceId: "auth0", Kind: "auth0.user_roles", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "akeneo_asset_families_attribute", event: &cerebrov1.EventEnvelope{Id: "evt-akeneo-asset-families-attribute", TenantId: "tenant", SourceId: "akeneo", Kind: "akeneo.asset_families_attribute", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "akeneo_asset_family", event: &cerebrov1.EventEnvelope{Id: "evt-akeneo-asset-family", TenantId: "tenant", SourceId: "akeneo", Kind: "akeneo.asset_family", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "akeneo_attributes_option", event: &cerebrov1.EventEnvelope{Id: "evt-akeneo-attributes-option", TenantId: "tenant", SourceId: "akeneo", Kind: "akeneo.attributes_option", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "akeneo_draft", event: &cerebrov1.EventEnvelope{Id: "evt-akeneo-draft", TenantId: "tenant", SourceId: "akeneo", Kind: "akeneo.draft", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "akeneo_option", event: &cerebrov1.EventEnvelope{Id: "evt-akeneo-option", TenantId: "tenant", SourceId: "akeneo", Kind: "akeneo.option", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "akeneo_products_draft", event: &cerebrov1.EventEnvelope{Id: "evt-akeneo-products-draft", TenantId: "tenant", SourceId: "akeneo", Kind: "akeneo.products_draft", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "akeneo_products_uuid_draft", event: &cerebrov1.EventEnvelope{Id: "evt-akeneo-products-uuid-draft", TenantId: "tenant", SourceId: "akeneo", Kind: "akeneo.products_uuid_draft", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "akeneo_reference_entities_attribute", event: &cerebrov1.EventEnvelope{Id: "evt-akeneo-reference-entities-attribute", TenantId: "tenant", SourceId: "akeneo", Kind: "akeneo.reference_entities_attribute", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "akeneo_v1_attribute", event: &cerebrov1.EventEnvelope{Id: "evt-akeneo-v1-attribute", TenantId: "tenant", SourceId: "akeneo", Kind: "akeneo.v1_attribute", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "onelogin_app_rules", event: &cerebrov1.EventEnvelope{Id: "evt-onelogin-app-rules", TenantId: "tenant", SourceId: "onelogin", Kind: "onelogin.app_rules", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "onelogin_app_users", event: &cerebrov1.EventEnvelope{Id: "evt-onelogin-app-users", TenantId: "tenant", SourceId: "onelogin", Kind: "onelogin.app_users", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "onelogin_apps", event: &cerebrov1.EventEnvelope{Id: "evt-onelogin-apps", TenantId: "tenant", SourceId: "onelogin", Kind: "onelogin.apps", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "onelogin_delegated_privileges", event: &cerebrov1.EventEnvelope{Id: "evt-onelogin-delegated-privileges", TenantId: "tenant", SourceId: "onelogin", Kind: "onelogin.delegated_privileges", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "onelogin_mappings", event: &cerebrov1.EventEnvelope{Id: "evt-onelogin-mappings", TenantId: "tenant", SourceId: "onelogin", Kind: "onelogin.mappings", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "onelogin_mfa_devices", event: &cerebrov1.EventEnvelope{Id: "evt-onelogin-mfa-devices", TenantId: "tenant", SourceId: "onelogin", Kind: "onelogin.mfa_devices", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "onelogin_privilege_roles", event: &cerebrov1.EventEnvelope{Id: "evt-onelogin-privilege-roles", TenantId: "tenant", SourceId: "onelogin", Kind: "onelogin.privilege_roles", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "onelogin_privilege_users", event: &cerebrov1.EventEnvelope{Id: "evt-onelogin-privilege-users", TenantId: "tenant", SourceId: "onelogin", Kind: "onelogin.privilege_users", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "onelogin_privileges", event: &cerebrov1.EventEnvelope{Id: "evt-onelogin-privileges", TenantId: "tenant", SourceId: "onelogin", Kind: "onelogin.privileges", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "onelogin_role_admins", event: &cerebrov1.EventEnvelope{Id: "evt-onelogin-role-admins", TenantId: "tenant", SourceId: "onelogin", Kind: "onelogin.role_admins", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "onelogin_role_apps", event: &cerebrov1.EventEnvelope{Id: "evt-onelogin-role-apps", TenantId: "tenant", SourceId: "onelogin", Kind: "onelogin.role_apps", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "onelogin_role_users", event: &cerebrov1.EventEnvelope{Id: "evt-onelogin-role-users", TenantId: "tenant", SourceId: "onelogin", Kind: "onelogin.role_users", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "onelogin_roles", event: &cerebrov1.EventEnvelope{Id: "evt-onelogin-roles", TenantId: "tenant", SourceId: "onelogin", Kind: "onelogin.roles", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "onelogin_user_apps", event: &cerebrov1.EventEnvelope{Id: "evt-onelogin-user-apps", TenantId: "tenant", SourceId: "onelogin", Kind: "onelogin.user_apps", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "onelogin_user_privileges", event: &cerebrov1.EventEnvelope{Id: "evt-onelogin-user-privileges", TenantId: "tenant", SourceId: "onelogin", Kind: "onelogin.user_privileges", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_access_profile_entitlements", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-access-profile-entitlements", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.access_profile_entitlements", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_access_profiles", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-access-profiles", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.access_profiles", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_access_request_status", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-access-request-status", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.access_request_status", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_account_activities", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-account-activities", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.account_activities", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_account_entitlements", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-account-entitlements", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.account_entitlements", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_accounts", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-accounts", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.accounts", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_campaigns", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-campaigns", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.campaigns", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_certification_access_review_items", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-certification-access-review-items", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.certification_access_review_items", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_certifications", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-certifications", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.certifications", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_entitlements", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-entitlements", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.entitlements", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_identities", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-identities", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.identities", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_identity_entitlements", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-identity-entitlements", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.identity_entitlements", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_identity_profiles", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-identity-profiles", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.identity_profiles", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_identity_role_assignments", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-identity-role-assignments", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.identity_role_assignments", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_lifecycle_states", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-lifecycle-states", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.lifecycle_states", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_personal_access_tokens", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-personal-access-tokens", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.personal_access_tokens", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_role_assigned_identities", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-role-assigned-identities", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.role_assigned_identities", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_role_dimensions", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-role-dimensions", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.role_dimensions", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_role_entitlements", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-role-entitlements", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.role_entitlements", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_roles", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-roles", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.roles", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_segments", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-segments", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.segments", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_source_health", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-source-health", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.source_health", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_source_provisioning_policies", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-source-provisioning-policies", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.source_provisioning_policies", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_source_schedules", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-source-schedules", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.source_schedules", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_source_schemas", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-source-schemas", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.source_schemas", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_sources", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-sources", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.sources", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_workgroup_members", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-workgroup-members", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.workgroup_members", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "sailpoint_identitynow_workgroups", event: &cerebrov1.EventEnvelope{Id: "evt-sailpoint-workgroups", TenantId: "tenant", SourceId: "sailpoint_identitynow", Kind: "sailpoint_identitynow.workgroups", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "duo_administrator", event: &cerebrov1.EventEnvelope{Id: "evt-duo-administrator", TenantId: "tenant", SourceId: "duo", Kind: "duo.administrator", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "duo_application", event: &cerebrov1.EventEnvelope{Id: "evt-duo-application", TenantId: "tenant", SourceId: "duo", Kind: "duo.application", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "duo_audit_event", event: &cerebrov1.EventEnvelope{Id: "evt-duo-audit-event", TenantId: "tenant", SourceId: "duo", Kind: "duo.audit_event", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "duo_authentication_log", event: &cerebrov1.EventEnvelope{Id: "evt-duo-authentication-log", TenantId: "tenant", SourceId: "duo", Kind: "duo.authentication_log", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "duo_endpoint", event: &cerebrov1.EventEnvelope{Id: "evt-duo-endpoint", TenantId: "tenant", SourceId: "duo", Kind: "duo.endpoint", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "duo_group", event: &cerebrov1.EventEnvelope{Id: "evt-duo-group", TenantId: "tenant", SourceId: "duo", Kind: "duo.group", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "duo_phone", event: &cerebrov1.EventEnvelope{Id: "evt-duo-phone", TenantId: "tenant", SourceId: "duo", Kind: "duo.phone", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "duo_role", event: &cerebrov1.EventEnvelope{Id: "evt-duo-role", TenantId: "tenant", SourceId: "duo", Kind: "duo.role", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "duo_token", event: &cerebrov1.EventEnvelope{Id: "evt-duo-token", TenantId: "tenant", SourceId: "duo", Kind: "duo.token", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "duo_user", event: &cerebrov1.EventEnvelope{Id: "evt-duo-user", TenantId: "tenant", SourceId: "duo", Kind: "duo.user", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "duo_web_authn_credential", event: &cerebrov1.EventEnvelope{Id: "evt-duo-web-authn-credential", TenantId: "tenant", SourceId: "duo", Kind: "duo.web_authn_credential", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "slack_access_log", event: &cerebrov1.EventEnvelope{Id: "evt-slack-access-log", TenantId: "tenant", SourceId: "slack", Kind: "slack.access_log", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "apideck_credit_note", event: &cerebrov1.EventEnvelope{Id: "evt-apideck-credit-note", TenantId: "tenant", SourceId: "apideck", Kind: "apideck.credit_note", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "apideck_customer", event: &cerebrov1.EventEnvelope{Id: "evt-apideck-customer", TenantId: "tenant", SourceId: "apideck", Kind: "apideck.customer", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "avaza_bill", event: &cerebrov1.EventEnvelope{Id: "evt-avaza-bill", TenantId: "tenant", SourceId: "avaza", Kind: "avaza.bill", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "avaza_billpayment", event: &cerebrov1.EventEnvelope{Id: "evt-avaza-billpayment", TenantId: "tenant", SourceId: "avaza", Kind: "avaza.billpayment", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "avaza_company", event: &cerebrov1.EventEnvelope{Id: "evt-avaza-company", TenantId: "tenant", SourceId: "avaza", Kind: "avaza.company", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "avaza_contact", event: &cerebrov1.EventEnvelope{Id: "evt-avaza-contact", TenantId: "tenant", SourceId: "avaza", Kind: "avaza.contact", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "avaza_creditnote", event: &cerebrov1.EventEnvelope{Id: "evt-avaza-creditnote", TenantId: "tenant", SourceId: "avaza", Kind: "avaza.creditnote", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "avaza_currency", event: &cerebrov1.EventEnvelope{Id: "evt-avaza-currency", TenantId: "tenant", SourceId: "avaza", Kind: "avaza.currency", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "avaza_estimate", event: &cerebrov1.EventEnvelope{Id: "evt-avaza-estimate", TenantId: "tenant", SourceId: "avaza", Kind: "avaza.estimate", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "avaza_expense", event: &cerebrov1.EventEnvelope{Id: "evt-avaza-expense", TenantId: "tenant", SourceId: "avaza", Kind: "avaza.expense", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "avaza_userprofile", event: &cerebrov1.EventEnvelope{Id: "evt-avaza-userprofile", TenantId: "tenant", SourceId: "avaza", Kind: "avaza.userprofile", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "avaza_webhook", event: &cerebrov1.EventEnvelope{Id: "evt-avaza-webhook", TenantId: "tenant", SourceId: "avaza", Kind: "avaza.webhook", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "bigredcloud_bankaccount", event: &cerebrov1.EventEnvelope{Id: "evt-bigredcloud-bankaccount", TenantId: "tenant", SourceId: "bigredcloud", Kind: "bigredcloud.bankaccount", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "billingo_document_block", event: &cerebrov1.EventEnvelope{Id: "evt-billingo-document-block", TenantId: "tenant", SourceId: "billingo", Kind: "billingo.document_block", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "billingo_partner", event: &cerebrov1.EventEnvelope{Id: "evt-billingo-partner", TenantId: "tenant", SourceId: "billingo", Kind: "billingo.partner", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "callfire_call", event: &cerebrov1.EventEnvelope{Id: "evt-callfire-call", TenantId: "tenant", SourceId: "callfire", Kind: "callfire.call", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "fulfillment_com_return", event: &cerebrov1.EventEnvelope{Id: "evt-fulfillment-com-return", TenantId: "tenant", SourceId: "fulfillment_com", Kind: "fulfillment_com.return", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "fulfillment_com_track", event: &cerebrov1.EventEnvelope{Id: "evt-fulfillment-com-track", TenantId: "tenant", SourceId: "fulfillment_com", Kind: "fulfillment_com.track", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "hetzner_firewall", event: &cerebrov1.EventEnvelope{Id: "evt-hetzner-firewall", TenantId: "tenant", SourceId: "hetzner", Kind: "hetzner.firewall", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "hetzner_ssh_key", event: &cerebrov1.EventEnvelope{Id: "evt-hetzner-ssh-key", TenantId: "tenant", SourceId: "hetzner", Kind: "hetzner.ssh_key", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "journy_io_segments_account", event: &cerebrov1.EventEnvelope{Id: "evt-journy-io-segments-account", TenantId: "tenant", SourceId: "journy_io", Kind: "journy_io.segments_account", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "journy_io_segments_user", event: &cerebrov1.EventEnvelope{Id: "evt-journy-io-segments-user", TenantId: "tenant", SourceId: "journy_io", Kind: "journy_io.segments_user", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "journy_io_user", event: &cerebrov1.EventEnvelope{Id: "evt-journy-io-user", TenantId: "tenant", SourceId: "journy_io", Kind: "journy_io.user", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "jumpseller_checkout_custom_fields_json", event: &cerebrov1.EventEnvelope{Id: "evt-jumpseller-checkout-custom-fields-json", TenantId: "tenant", SourceId: "jumpseller", Kind: "jumpseller.checkout_custom_fields_json", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "jumpseller_countries_json", event: &cerebrov1.EventEnvelope{Id: "evt-jumpseller-countries-json", TenantId: "tenant", SourceId: "jumpseller", Kind: "jumpseller.countries_json", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "jumpseller_custom_fields_json", event: &cerebrov1.EventEnvelope{Id: "evt-jumpseller-custom-fields-json", TenantId: "tenant", SourceId: "jumpseller", Kind: "jumpseller.custom_fields_json", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "jumpseller_customer_categories_json", event: &cerebrov1.EventEnvelope{Id: "evt-jumpseller-customer-categories-json", TenantId: "tenant", SourceId: "jumpseller", Kind: "jumpseller.customer_categories_json", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "jumpseller_customers_json", event: &cerebrov1.EventEnvelope{Id: "evt-jumpseller-customers-json", TenantId: "tenant", SourceId: "jumpseller", Kind: "jumpseller.customers_json", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "jumpseller_fulfillments_json", event: &cerebrov1.EventEnvelope{Id: "evt-jumpseller-fulfillments-json", TenantId: "tenant", SourceId: "jumpseller", Kind: "jumpseller.fulfillments_json", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "jumpseller_jsapps_json", event: &cerebrov1.EventEnvelope{Id: "evt-jumpseller-jsapps-json", TenantId: "tenant", SourceId: "jumpseller", Kind: "jumpseller.jsapps_json", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "jumpseller_orders_json", event: &cerebrov1.EventEnvelope{Id: "evt-jumpseller-orders-json", TenantId: "tenant", SourceId: "jumpseller", Kind: "jumpseller.orders_json", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "jumpseller_pages_json", event: &cerebrov1.EventEnvelope{Id: "evt-jumpseller-pages-json", TenantId: "tenant", SourceId: "jumpseller", Kind: "jumpseller.pages_json", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "jumpseller_payment_methods_json", event: &cerebrov1.EventEnvelope{Id: "evt-jumpseller-payment-methods-json", TenantId: "tenant", SourceId: "jumpseller", Kind: "jumpseller.payment_methods_json", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "jumpseller_products_json", event: &cerebrov1.EventEnvelope{Id: "evt-jumpseller-products-json", TenantId: "tenant", SourceId: "jumpseller", Kind: "jumpseller.products_json", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "netlicensing_licensee", event: &cerebrov1.EventEnvelope{Id: "evt-netlicensing-licensee", TenantId: "tenant", SourceId: "netlicensing", Kind: "netlicensing.licensee", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "netlicensing_licensetemplate", event: &cerebrov1.EventEnvelope{Id: "evt-netlicensing-licensetemplate", TenantId: "tenant", SourceId: "netlicensing", Kind: "netlicensing.licensetemplate", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "neutrinoapi_bin_lookup", event: &cerebrov1.EventEnvelope{Id: "evt-neutrinoapi-bin-lookup", TenantId: "tenant", SourceId: "neutrinoapi", Kind: "neutrinoapi.bin_lookup", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "neutrinoapi_geocode_address", event: &cerebrov1.EventEnvelope{Id: "evt-neutrinoapi-geocode-address", TenantId: "tenant", SourceId: "neutrinoapi", Kind: "neutrinoapi.geocode_address", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "neutrinoapi_host_reputation", event: &cerebrov1.EventEnvelope{Id: "evt-neutrinoapi-host-reputation", TenantId: "tenant", SourceId: "neutrinoapi", Kind: "neutrinoapi.host_reputation", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "openfintech_country", event: &cerebrov1.EventEnvelope{Id: "evt-openfintech-country", TenantId: "tenant", SourceId: "openfintech", Kind: "openfintech.country", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "openfintech_currency", event: &cerebrov1.EventEnvelope{Id: "evt-openfintech-currency", TenantId: "tenant", SourceId: "openfintech", Kind: "openfintech.currency", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "stream_io_api_query_banned_user", event: &cerebrov1.EventEnvelope{Id: "evt-stream-io-api-query-banned-user", TenantId: "tenant", SourceId: "stream_io_api", Kind: "stream_io_api.query_banned_user", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "truora_check", event: &cerebrov1.EventEnvelope{Id: "evt-truora-check", TenantId: "tenant", SourceId: "truora", Kind: "truora.check", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "truora_config", event: &cerebrov1.EventEnvelope{Id: "evt-truora-config", TenantId: "tenant", SourceId: "truora", Kind: "truora.config", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "truora_report", event: &cerebrov1.EventEnvelope{Id: "evt-truora-report", TenantId: "tenant", SourceId: "truora", Kind: "truora.report", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "winsms_optout", event: &cerebrov1.EventEnvelope{Id: "evt-winsms-optout", TenantId: "tenant", SourceId: "winsms", Kind: "winsms.optout", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "winsms_sms_incoming", event: &cerebrov1.EventEnvelope{Id: "evt-winsms-sms-incoming", TenantId: "tenant", SourceId: "winsms", Kind: "winsms.sms_incoming", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "xtrf_eu_all", event: &cerebrov1.EventEnvelope{Id: "evt-xtrf-eu-all", TenantId: "tenant", SourceId: "xtrf_eu", Kind: "xtrf_eu.all", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "xtrf_eu_customer", event: &cerebrov1.EventEnvelope{Id: "evt-xtrf-eu-customer", TenantId: "tenant", SourceId: "xtrf_eu", Kind: "xtrf_eu.customer", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "xtrf_eu_customers_id", event: &cerebrov1.EventEnvelope{Id: "evt-xtrf-eu-customers-id", TenantId: "tenant", SourceId: "xtrf_eu", Kind: "xtrf_eu.customers_id", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "xtrf_eu_id", event: &cerebrov1.EventEnvelope{Id: "evt-xtrf-eu-id", TenantId: "tenant", SourceId: "xtrf_eu", Kind: "xtrf_eu.id", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "xtrf_eu_id_2", event: &cerebrov1.EventEnvelope{Id: "evt-xtrf-eu-id-2", TenantId: "tenant", SourceId: "xtrf_eu", Kind: "xtrf_eu.id_2", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "xtrf_eu_invoices_id", event: &cerebrov1.EventEnvelope{Id: "evt-xtrf-eu-invoices-id", TenantId: "tenant", SourceId: "xtrf_eu", Kind: "xtrf_eu.invoices_id", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "xtrf_eu_persons_id", event: &cerebrov1.EventEnvelope{Id: "evt-xtrf-eu-persons-id", TenantId: "tenant", SourceId: "xtrf_eu", Kind: "xtrf_eu.persons_id", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "xtrf_eu_projects_id", event: &cerebrov1.EventEnvelope{Id: "evt-xtrf-eu-projects-id", TenantId: "tenant", SourceId: "xtrf_eu", Kind: "xtrf_eu.projects_id", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "xtrf_eu_providers_id", event: &cerebrov1.EventEnvelope{Id: "evt-xtrf-eu-providers-id", TenantId: "tenant", SourceId: "xtrf_eu", Kind: "xtrf_eu.providers_id", Attributes: runtimeDepthPromotionAttributes()}},
		{name: "xtrf_eu_quotes_id", event: &cerebrov1.EventEnvelope{Id: "evt-xtrf-eu-quotes-id", TenantId: "tenant", SourceId: "xtrf_eu", Kind: "xtrf_eu.quotes_id", Attributes: runtimeDepthPromotionAttributes()}},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			entities, links, err := BuiltinRegistry().Project(test.event)
			if err != nil {
				t.Fatalf("Project(%q) error = %v", test.event.GetKind(), err)
			}
			if len(entities) == 0 && len(links) == 0 {
				t.Fatalf("Project(%q) returned no graph records", test.event.GetKind())
			}
		})
	}
}

func runtimeDepthPromotionAttributes() map[string]string {
	return map[string]string{ // #nosec G101 -- static test fixture identifiers, not credentials.
		"account_id":         "account-1",
		"admin_id":           "admin-1",
		"actor_email":        "user@example.test",
		"actor_id":           "user-1",
		"api_id":             "api-1",
		"api_identifier":     "https://api.example.test",
		"api_name":           "Example API",
		"app_id":             "app-1",
		"app_name":           "Example App",
		"application_id":     "app-1",
		"authentication_id":  "auth-1",
		"audience":           "https://api.example.test",
		"certification_id":   "certification-1",
		"certification_name": "Access Review",
		"client_id":          "client-1",
		"connection_id":      "connection-1",
		"connection_name":    "Database",
		"credential_id":      "credential-1",
		"display_name":       "User One",
		"email":              "user@example.test",
		"entitlement_id":     "entitlement-1",
		"entitlement_name":   "Payroll Admin",
		"entitlement_value":  "payroll-admin",
		"endpoint_id":        "endpoint-1",
		"event_type":         "user.login",
		"external_id":        "resource-1",
		"factor_id":          "factor-1",
		"group_email":        "group@example.test",
		"group_id":           "group-1",
		"group_name":         "Group One",
		"id":                 "resource-1",
		"identity_id":        "identity-1",
		"identity_name":      "User One",
		"integration_key":    "DIAPP1",
		"member_email":       "user@example.test",
		"member_name":        "User One",
		"member_user_id":     "user-1",
		"name":               "Resource One",
		"organization_id":    "org-1",
		"organization_name":  "Organization One",
		"phone_id":           "phone-1",
		"policy_id":          "policy-1",
		"policy_name":        "Policy One",
		"policy_status":      "enabled",
		"policy_type":        "access",
		"resource_id":        "resource-1",
		"resource_name":      "Resource One",
		"resource_type":      "application",
		"review_item_id":     "review-item-1",
		"role_id":            "role-1",
		"role_name":          "Role One",
		"scope":              "read:reports",
		"source_id":          "source-1",
		"source_name":        "Source One",
		"subject_email":      "user@example.test",
		"subject_id":         "user-1",
		"subject_name":       "User One",
		"subject_type":       "user",
		"token_id":           "token-1",
		"type":               "application",
		"user_id":            "user-1",
	}
}
