// Code generated by tools/agentlifecyclegen from the AgentServiceLifecycleContract JSON Schema. DO NOT EDIT.

package agentplatform

// AgentServiceBindingV1 AgentServiceBindingV1 is part of the AgentServiceLifecycle contract.
type AgentServiceBindingV1 struct {
	BindingID              string                     `json:"binding_id"`
	CreatedAt              string                     `json:"created_at"`
	InstallationGeneration int64                      `json:"installation_generation"`
	RetentionPolicyRef     string                     `json:"retention_policy_ref"`
	RouteGeneration        int64                      `json:"route_generation"`
	SchemaVersion          string                     `json:"schema_version"`
	ServiceID              string                     `json:"service_id"`
	State                  InstallationLifecycleState `json:"state"`
	TenantID               string                     `json:"tenant_id"`
	UpdatedAt              string                     `json:"updated_at"`
}

// AgentServiceLifecycleContract The public contract an agent service implements independently of transport and deployment topology.
type AgentServiceLifecycleContract struct {
	Compatibility      SchemaCompatibility           `json:"compatibility"`
	ContractVersion    string                        `json:"contract_version"`
	DeploymentStates   []DeploymentStateDefinition   `json:"deployment_states"`
	HealthSurfaces     []HealthSurface               `json:"health_surfaces"`
	InstallationStates []InstallationStateDefinition `json:"installation_states"`
	Invariants         []LifecycleInvariant          `json:"invariants"`
	LegacyAdapters     []LegacyAdapter               `json:"legacy_adapters"`
	Ports              []PortContract                `json:"ports"`
	Records            []RecordContract              `json:"records"`
	RunStates          []RunStateDefinition          `json:"run_states"`
	SchemaVersion      string                        `json:"schema_version"`
	ServiceStates      []ServiceStateDefinition      `json:"service_states"`
	Transitions        []StateTransition             `json:"transitions"`
}

// CapabilityCompatibilityDecision CapabilityCompatibilityDecision is part of the AgentServiceLifecycle contract.
type CapabilityCompatibilityDecision string

const (
	CapabilityCompatibilityDecisionSupported    CapabilityCompatibilityDecision = "supported"
	CapabilityCompatibilityDecisionDegraded     CapabilityCompatibilityDecision = "degraded"
	CapabilityCompatibilityDecisionBlocked      CapabilityCompatibilityDecision = "blocked"
	CapabilityCompatibilityDecisionIncompatible CapabilityCompatibilityDecision = "incompatible"
)

// CapabilityManifestV1 CapabilityManifestV1 is part of the AgentServiceLifecycle contract.
type CapabilityManifestV1 struct {
	Capabilities     []CapabilityRequirement `json:"capabilities"`
	ContractVersions []string                `json:"contract_versions"`
	Digest           string                  `json:"digest"`
	Generation       int64                   `json:"generation"`
	ProducedAt       string                  `json:"produced_at"`
	SchemaVersion    string                  `json:"schema_version"`
	ServiceID        string                  `json:"service_id"`
}

// CapabilityRequirement CapabilityRequirement is part of the AgentServiceLifecycle contract.
type CapabilityRequirement struct {
	CapabilityID string                     `json:"capability_id"`
	Level        CapabilityRequirementLevel `json:"level"`
	Version      string                     `json:"version"`
}

// CapabilityRequirementLevel CapabilityRequirementLevel is part of the AgentServiceLifecycle contract.
type CapabilityRequirementLevel string

const (
	CapabilityRequirementLevelRequired CapabilityRequirementLevel = "required"
	CapabilityRequirementLevelOptional CapabilityRequirementLevel = "optional"
)

// CheckpointV1 CheckpointV1 is part of the AgentServiceLifecycle contract.
type CheckpointV1 struct {
	CheckpointID     string   `json:"checkpoint_id"`
	CompletedStepIDs []string `json:"completed_step_ids"`
	CreatedAt        string   `json:"created_at"`
	EffectReceiptIDs []string `json:"effect_receipt_ids"`
	Generation       int64    `json:"generation"`
	PayloadDigest    string   `json:"payload_digest"`
	PayloadRef       string   `json:"payload_ref"`
	ResumeCursor     string   `json:"resume_cursor"`
	RunID            string   `json:"run_id"`
	RunRevision      int64    `json:"run_revision"`
	SchemaVersion    string   `json:"schema_version"`
	Sequence         int64    `json:"sequence"`
	WaitingOnRef     *string  `json:"waiting_on_ref,omitempty"`
}

// DeliveryPartV1 DeliveryPartV1 is part of the AgentServiceLifecycle contract.
type DeliveryPartV1 struct {
	DeliveredAt        *string `json:"delivered_at,omitempty"`
	DestinationReceipt *string `json:"destination_receipt,omitempty"`
	IdempotencyKey     string  `json:"idempotency_key"`
	PartID             string  `json:"part_id"`
	PayloadDigest      string  `json:"payload_digest"`
	PayloadRef         string  `json:"payload_ref"`
	Sequence           int64   `json:"sequence"`
	State              string  `json:"state"`
}

// DeliveryReceiptV1 DeliveryReceiptV1 is part of the AgentServiceLifecycle contract.
type DeliveryReceiptV1 struct {
	CreatedAt      string           `json:"created_at"`
	DeliveryID     string           `json:"delivery_id"`
	DestinationRef string           `json:"destination_ref"`
	Parts          []DeliveryPartV1 `json:"parts"`
	RunID          string           `json:"run_id"`
	SchemaVersion  string           `json:"schema_version"`
	State          string           `json:"state"`
	UpdatedAt      string           `json:"updated_at"`
}

// DeploymentGenerationState DeploymentGenerationState is part of the AgentServiceLifecycle contract.
type DeploymentGenerationState string

const (
	DeploymentGenerationStateProposed     DeploymentGenerationState = "proposed"
	DeploymentGenerationStateProvisioning DeploymentGenerationState = "provisioning"
	DeploymentGenerationStateValidating   DeploymentGenerationState = "validating"
	DeploymentGenerationStateActive       DeploymentGenerationState = "active"
	DeploymentGenerationStateFailed       DeploymentGenerationState = "failed"
	DeploymentGenerationStateRolledBack   DeploymentGenerationState = "rolled_back"
	DeploymentGenerationStateSuperseded   DeploymentGenerationState = "superseded"
	DeploymentGenerationStateRetired      DeploymentGenerationState = "retired"
)

// DeploymentGenerationV1 DeploymentGenerationV1 is part of the AgentServiceLifecycle contract.
type DeploymentGenerationV1 struct {
	CapabilityManifestDigest string                    `json:"capability_manifest_digest"`
	ContractVersion          string                    `json:"contract_version"`
	CreatedAt                string                    `json:"created_at"`
	FencingToken             int64                     `json:"fencing_token"`
	Generation               int64                     `json:"generation"`
	ReleaseVersion           string                    `json:"release_version"`
	SchemaVersion            string                    `json:"schema_version"`
	ServiceID                string                    `json:"service_id"`
	State                    DeploymentGenerationState `json:"state"`
	UpdatedAt                string                    `json:"updated_at"`
}

// DeploymentStateDefinition DeploymentStateDefinition is part of the AgentServiceLifecycle contract.
type DeploymentStateDefinition struct {
	MayOwnLeases bool                      `json:"may_own_leases"`
	MayOwnRoutes bool                      `json:"may_own_routes"`
	Meaning      string                    `json:"meaning"`
	State        DeploymentGenerationState `json:"state"`
}

// EffectExecutionState EffectExecutionState is part of the AgentServiceLifecycle contract.
type EffectExecutionState string

const (
	EffectExecutionStatePlanned   EffectExecutionState = "planned"
	EffectExecutionStateExecuting EffectExecutionState = "executing"
	EffectExecutionStateSucceeded EffectExecutionState = "succeeded"
	EffectExecutionStateFailed    EffectExecutionState = "failed"
	EffectExecutionStateUnknown   EffectExecutionState = "unknown"
)

// EffectReceiptV1 EffectReceiptV1 is part of the AgentServiceLifecycle contract.
type EffectReceiptV1 struct {
	ApprovalRef            *string              `json:"approval_ref,omitempty"`
	ApprovalRequired       bool                 `json:"approval_required"`
	EffectID               string               `json:"effect_id"`
	FencingToken           int64                `json:"fencing_token"`
	Generation             int64                `json:"generation"`
	IdempotencyKey         string               `json:"idempotency_key"`
	LeaseToken             string               `json:"lease_token"`
	RecordedAt             string               `json:"recorded_at"`
	RequestDigest          string               `json:"request_digest"`
	ResultDigest           *string              `json:"result_digest,omitempty"`
	ResultRef              *string              `json:"result_ref,omitempty"`
	RollbackPlanRef        *string              `json:"rollback_plan_ref,omitempty"`
	RunID                  string               `json:"run_id"`
	SchemaVersion          string               `json:"schema_version"`
	State                  EffectExecutionState `json:"state"`
	StepID                 string               `json:"step_id"`
	TargetRef              string               `json:"target_ref"`
	VerificationReceiptRef *string              `json:"verification_receipt_ref,omitempty"`
	VerificationState      string               `json:"verification_state"`
}

// HealthSurface HealthSurface is part of the AgentServiceLifecycle contract.
type HealthSurface struct {
	Path             string `json:"path"`
	Responsibility   string `json:"responsibility"`
	SuccessCondition string `json:"success_condition"`
}

// InstallationLifecycleState InstallationLifecycleState is part of the AgentServiceLifecycle contract.
type InstallationLifecycleState string

const (
	InstallationLifecycleStateAuthorizing InstallationLifecycleState = "authorizing"
	InstallationLifecycleStateBinding     InstallationLifecycleState = "binding"
	InstallationLifecycleStateVerifying   InstallationLifecycleState = "verifying"
	InstallationLifecycleStateActive      InstallationLifecycleState = "active"
	InstallationLifecycleStateSuspended   InstallationLifecycleState = "suspended"
	InstallationLifecycleStateRevoked     InstallationLifecycleState = "revoked"
	InstallationLifecycleStateRetired     InstallationLifecycleState = "retired"
)

// InstallationStateDefinition InstallationStateDefinition is part of the AgentServiceLifecycle contract.
type InstallationStateDefinition struct {
	AdmissionAllowed bool                       `json:"admission_allowed"`
	Meaning          string                     `json:"meaning"`
	State            InstallationLifecycleState `json:"state"`
}

// LegacyAdapter LegacyAdapter is part of the AgentServiceLifecycle contract.
type LegacyAdapter struct {
	ID                  string `json:"id"`
	RetirementCondition string `json:"retirement_condition"`
	TargetSchema        string `json:"target_schema"`
	WriteAuthority      bool   `json:"write_authority"`
}

// LifecycleInvariant LifecycleInvariant is part of the AgentServiceLifecycle contract.
type LifecycleInvariant struct {
	ID        string `json:"id"`
	Statement string `json:"statement"`
}

// MigrationReceiptV1 MigrationReceiptV1 is part of the AgentServiceLifecycle contract.
type MigrationReceiptV1 struct {
	BindingID            string `json:"binding_id"`
	CheckpointCount      int64  `json:"checkpoint_count"`
	CreatedAt            string `json:"created_at"`
	MigrationID          string `json:"migration_id"`
	PendingDeliveryCount int64  `json:"pending_delivery_count"`
	RollbackGeneration   int64  `json:"rollback_generation"`
	RouteGeneration      int64  `json:"route_generation"`
	SchemaVersion        string `json:"schema_version"`
	SourceGeneration     int64  `json:"source_generation"`
	State                string `json:"state"`
	TargetGeneration     int64  `json:"target_generation"`
	UpdatedAt            string `json:"updated_at"`
}

// PortContract PortContract is part of the AgentServiceLifecycle contract.
type PortContract struct {
	ID                           string   `json:"id"`
	ProductionDurabilityRequired bool     `json:"production_durability_required"`
	Purpose                      string   `json:"purpose"`
	RequiredOperations           []string `json:"required_operations"`
}

// PresenceSnapshotV1 PresenceSnapshotV1 is part of the AgentServiceLifecycle contract.
type PresenceSnapshotV1 struct {
	ActiveGeneration int64                           `json:"active_generation"`
	BindingID        string                          `json:"binding_id"`
	Compatibility    CapabilityCompatibilityDecision `json:"compatibility"`
	ExpiresAt        string                          `json:"expires_at"`
	ObservedAt       string                          `json:"observed_at"`
	ReasonCode       string                          `json:"reason_code"`
	RouteGeneration  int64                           `json:"route_generation"`
	SchemaVersion    string                          `json:"schema_version"`
	ServiceState     ServiceAvailabilityState        `json:"service_state"`
}

// RecordContract RecordContract is part of the AgentServiceLifecycle contract.
type RecordContract struct {
	FencingFields  []string `json:"fencing_fields"`
	IdentityFields []string `json:"identity_fields"`
	Kind           string   `json:"kind"`
	SchemaRef      string   `json:"schema_ref"`
	SchemaVersion  string   `json:"schema_version"`
}

// ReleaseReceiptV2 ReleaseReceiptV2 is part of the AgentServiceLifecycle contract.
type ReleaseReceiptV2 struct {
	ActiveLeaseCount        int64                           `json:"active_lease_count"`
	Compatibility           CapabilityCompatibilityDecision `json:"compatibility"`
	CreatedAt               string                          `json:"created_at"`
	DrainedRunCount         int64                           `json:"drained_run_count"`
	Generation              int64                           `json:"generation"`
	OrphanedRunCount        int64                           `json:"orphaned_run_count"`
	PendingDeliveryCount    int64                           `json:"pending_delivery_count"`
	RecoverableRunCount     int64                           `json:"recoverable_run_count"`
	ReleaseID               string                          `json:"release_id"`
	ResumedRunCount         int64                           `json:"resumed_run_count"`
	SchemaVersion           string                          `json:"schema_version"`
	ServiceID               string                          `json:"service_id"`
	State                   DeploymentGenerationState       `json:"state"`
	StuckDeliveryCount      int64                           `json:"stuck_delivery_count"`
	UpdatedAt               string                          `json:"updated_at"`
	VerificationReceiptRefs []string                        `json:"verification_receipt_refs"`
}

// RunKind RunKind is part of the AgentServiceLifecycle contract.
type RunKind string

const (
	RunKindInteractive     RunKind = "interactive"
	RunKindScheduled       RunKind = "scheduled"
	RunKindAutonomy        RunKind = "autonomy"
	RunKindTriage          RunKind = "triage"
	RunKindRiskAttestation RunKind = "risk_attestation"
	RunKindReconciliation  RunKind = "reconciliation"
)

// RunLifecycleState RunLifecycleState is part of the AgentServiceLifecycle contract.
type RunLifecycleState string

const (
	RunLifecycleStateReceived   RunLifecycleState = "received"
	RunLifecycleStateAdmitted   RunLifecycleState = "admitted"
	RunLifecycleStateRejected   RunLifecycleState = "rejected"
	RunLifecycleStateQueued     RunLifecycleState = "queued"
	RunLifecycleStateLeased     RunLifecycleState = "leased"
	RunLifecycleStateRunning    RunLifecycleState = "running"
	RunLifecycleStateWaiting    RunLifecycleState = "waiting"
	RunLifecycleStatePaused     RunLifecycleState = "paused"
	RunLifecycleStateDelivering RunLifecycleState = "delivering"
	RunLifecycleStateCompleted  RunLifecycleState = "completed"
	RunLifecycleStateCancelled  RunLifecycleState = "cancelled"
	RunLifecycleStateExpired    RunLifecycleState = "expired"
	RunLifecycleStateBlocked    RunLifecycleState = "blocked"
)

// RunReceiptV1 RunReceiptV1 is part of the AgentServiceLifecycle contract.
type RunReceiptV1 struct {
	AdmittedAt           string                  `json:"admitted_at"`
	BindingID            string                  `json:"binding_id"`
	IdempotencyKey       string                  `json:"idempotency_key"`
	InputDigest          string                  `json:"input_digest"`
	ReceiptID            string                  `json:"receipt_id"`
	ReceivedAt           string                  `json:"received_at"`
	RequiredCapabilities []CapabilityRequirement `json:"required_capabilities"`
	RetentionPolicyRef   string                  `json:"retention_policy_ref"`
	Revision             int64                   `json:"revision"`
	RunID                string                  `json:"run_id"`
	RunKind              RunKind                 `json:"run_kind"`
	SchemaVersion        string                  `json:"schema_version"`
	State                string                  `json:"state"`
	SubjectRef           string                  `json:"subject_ref"`
	TenantID             string                  `json:"tenant_id"`
	UpdatedAt            string                  `json:"updated_at"`
}

// RunStateDefinition RunStateDefinition is part of the AgentServiceLifecycle contract.
type RunStateDefinition struct {
	Meaning  string            `json:"meaning"`
	State    RunLifecycleState `json:"state"`
	Terminal bool              `json:"terminal"`
}

// ScheduleMisfirePolicy ScheduleMisfirePolicy is part of the AgentServiceLifecycle contract.
type ScheduleMisfirePolicy string

const (
	ScheduleMisfirePolicyCoalesceOnce  ScheduleMisfirePolicy = "coalesce_once"
	ScheduleMisfirePolicySkip          ScheduleMisfirePolicy = "skip"
	ScheduleMisfirePolicyRunAllBounded ScheduleMisfirePolicy = "run_all_bounded"
)

// ScheduledOccurrenceState ScheduledOccurrenceState is part of the AgentServiceLifecycle contract.
type ScheduledOccurrenceState string

const (
	ScheduledOccurrenceStateAdmitted  ScheduledOccurrenceState = "admitted"
	ScheduledOccurrenceStateQueued    ScheduledOccurrenceState = "queued"
	ScheduledOccurrenceStateLeased    ScheduledOccurrenceState = "leased"
	ScheduledOccurrenceStateRunning   ScheduledOccurrenceState = "running"
	ScheduledOccurrenceStateCompleted ScheduledOccurrenceState = "completed"
	ScheduledOccurrenceStateFailed    ScheduledOccurrenceState = "failed"
	ScheduledOccurrenceStateCancelled ScheduledOccurrenceState = "cancelled"
	ScheduledOccurrenceStateSkipped   ScheduledOccurrenceState = "skipped"
)

// ScheduledOccurrenceV1 ScheduledOccurrenceV1 is part of the AgentServiceLifecycle contract.
type ScheduledOccurrenceV1 struct {
	CreatedAt        string                   `json:"created_at"`
	DueAt            string                   `json:"due_at"`
	FencingToken     *int64                   `json:"fencing_token,omitempty"`
	Generation       int64                    `json:"generation"`
	HeartbeatAt      *string                  `json:"heartbeat_at,omitempty"`
	IdempotencyKey   string                   `json:"idempotency_key"`
	LeaseExpiresAt   *string                  `json:"lease_expires_at,omitempty"`
	LeaseToken       *string                  `json:"lease_token,omitempty"`
	MisfirePolicy    ScheduleMisfirePolicy    `json:"misfire_policy"`
	OccurrenceID     string                   `json:"occurrence_id"`
	OwnerID          *string                  `json:"owner_id,omitempty"`
	RunID            string                   `json:"run_id"`
	ScheduleID       string                   `json:"schedule_id"`
	ScheduleRevision int64                    `json:"schedule_revision"`
	SchemaVersion    string                   `json:"schema_version"`
	State            ScheduledOccurrenceState `json:"state"`
	UpdatedAt        string                   `json:"updated_at"`
}

// SchemaCompatibility SchemaCompatibility is part of the AgentServiceLifecycle contract.
type SchemaCompatibility struct {
	CapabilityDecisions []CapabilityCompatibilityDecision `json:"capability_decisions"`
	CurrentVersion      string                            `json:"current_version"`
	ReadVersions        []string                          `json:"read_versions"`
	RollingUpgradeRule  string                            `json:"rolling_upgrade_rule"`
	WriteVersions       []string                          `json:"write_versions"`
}

// ServiceAvailabilityState ServiceAvailabilityState is part of the AgentServiceLifecycle contract.
type ServiceAvailabilityState string

const (
	ServiceAvailabilityStateBooting    ServiceAvailabilityState = "booting"
	ServiceAvailabilityStateWarming    ServiceAvailabilityState = "warming"
	ServiceAvailabilityStateReady      ServiceAvailabilityState = "ready"
	ServiceAvailabilityStateDegraded   ServiceAvailabilityState = "degraded"
	ServiceAvailabilityStateDraining   ServiceAvailabilityState = "draining"
	ServiceAvailabilityStateOffline    ServiceAvailabilityState = "offline"
	ServiceAvailabilityStateRecovering ServiceAvailabilityState = "recovering"
	ServiceAvailabilityStateStopped    ServiceAvailabilityState = "stopped"
)

// ServiceStateDefinition ServiceStateDefinition is part of the AgentServiceLifecycle contract.
type ServiceStateDefinition struct {
	Admission    string                   `json:"admission"`
	ExistingWork string                   `json:"existing_work"`
	Meaning      string                   `json:"meaning"`
	NewLeases    bool                     `json:"new_leases"`
	State        ServiceAvailabilityState `json:"state"`
}

// StateTransition StateTransition is part of the AgentServiceLifecycle contract.
type StateTransition struct {
	Condition string `json:"condition"`
	From      string `json:"from"`
	Machine   string `json:"machine"`
	To        string `json:"to"`
}

// WorkLeaseV1 WorkLeaseV1 is part of the AgentServiceLifecycle contract.
type WorkLeaseV1 struct {
	FencingToken   int64  `json:"fencing_token"`
	Generation     int64  `json:"generation"`
	HeartbeatAt    string `json:"heartbeat_at"`
	LeaseExpiresAt string `json:"lease_expires_at"`
	LeaseToken     string `json:"lease_token"`
	OwnerID        string `json:"owner_id"`
	RunID          string `json:"run_id"`
	SchemaVersion  string `json:"schema_version"`
}
