// Code generated by tools/rustcarve. DO NOT EDIT.

use super::{
    MIGRATION_IR_DIGEST_SHA256, MIGRATION_IR_VERSION, RUST_IMPLEMENTATION_REVISION,
    RUSTCARVE_TOOL_REVISION, SUBJECT_ID, contracts,
};

#[test]
fn generated_contract_is_closed_and_revision_bound() {
    assert_eq!(RUSTCARVE_TOOL_REVISION, "cerebro.rustcarve/v2");
    assert_eq!(MIGRATION_IR_VERSION, "graph-query/v1");
    assert_eq!(
        MIGRATION_IR_DIGEST_SHA256,
        "sha256:4100c589fefac5a5a3c66a2c9b0c3aed6328693b0858553978d282d8efd6e261"
    );
    assert_eq!(RUST_IMPLEMENTATION_REVISION, "unimplemented");
    assert_eq!(SUBJECT_ID, "complianceimpact.projected_graph");
    assert_eq!(contracts::FIXTURE_CORPUS.len(), 1);
    assert_eq!(contracts::PORT_TRACES.len(), 1);
    assert_eq!(contracts::REQUIRED_RECEIPT_MODES.len(), 2);
    assert_eq!(contracts::ACCEPTED_RECEIPTS.len(), 0);
    assert_eq!(contracts::DELETION_ELIGIBLE, false);
    assert_eq!(contracts::DELETION_REASON_CODES.len(), 2);
    assert_eq!(contracts::AUTHORITY_GATES.len(), 0);
    // This scaffold is intentionally not deletion-eligible without exact differential receipts.
}
