// Code generated by tools/rustcarve. DO NOT EDIT.

use super::{
    MIGRATION_IR_DIGEST_SHA256, MIGRATION_IR_VERSION, RUST_IMPLEMENTATION_REVISION,
    RUSTCARVE_TOOL_REVISION, SUBJECT_ID, contracts,
};

#[test]
fn generated_contract_is_closed_and_revision_bound() {
    assert_eq!(RUSTCARVE_TOOL_REVISION, "cerebro.rustcarve/v1");
    assert_eq!(MIGRATION_IR_VERSION, "graph-query/v1");
    assert_eq!(
        MIGRATION_IR_DIGEST_SHA256,
        "sha256:e19d490e27fc09e80f5f902dff3d8fef92ad027cb544a0df20bbf6c205f2d088"
    );
    assert_eq!(RUST_IMPLEMENTATION_REVISION, "unimplemented");
    assert_eq!(SUBJECT_ID, "complianceimpact.projected_graph");
    assert_eq!(contracts::FIXTURE_CORPUS.len(), 1);
    assert_eq!(contracts::PORT_TRACES.len(), 1);
    assert_eq!(contracts::REQUIRED_RECEIPT_MODES.len(), 2);
    assert_eq!(contracts::ACCEPTED_RECEIPTS.len(), 0);
    assert_eq!(contracts::DELETION_ELIGIBLE, false);
    assert_eq!(contracts::DELETION_REASON_CODES.len(), 2);
    // This scaffold is intentionally not deletion-eligible without exact differential receipts.
}
