apiVersion: cerebro.writer.com/v1alpha1
kind: PolicyFindingRuleTest
cases:
    - name: matching resource produces a finding
      resource:
        assume_role_policy_document:
            Statement:
                Principal:
                    AWS: '*'
      wantFinding: true
    - name: non-matching resource passes
      resource:
        assume_role_policy_document:
            Statement:
                Principal:
                    AWS: '*-passing'
      wantFinding: false
