apiVersion: cerebro.writer.com/v1alpha1
kind: PolicyFindingRuleTest
cases:
    - name: matching resource produces a finding
      resource:
        auth_type: BASIC_AUTH
        server_type: GITHUB
      wantFinding: true
    - name: non-matching resource passes
      resource:
        auth_type: BASIC_AUTH-passing
        server_type: GITHUB
      wantFinding: false
