// Code generated by tools/rustcarve. DO NOT EDIT.

use super::{
    MIGRATION_IR_DIGEST_SHA256, MIGRATION_IR_VERSION, RUST_IMPLEMENTATION_REVISION,
    RUSTCARVE_TOOL_REVISION, SUBJECT_ID, contracts,
};

#[test]
fn generated_contract_is_closed_and_revision_bound() {
    assert_eq!(RUSTCARVE_TOOL_REVISION, "cerebro.rustcarve/v2");
    assert_eq!(MIGRATION_IR_VERSION, "standard-source/v2");
    assert_eq!(
        MIGRATION_IR_DIGEST_SHA256,
        "sha256:ed0ddc3c30f34c0beee5c5c0c9f3adb85f898d25898ab0615563e0f3e77f13ab"
    );
    assert_eq!(
        RUST_IMPLEMENTATION_REVISION,
        "24a48b50fbf087eb9b484d31f984f98fcc6e325c"
    );
    assert_eq!(SUBJECT_ID, "acunetix");
    assert_eq!(contracts::FIXTURE_CORPUS.len(), 5);
    assert_eq!(contracts::PORT_TRACES.len(), 1);
    assert_eq!(contracts::REQUIRED_RECEIPT_MODES.len(), 1);
    assert_eq!(contracts::ACCEPTED_RECEIPTS.len(), 0);
    assert_eq!(contracts::DELETION_ELIGIBLE, false);
    assert_eq!(contracts::DELETION_REASON_CODES.len(), 4);
    assert_eq!(contracts::AUTHORITY_GATES.len(), 2);
    // This scaffold is intentionally not deletion-eligible without exact differential receipts.
}
