// Code generated by tools/rustcarve. DO NOT EDIT.

#[path = "contracts.rs"]
pub mod contracts;
#[cfg(test)]
#[path = "parity_test.rs"]
mod parity_test;

pub const RUSTCARVE_TOOL_REVISION: &str = "cerebro.rustcarve/v1";
pub const MIGRATION_IR_VERSION: &str = "standard-source/v1";
pub const MIGRATION_IR_DIGEST_SHA256: &str =
    "sha256:6096890211faa327b3fdbbd37827cc4ae6649179b6f7ef107cd4587454cd5b6b";
pub const SUBJECT_ID: &str = "acunetix";
pub const RUST_IMPLEMENTATION_REVISION: &str = "24a48b50fbf087eb9b484d31f984f98fcc6e325c";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct AuthenticatedScope<'a> {
    pub tenant_id: &'a str,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ScopeError {
    MissingTenant,
    MissingWorkspace,
    ForbiddenWorkspace,
}

pub fn validate_scope(scope: AuthenticatedScope<'_>) -> Result<(), ScopeError> {
    if scope.tenant_id.trim().is_empty() {
        return Err(ScopeError::MissingTenant);
    }
    Ok(())
}
