package main

import (
	"encoding/hex"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"google.golang.org/protobuf/proto"

	"github.com/writer/cerebro/internal/connectorcatalog"
	"github.com/writer/cerebro/internal/connectordefinitions"
)

func main() {
	goOut := flag.String("go-out", "plans_gen.go", "generated Go output")
	wireHexOut := flag.String("wire-hex-out", "", "canonical protobuf wire fixture")
	flag.Parse()

	entry, found, err := connectorcatalog.BuiltinEntry("azure")
	if err != nil || !found {
		fatalf("load Azure catalog: found=%v err=%v", found, err)
	}
	plan, err := connectordefinitions.CompileSourceExecutionPlanV1(entry.Definition, "authorization_policy")
	if err != nil {
		fatalf("compile Azure authorization policy plan: %v", err)
	}
	source := fmt.Sprintf(`// Code generated by sourceplangen; DO NOT EDIT.

package sourceworker

import cerebrov1 "github.com/writer/cerebro/gen/cerebro/v1"

// AzureAuthorizationPolicyPlan returns the generated, credential-free plan for
// the first-party Azure authorization policy family. Runtime code does not read
// the connector catalog YAML.
func AzureAuthorizationPolicyPlan() *cerebrov1.SourceExecutionPlanV1 {
	return &cerebrov1.SourceExecutionPlanV1{
		PlanId: %s,
		SourceId: %s,
		FamilyId: %s,
		ProviderKernel: %s,
		Method: %s,
		Origin: %s,
		Path: %s,
		RecordSelector: %s,
		IdField: %s,
		SingletonFallbackId: %s,
		MaxResponseBytes: %d,
		EventKind: %s,
		SchemaRef: %s,
		RequiredAttributes: %#v,
		RequiredPayloadFields: %#v,
		PlanDigestSha256: %s,
	}
}
`, quote(plan.GetPlanId()), quote(plan.GetSourceId()), quote(plan.GetFamilyId()), quote(plan.GetProviderKernel()), quote(plan.GetMethod()), quote(plan.GetOrigin()), quote(plan.GetPath()), quote(plan.GetRecordSelector()), quote(plan.GetIdField()), quote(plan.GetSingletonFallbackId()), plan.GetMaxResponseBytes(), quote(plan.GetEventKind()), quote(plan.GetSchemaRef()), plan.GetRequiredAttributes(), plan.GetRequiredPayloadFields(), quote(plan.GetPlanDigestSha256()))
	formatted, err := format.Source([]byte(source))
	if err != nil {
		fatalf("format generated Go: %v", err)
	}
	if err := os.WriteFile(*goOut, formatted, 0o644); err != nil {
		fatalf("write %s: %v", *goOut, err)
	}
	if *wireHexOut != "" {
		wire, err := proto.MarshalOptions{Deterministic: true}.Marshal(plan)
		if err != nil {
			fatalf("encode plan: %v", err)
		}
		if err := os.MkdirAll(filepath.Dir(*wireHexOut), 0o755); err != nil {
			fatalf("create fixture directory: %v", err)
		}
		if err := os.WriteFile(*wireHexOut, []byte(hex.EncodeToString(wire)+"\n"), 0o644); err != nil {
			fatalf("write %s: %v", *wireHexOut, err)
		}
	}
}

func quote(value string) string { return strconv.Quote(value) }

func fatalf(format string, values ...any) {
	_, _ = fmt.Fprintf(os.Stderr, strings.TrimSpace(format)+"\n", values...)
	os.Exit(1)
}
