#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys
import tempfile
from typing import Any

import yaml


def load_stack(path: Path) -> dict[str, Any]:
    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    config = raw.get("config") or {}
    return {str(key).removeprefix("cerebro:"): value for key, value in config.items()}


def stack_name(path: Path) -> str:
    name = path.name
    if name.startswith("Pulumi.") and name.endswith(".yaml"):
        return name.removeprefix("Pulumi.").removesuffix(".yaml")
    return path.stem


def bool_value(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    return str(value or "").strip().lower() in {"1", "true", "yes", "on"}


def collector_secret_id(config: dict[str, Any], stack: str) -> str:
    environment = str(config.get("environment") or stack).strip()
    external_prefix = str(config.get("externalSecretsPrefix") or f"cerebro-{environment}").strip()
    infisical_prefix = str(config.get("infisicalSecretsPrefix") or external_prefix).strip()
    prefix = str(config.get("otelCollectorConfigSecretPrefix") or infisical_prefix).strip().strip("/")
    source = str(config.get("otelCollectorConfigSecretName") or "CEREBRO_OTEL_COLLECTOR_CONFIG").strip().strip("/")
    if not source:
        raise ValueError("otelCollectorConfigSecretName is required")
    return f"{prefix}/{source}" if prefix else source


def service_name(config: dict[str, Any], stack: str) -> str:
    environment = str(config.get("environment") or stack).strip()
    return f"cerebro-{environment}"


def render_collector_config(service: str) -> str:
    metrics_log_group = f"/aws/otel/{service}/metrics"
    return f"""extensions:
  health_check:
    endpoint: 127.0.0.1:13133

receivers:
  prometheus/internal:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 30s
          static_configs:
            - targets: [127.0.0.1:8888]
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4317
      http:
        endpoint: 127.0.0.1:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 192
    spike_limit_mib: 64
  resourcedetection:
    detectors: [env, ecs]
    timeout: 2s
    override: false
  batch/traces:
    timeout: 5s
    send_batch_size: 512
  batch/metrics:
    timeout: 30s
    send_batch_size: 512

exporters:
  awsxray: {{}}
  awsemf:
    namespace: Cerebro/OTEL
    log_group_name: {metrics_log_group}
    dimension_rollup_option: NoDimensionRollup

service:
  extensions: [health_check]
  telemetry:
    logs:
      level: info
    metrics:
      level: detailed
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, batch/traces]
      exporters: [awsxray]
    metrics:
      receivers: [otlp, prometheus/internal]
      processors: [memory_limiter, resourcedetection, batch/metrics]
      exporters: [awsemf]
"""


def aws_json(args: list[str], profile: str | None, region: str) -> tuple[int, dict[str, Any] | None, str]:
    command = ["aws", *args, "--region", region, "--output", "json"]
    if profile:
        command.extend(["--profile", profile])
    completed = subprocess.run(command, text=True, capture_output=True)
    payload = None
    if completed.stdout.strip():
        try:
            payload = json.loads(completed.stdout)
        except json.JSONDecodeError:
            payload = None
    return completed.returncode, payload, (completed.stderr or completed.stdout or "").strip()


def upsert_secret(secret_id: str, value: str, profile: str | None, region: str, dry_run: bool) -> str:
    if dry_run:
        return "dry-run"
    code, _, detail = aws_json(["secretsmanager", "describe-secret", "--secret-id", secret_id], profile, region)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", delete=True) as handle:
        handle.write(value)
        handle.flush()
        if code == 0:
            update_code, _, update_detail = aws_json(
                ["secretsmanager", "put-secret-value", "--secret-id", secret_id, "--secret-string", f"file://{handle.name}"],
                profile,
                region,
            )
            if update_code != 0:
                raise RuntimeError(f"failed to update collector config secret: {update_detail}")
            return "updated"
        if "ResourceNotFoundException" not in detail:
            raise RuntimeError(f"failed to describe collector config secret: {detail}")
        create_code, _, create_detail = aws_json(
            [
                "secretsmanager",
                "create-secret",
                "--name",
                secret_id,
                "--description",
                "Cerebro ADOT collector config generated by infra/scripts/provision_otel_collector_config.py",
                "--secret-string",
                f"file://{handle.name}",
            ],
            profile,
            region,
        )
        if create_code != 0:
            raise RuntimeError(f"failed to create collector config secret: {create_detail}")
        return "created"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Create or update the ADOT collector config secret for a Cerebro AWS stack.")
    parser.add_argument("--stack-file", type=Path, required=True)
    parser.add_argument("--profile")
    parser.add_argument("--region", default="us-east-1")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--print-config", action="store_true")
    parser.add_argument("--skip-if-disabled", action="store_true")
    args = parser.parse_args(argv)

    config = load_stack(args.stack_file)
    if not bool_value(config.get("otelCollectorEnabled")):
        if args.skip_if_disabled:
            print("skipped: otelCollectorEnabled is not true")
            return 0
        raise ValueError("otelCollectorEnabled must be true for the selected stack")
    stack = stack_name(args.stack_file)
    secret_id = collector_secret_id(config, stack)
    rendered = render_collector_config(service_name(config, stack))
    if args.print_config:
        sys.stdout.write(rendered)
        return 0
    upsert_secret(secret_id, rendered, args.profile, args.region, args.dry_run)
    digest = hashlib.sha256(rendered.encode("utf-8")).hexdigest()[:12]
    mode = "dry-run" if args.dry_run else "applied"
    print(f"{mode}: collector config ready config_sha256={digest}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        sys.exit(1)
