package workflowevents

import eventregistry "github.com/WriterInternal/event-registry/clients/go"

func registryDecisionRecorded(payload DecisionRecorded) eventregistry.DecisionRecordedV1 {
	return eventregistry.DecisionRecordedV1{
		TenantID:      payload.TenantID,
		DecisionID:    payload.DecisionID,
		DecisionType:  payload.DecisionType,
		Status:        payload.Status,
		MadeBy:        optionalString(payload.MadeBy),
		Rationale:     optionalString(payload.Rationale),
		TargetIDs:     payload.TargetIDs,
		EvidenceIDs:   payload.EvidenceIDs,
		ActionIDs:     payload.ActionIDs,
		SourceSystem:  payload.SourceSystem,
		SourceEventID: optionalString(payload.SourceEventID),
		ObservedAt:    payload.ObservedAt,
		ValidFrom:     payload.ValidFrom,
		ValidTo:       optionalString(payload.ValidTo),
		Confidence:    optionalFloat64(payload.Confidence),
		Metadata:      payload.Metadata,
	}
}

func registryActionRecorded(payload ActionRecorded) eventregistry.ActionRecordedV1 {
	return eventregistry.ActionRecordedV1{
		TenantID:         payload.TenantID,
		ActionID:         payload.ActionID,
		ActionType:       payload.ActionType,
		Status:           payload.Status,
		RecommendationID: optionalString(payload.RecommendationID),
		InsightType:      optionalString(payload.InsightType),
		Title:            payload.Title,
		Summary:          optionalString(payload.Summary),
		DecisionID:       optionalString(payload.DecisionID),
		TargetIDs:        payload.TargetIDs,
		SourceSystem:     payload.SourceSystem,
		SourceEventID:    optionalString(payload.SourceEventID),
		ObservedAt:       payload.ObservedAt,
		ValidFrom:        payload.ValidFrom,
		ValidTo:          optionalString(payload.ValidTo),
		Confidence:       optionalFloat64(payload.Confidence),
		AutoGenerated:    payload.AutoGenerated,
		Metadata:         payload.Metadata,
	}
}

func registryOutcomeRecorded(payload OutcomeRecorded) eventregistry.OutcomeRecordedV1 {
	return eventregistry.OutcomeRecordedV1{
		TenantID:      payload.TenantID,
		OutcomeID:     payload.OutcomeID,
		DecisionID:    payload.DecisionID,
		OutcomeType:   payload.OutcomeType,
		Verdict:       payload.Verdict,
		ImpactScore:   optionalFloat64(payload.ImpactScore),
		TargetIDs:     payload.TargetIDs,
		SourceSystem:  payload.SourceSystem,
		SourceEventID: optionalString(payload.SourceEventID),
		ObservedAt:    payload.ObservedAt,
		ValidFrom:     payload.ValidFrom,
		ValidTo:       optionalString(payload.ValidTo),
		Confidence:    optionalFloat64(payload.Confidence),
		Metadata:      payload.Metadata,
	}
}

func registryFindingRecorded(payload FindingRecorded) eventregistry.FindingRecordedV1 {
	return eventregistry.FindingRecordedV1{
		Finding:    registryFindingSnapshot(payload.Finding),
		RecordedAt: payload.RecordedAt,
	}
}

func registryFindingNoteAdded(payload FindingNoteAdded) eventregistry.FindingNoteAddedV1 {
	return eventregistry.FindingNoteAddedV1{
		Finding:   registryFindingSnapshot(payload.Finding),
		NoteID:    payload.NoteID,
		Body:      payload.Body,
		CreatedAt: payload.CreatedAt,
	}
}

func registryFindingTicketLinked(payload FindingTicketLinked) eventregistry.FindingTicketLinkedV1 {
	return eventregistry.FindingTicketLinkedV1{
		Finding:    registryFindingSnapshot(payload.Finding),
		URL:        payload.URL,
		Name:       optionalString(payload.Name),
		ExternalID: optionalString(payload.ExternalID),
		LinkedAt:   payload.LinkedAt,
	}
}

func registryFindingExternalRefLinked(payload FindingExternalRefLinked) eventregistry.FindingExternalRefLinkedV1 {
	return eventregistry.FindingExternalRefLinkedV1{
		Finding:              registryFindingSnapshot(payload.Finding),
		System:               payload.System,
		Kind:                 payload.Kind,
		ExternalID:           payload.ExternalID,
		URL:                  optionalString(payload.URL),
		ExternalStatus:       optionalString(payload.ExternalStatus),
		ExternalStatusReason: optionalString(payload.ExternalStatusReason),
		LifecycleOwner:       optionalString(payload.LifecycleOwner),
		LinkedAt:             payload.LinkedAt,
	}
}

func registryFindingStatusChanged(payload FindingStatusChanged) eventregistry.FindingStatusChangedV1 {
	return eventregistry.FindingStatusChangedV1{
		Finding:     registryFindingSnapshot(payload.Finding),
		Status:      payload.Status,
		Reason:      optionalString(payload.Reason),
		Source:      optionalString(payload.Source),
		UpdatedAt:   payload.UpdatedAt,
		DecisionID:  optionalString(payload.DecisionID),
		OutcomeID:   optionalString(payload.OutcomeID),
		OutcomeType: optionalString(payload.OutcomeType),
	}
}

func registryFindingTombstoned(payload FindingTombstoned) eventregistry.FindingTombstonedV1 {
	return eventregistry.FindingTombstonedV1{
		Finding:      registryFindingSnapshot(payload.Finding),
		PriorStatus:  payload.PriorStatus,
		Reason:       payload.Reason,
		Actor:        payload.Actor,
		RunID:        payload.RunID,
		TombstonedAt: payload.TombstonedAt,
	}
}

func registryFindingSnapshot(finding FindingSnapshot) eventregistry.FindingSnapshot {
	return eventregistry.FindingSnapshot{
		TenantID:           finding.TenantID,
		SourceSystem:       finding.SourceSystem,
		FindingID:          finding.FindingID,
		Fingerprint:        optionalString(finding.Fingerprint),
		Title:              optionalString(finding.Title),
		Summary:            optionalString(finding.Summary),
		RuleID:             optionalString(finding.RuleID),
		Severity:           optionalString(finding.Severity),
		Status:             optionalString(finding.Status),
		RuntimeID:          optionalString(finding.RuntimeID),
		PolicyID:           optionalString(finding.PolicyID),
		CheckID:            optionalString(finding.CheckID),
		PrimaryResourceURN: optionalString(finding.PrimaryResourceURN),
		ResourceURNs:       finding.ResourceURNs,
		EventIDs:           finding.EventIDs,
		FirstObservedAt:    optionalString(finding.FirstObservedAt),
		LastObservedAt:     optionalString(finding.LastObservedAt),
		ResourceCount:      finding.ResourceCount,
		EventCount:         finding.EventCount,
		ControlRefs:        registryFindingControlRefs(finding.ControlRefs),
		RiskScore:          finding.RiskScore,
		EffectiveSeverity:  optionalString(finding.EffectiveSeverity),
		LikelihoodScore:    finding.LikelihoodScore,
		ImpactScore:        finding.ImpactScore,
		ConfidenceScore:    finding.ConfidenceScore,
		LikelihoodLevel:    optionalString(finding.LikelihoodLevel),
		ImpactLevel:        optionalString(finding.ImpactLevel),
		RiskModelVersion:   optionalString(finding.RiskModelVersion),
		RiskReasons:        finding.RiskReasons,
		Metadata:           finding.Metadata,
	}
}

func registryFindingControlRefs(refs []FindingControlRefSnapshot) []eventregistry.FindingControlRefSnapshot {
	if len(refs) == 0 {
		return nil
	}
	converted := make([]eventregistry.FindingControlRefSnapshot, 0, len(refs))
	for _, ref := range refs {
		converted = append(converted, eventregistry.FindingControlRefSnapshot{
			FrameworkName: ref.FrameworkName,
			ControlID:     ref.ControlID,
		})
	}
	return converted
}

func optionalString(value string) *string {
	if value == "" {
		return nil
	}
	return &value
}

func optionalFloat64(value float64) *float64 {
	if value == 0 {
		return nil
	}
	return &value
}
