//! Public CodeBuild wire types and fail-closed errors.

use std::{collections::BTreeMap, error::Error, fmt};

use reqwest::Url;
use serde_json::Value;

pub(super) const AWS_JSON_CONTENT_TYPE: &str = "application/x-amz-json-1.1";

/// CodeBuild source family covered by the provider-local kernel.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AwsCodeBuildFamily {
    /// CodeBuild projects and their non-secret posture metadata.
    Project,
    /// Imported source-credential metadata; credential values are never returned.
    SourceCredential,
}

impl AwsCodeBuildFamily {
    /// Return the Go source family identifier.
    pub const fn id(self) -> &'static str {
        match self {
            Self::Project => "codebuild_project",
            Self::SourceCredential => "codebuild_source_credential",
        }
    }

    pub(super) const fn provider_kind(self) -> &'static str {
        match self {
            Self::Project => "aws.codebuild_project",
            Self::SourceCredential => "aws.codebuild_source_credential",
        }
    }

    pub(super) const fn schema_ref(self) -> &'static str {
        match self {
            Self::Project => "aws/codebuild_project/v1",
            Self::SourceCredential => "aws/codebuild_source_credential/v1",
        }
    }
}

/// Purpose of one CodeBuild provider request.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AwsCodeBuildRequestKind {
    /// List project names and the provider continuation token.
    ListProjects,
    /// Read complete project objects for at most 100 names.
    BatchGetProjects,
    /// List imported source-credential metadata.
    ListSourceCredentials,
}

impl AwsCodeBuildRequestKind {
    const fn target(self) -> &'static str {
        match self {
            Self::ListProjects => "CodeBuild_20161006.ListProjects",
            Self::BatchGetProjects => "CodeBuild_20161006.BatchGetProjects",
            Self::ListSourceCredentials => "CodeBuild_20161006.ListSourceCredentials",
        }
    }
}

/// One credential-free CodeBuild AWS JSON request.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AwsCodeBuildRequest {
    pub(super) url: Url,
    pub(super) family: AwsCodeBuildFamily,
    pub(super) kind: AwsCodeBuildRequestKind,
    pub(super) account_id: String,
    pub(super) region: String,
    pub(super) cursor: Option<String>,
    pub(super) names: Option<Vec<String>>,
    pub(super) body: Vec<u8>,
    pub(super) kernel_fingerprint: [u8; 32],
}

impl AwsCodeBuildRequest {
    /// Return the exact provider URL. The caller must authorize it before I/O.
    pub fn url(&self) -> &Url {
        &self.url
    }

    /// Return the correlated source family.
    pub const fn family(&self) -> AwsCodeBuildFamily {
        self.family
    }

    /// Return the operation represented by this request.
    pub const fn kind(&self) -> AwsCodeBuildRequestKind {
        self.kind
    }

    /// Return the exact HTTP method.
    pub const fn method(&self) -> &'static str {
        "POST"
    }

    /// Return the request body without authorization material.
    pub fn body(&self) -> &[u8] {
        &self.body
    }

    /// Return the AWS JSON media type.
    pub const fn content_type(&self) -> &'static str {
        AWS_JSON_CONTENT_TYPE
    }

    /// Return the exact `X-Amz-Target` value generated by the Go SDK.
    pub const fn amz_target(&self) -> &'static str {
        self.kind.target()
    }

    /// Return the Signature Version 4 service name.
    pub const fn signing_service(&self) -> &'static str {
        "codebuild"
    }

    /// Return the Signature Version 4 region.
    pub fn signing_region(&self) -> &str {
        &self.region
    }
}

/// One normalized CodeBuild record.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AwsCodeBuildRecord {
    /// Go source family identifier.
    pub family: String,
    /// Provider event kind.
    pub provider_kind: String,
    /// Versioned schema reference.
    pub schema_ref: String,
    /// Stable Go-compatible event identifier.
    pub provider_id: String,
    /// Portable scalar fields consumed by source mapping.
    pub fields: BTreeMap<String, String>,
    /// Sanitized payload; environment-variable and credential values are excluded.
    pub payload: Value,
}

/// Result of one CodeBuild operation.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AwsCodeBuildBatch {
    /// Complete records returned by this operation.
    pub records: Vec<AwsCodeBuildRecord>,
    /// Correlated project-detail requests required to finish a list page.
    pub requests: Vec<AwsCodeBuildRequest>,
    /// Validated list-projects continuation token.
    pub next_cursor: Option<String>,
}

/// Safe CodeBuild kernel failures.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum AwsCodeBuildError {
    /// Service base URL is not a secure origin-only URL.
    InvalidBaseUrl,
    /// Account identity is not exactly twelve ASCII digits.
    InvalidAccountId,
    /// Region is empty or contains an unsafe character.
    InvalidRegion,
    /// Provider cursor is empty, oversized, padded, or contains a control character.
    InvalidCursor,
    /// The non-paginated source-credential family received a cursor.
    CursorNotSupported,
    /// Request family, stage, origin, body, or kernel correlation does not match.
    RequestScopeMismatch,
    /// Provider returned a non-success status and safe error identifier.
    ProviderFailure {
        /// HTTP status returned by the provider.
        status: u16,
        /// Bounded Smithy error identifier, when safe and present.
        code: Option<String>,
    },
    /// Provider response is oversized, malformed, or violates the operation shape.
    InvalidResponse,
    /// Provider project lacks the stable identity required by the Go contract.
    MissingIdentity,
}

impl fmt::Display for AwsCodeBuildError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidBaseUrl => formatter.write_str("invalid CodeBuild base URL"),
            Self::InvalidAccountId => formatter.write_str("invalid AWS account ID"),
            Self::InvalidRegion => formatter.write_str("invalid AWS region"),
            Self::InvalidCursor => formatter.write_str("invalid CodeBuild cursor"),
            Self::CursorNotSupported => formatter.write_str("CodeBuild family does not paginate"),
            Self::RequestScopeMismatch => formatter.write_str("CodeBuild request scope mismatch"),
            Self::ProviderFailure { status, code } => {
                write!(
                    formatter,
                    "CodeBuild provider request failed with status {status}"
                )?;
                if let Some(code) = code {
                    write!(formatter, " ({code})")?;
                }
                Ok(())
            }
            Self::InvalidResponse => formatter.write_str("invalid CodeBuild provider response"),
            Self::MissingIdentity => formatter.write_str("CodeBuild project identity is missing"),
        }
    }
}

impl Error for AwsCodeBuildError {}
