package codegencatalog

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	APIVersion = "devex.cerebro/v1alpha1"
	Kind       = "CodegenCatalog"
)

var ErrInvalidCatalog = errors.New("invalid codegen catalog")

type Catalog struct {
	APIVersion string   `json:"api_version"`
	Kind       string   `json:"kind"`
	Families   []Family `json:"families"`
}

type Family struct {
	ID           string   `json:"id"`
	Title        string   `json:"title"`
	Summary      string   `json:"summary"`
	ChangeReason string   `json:"change_reason"`
	Triggers     []string `json:"triggers"`
	Generator    Command  `json:"generator"`
	Checks       []Check  `json:"checks"`
	Outputs      []string `json:"outputs"`
	CIJobs       []string `json:"ci_jobs"`
}

type Command struct {
	MakeTarget string   `json:"make_target"`
	Command    []string `json:"command"`
	Summary    string   `json:"summary"`
}

type Check struct {
	Key                      string   `json:"key"`
	Summary                  string   `json:"summary"`
	MakeTarget               string   `json:"make_target"`
	Command                  []string `json:"command"`
	IncludeInPRGeneratedStep bool     `json:"include_in_pr_generated_step,omitempty"`
}

func Load(path string) (*Catalog, error) {
	payload, err := os.ReadFile(path) // #nosec G304 -- operator-provided repository path.
	if err != nil {
		return nil, fmt.Errorf("read codegen catalog: %w", err)
	}
	var catalog Catalog
	decoder := json.NewDecoder(bytes.NewReader(payload))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&catalog); err != nil {
		return nil, fmt.Errorf("decode codegen catalog: %w", err)
	}
	if err := catalog.Validate(); err != nil {
		return nil, err
	}
	return &catalog, nil
}

func (c Catalog) Validate() error {
	var issues []string
	if c.APIVersion != APIVersion {
		issues = append(issues, fmt.Sprintf("api_version must be %q", APIVersion))
	}
	if c.Kind != Kind {
		issues = append(issues, fmt.Sprintf("kind must be %q", Kind))
	}
	if len(c.Families) == 0 {
		issues = append(issues, "families cannot be empty")
	}
	seenFamilies := map[string]struct{}{}
	for index, family := range c.Families {
		prefix := fmt.Sprintf("families[%d]", index)
		if strings.TrimSpace(family.ID) == "" {
			issues = append(issues, prefix+".id is required")
		} else if _, exists := seenFamilies[family.ID]; exists {
			issues = append(issues, fmt.Sprintf("duplicate family id %q", family.ID))
		} else {
			seenFamilies[family.ID] = struct{}{}
		}
		if strings.TrimSpace(family.Title) == "" {
			issues = append(issues, prefix+".title is required")
		}
		if len(family.Triggers) == 0 {
			issues = append(issues, prefix+".triggers cannot be empty")
		}
		if len(family.Generator.Command) == 0 || strings.TrimSpace(family.Generator.MakeTarget) == "" {
			issues = append(issues, prefix+".generator command and make_target are required")
		}
		if len(family.Checks) == 0 {
			issues = append(issues, prefix+".checks cannot be empty")
		}
		seenChecks := map[string]struct{}{}
		for checkIndex, check := range family.Checks {
			checkPrefix := fmt.Sprintf("%s.checks[%d]", prefix, checkIndex)
			if strings.TrimSpace(check.Key) == "" || len(check.Command) == 0 || strings.TrimSpace(check.MakeTarget) == "" {
				issues = append(issues, checkPrefix+" key, command, and make_target are required")
			}
			if _, exists := seenChecks[check.Key]; exists {
				issues = append(issues, fmt.Sprintf("%s has duplicate check %q", prefix, check.Key))
			}
			seenChecks[check.Key] = struct{}{}
		}
		if len(family.Outputs) == 0 {
			issues = append(issues, prefix+".outputs cannot be empty")
		}
	}
	if len(issues) > 0 {
		return fmt.Errorf("%w: %s", ErrInvalidCatalog, strings.Join(issues, "; "))
	}
	return nil
}

func (c Catalog) CanonicalJSON() ([]byte, error) {
	payload, err := json.MarshalIndent(c, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(payload, '\n'), nil
}

func (c Catalog) Markdown() []byte {
	var out strings.Builder
	out.WriteString("# DevEx Codegen Catalog\n\n")
	out.WriteString("Generated from `devex/codegen_catalog.json`. Do not edit this file directly.\n\n")
	fmt.Fprintf(&out, "- Catalog API version: **%s**\n", c.APIVersion)
	fmt.Fprintf(&out, "- Catalog kind: **%s**\n", c.Kind)
	fmt.Fprintf(&out, "- Families: **%d**\n\n", len(c.Families))
	out.WriteString("## CI To Local Map\n\n")
	out.WriteString("| Family | Generator | Local Checks | CI Jobs | Outputs |\n")
	out.WriteString("|---|---|---|---|---|\n")
	for _, family := range c.Families {
		fmt.Fprintf(&out, "| `%s` | `%s` | %s | %s | %s |\n", family.ID, family.Generator.MakeTarget, codeList(checkTargets(family.Checks)), codeList(family.CIJobs), codeList(family.Outputs))
	}
	out.WriteString("\n## Families\n\n")
	for _, family := range c.Families {
		fmt.Fprintf(&out, "### `%s`\n\n%s\n\n", family.ID, family.Summary)
		fmt.Fprintf(&out, "- Change reason: %s\n", family.ChangeReason)
		fmt.Fprintf(&out, "- Generator: `%s` -> `%s`\n", family.Generator.MakeTarget, strings.Join(family.Generator.Command, " "))
		out.WriteString("- Checks:\n")
		for _, check := range family.Checks {
			fmt.Fprintf(&out, "  - `%s` -> `%s`\n", check.Key, strings.Join(check.Command, " "))
		}
		fmt.Fprintf(&out, "- Triggers: %s\n", codeList(family.Triggers))
		fmt.Fprintf(&out, "- Outputs: %s\n", codeList(family.Outputs))
		fmt.Fprintf(&out, "- CI jobs: %s\n\n", codeList(family.CIJobs))
	}
	out.WriteString("## Operator Commands\n\n")
	out.WriteString("- `make codegen-status`: show every registered generator and catalog readiness.\n")
	out.WriteString("- `make codegen-check`: run each unique registered codegen check.\n")
	out.WriteString("- `go run ./tools/codegenstatus -changed-base origin/main`: show generators selected by the current diff.\n")
	out.WriteString("- `make codegen-catalog-check`: verify this document and its machine-readable copy match the registry.\n")
	return []byte(out.String())
}

func (c Catalog) Select(changedPaths []string) []Family {
	selected := make([]Family, 0)
	for _, family := range c.Families {
		if familyMatches(family, changedPaths) {
			selected = append(selected, family)
		}
	}
	return selected
}

func familyMatches(family Family, paths []string) bool {
	for _, trigger := range family.Triggers {
		for _, path := range paths {
			if triggerMatches(trigger, path) {
				return true
			}
		}
	}
	return false
}

func triggerMatches(pattern, path string) bool {
	pattern = filepath.ToSlash(strings.TrimSpace(pattern))
	path = filepath.ToSlash(strings.TrimSpace(path))
	if strings.HasSuffix(pattern, "/**") {
		return strings.HasPrefix(path, strings.TrimSuffix(pattern, "**"))
	}
	matched, err := filepath.Match(pattern, path)
	return err == nil && matched
}

func checkTargets(checks []Check) []string {
	targets := make([]string, 0, len(checks))
	for _, check := range checks {
		targets = append(targets, check.MakeTarget)
	}
	sort.Strings(targets)
	return targets
}

func codeList(values []string) string {
	if len(values) == 0 {
		return "none"
	}
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, "`"+value+"`")
	}
	return strings.Join(quoted, ", ")
}
