// Staging and built-in-catalog file writers.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/writer/cerebro/internal/connectorimport"
)

func writeStagingCatalogs(outDir string, outcomes []connectorimport.Outcome) error {
	byDomain := map[string][]connectorimport.Outcome{}
	for _, outcome := range outcomes {
		if !outcome.CatalogReady() {
			continue
		}
		byDomain[catalogDomain(outcome.Domain)] = append(byDomain[catalogDomain(outcome.Domain)], outcome)
	}
	for domain, entries := range byDomain {
		sort.SliceStable(entries, func(i, j int) bool { return entries[i].SourceID < entries[j].SourceID })
		for _, outcome := range entries {
			header := fmt.Sprintf("Candidate connector definition for %s.\nGenerated by tools/connectorimport; review before promotion.", outcome.SourceID)
			body, err := connectorimport.RenderCatalogEntries(header, []connectorimport.Outcome{outcome})
			if err != nil {
				return err
			}
			path := filepath.Join(outDir, domain, catalogSourceFileName(outcome.SourceID))
			if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
				return fmt.Errorf("create catalog staging dir %s: %w", filepath.Dir(path), err)
			}
			if err := os.WriteFile(path, body, 0o600); err != nil {
				return fmt.Errorf("write %s: %w", path, err)
			}
		}
	}
	return nil
}

func appendToCatalog(catalogDir string, outcomes []connectorimport.Outcome) (int, error) {
	globalPresent, err := existingCatalogSourceIDs(catalogDir)
	if err != nil {
		return 0, err
	}
	byDomain := map[string][]connectorimport.Outcome{}
	for _, outcome := range outcomes {
		if outcome.CatalogReady() {
			byDomain[catalogDomain(outcome.Domain)] = append(byDomain[catalogDomain(outcome.Domain)], outcome)
		}
	}
	appended := 0
	for domain, entries := range byDomain {
		sort.SliceStable(entries, func(i, j int) bool { return entries[i].SourceID < entries[j].SourceID })
		for _, outcome := range entries {
			if _, ok := globalPresent[outcome.SourceID]; ok {
				continue
			}
			path := filepath.Join(catalogDir, domain, catalogSourceFileName(outcome.SourceID))
			if _, err := os.Stat(path); err == nil {
				globalPresent[outcome.SourceID] = struct{}{}
				continue
			} else if err != nil && !os.IsNotExist(err) {
				return appended, fmt.Errorf("stat catalog file %s: %w", path, err)
			}
			header := fmt.Sprintf("Built-in connector definition for %s.\nGenerated by tools/connectorimport.", outcome.SourceID)
			body, err := connectorimport.RenderCatalogEntries(header, []connectorimport.Outcome{outcome})
			if err != nil {
				return appended, err
			}
			if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
				return appended, fmt.Errorf("create catalog dir %s: %w", filepath.Dir(path), err)
			}
			if err := os.WriteFile(path, body, 0o600); err != nil {
				return appended, fmt.Errorf("write catalog file %s: %w", path, err)
			}
			globalPresent[outcome.SourceID] = struct{}{}
			appended++
		}
	}
	return appended, nil
}

func existingCatalogSourceIDs(catalogDir string) (map[string]struct{}, error) {
	ids := map[string]struct{}{}
	err := filepath.WalkDir(catalogDir, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		ext := strings.ToLower(filepath.Ext(path))
		if ext != ".yaml" && ext != ".yml" && ext != ".json" {
			return nil
		}
		existing, err := os.ReadFile(path) //nolint:gosec // operator-provided catalog dir for a build-time tool.
		if err != nil {
			return fmt.Errorf("read catalog file %s: %w", path, err)
		}
		for id := range existingSourceIDs(string(existing)) {
			ids[id] = struct{}{}
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("walk catalog dir %s: %w", catalogDir, err)
	}
	return ids, nil
}

func existingSourceIDs(body string) map[string]struct{} {
	ids := map[string]struct{}{}
	for _, line := range strings.Split(body, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "source_id:") {
			ids[strings.TrimSpace(strings.TrimPrefix(trimmed, "source_id:"))] = struct{}{}
		}
	}
	return ids
}

func catalogDomain(domain string) string {
	domain = strings.TrimSpace(domain)
	if domain == "" {
		return "uncategorized"
	}
	return domain
}

func catalogSourceFileName(sourceID string) string {
	sourceID = strings.TrimSpace(sourceID)
	if sourceID == "" {
		sourceID = "source"
	}
	sourceID = strings.NewReplacer("/", "_", "\\", "_", ":", "_").Replace(sourceID)
	return sourceID + ".yaml"
}
