// Code generated by tools/rustcarve. DO NOT EDIT.

use super::{
    MIGRATION_IR_DIGEST_SHA256, MIGRATION_IR_VERSION, RUST_IMPLEMENTATION_REVISION,
    RUSTCARVE_TOOL_REVISION, SUBJECT_ID, contracts,
};

#[test]
fn generated_contract_is_closed_and_revision_bound() {
    assert_eq!(RUSTCARVE_TOOL_REVISION, "cerebro.rustcarve/v1");
    assert_eq!(MIGRATION_IR_VERSION, "graph-query/v1");
    assert_eq!(
        MIGRATION_IR_DIGEST_SHA256,
        "sha256:768ad831ffe223913a3f631eee787caf66d5326e56ab17bdc0ca4c77648fc693"
    );
    assert_eq!(
        RUST_IMPLEMENTATION_REVISION,
        "4c553a2d7e80c93d387eb281eae9bec0527b08c3"
    );
    assert_eq!(SUBJECT_ID, "graphquery.effective_access");
    assert_eq!(contracts::FIXTURE_CORPUS.len(), 2);
    assert_eq!(contracts::PORT_TRACES.len(), 2);
    assert_eq!(contracts::REQUIRED_RECEIPT_MODES.len(), 2);
    assert_eq!(contracts::ACCEPTED_RECEIPTS.len(), 0);
    assert_eq!(contracts::DELETION_ELIGIBLE, false);
    assert_eq!(contracts::DELETION_REASON_CODES.len(), 2);
    // This scaffold is intentionally not deletion-eligible without exact differential receipts.
}
