// Code generated by tools/rustcarve. DO NOT EDIT.

#[path = "contracts.rs"]
pub mod contracts;
#[cfg(test)]
#[path = "parity_test.rs"]
mod parity_test;

pub const RUSTCARVE_TOOL_REVISION: &str = "cerebro.rustcarve/v2";
pub const MIGRATION_IR_VERSION: &str = "graph-query/v1";
pub const MIGRATION_IR_DIGEST_SHA256: &str =
    "sha256:68f91ef9bfb3f591618d4e60fe0e46f076608aa79f17b064affdbcd50b51d0aa";
pub const SUBJECT_ID: &str = "graphquery.effective_access";
pub const RUST_IMPLEMENTATION_REVISION: &str = "4c553a2d7e80c93d387eb281eae9bec0527b08c3";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct AuthenticatedScope<'a> {
    pub tenant_id: &'a str,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ScopeError {
    MissingTenant,
    MissingWorkspace,
    ForbiddenWorkspace,
}

pub fn validate_scope(scope: AuthenticatedScope<'_>) -> Result<(), ScopeError> {
    if scope.tenant_id.trim().is_empty() {
        return Err(ScopeError::MissingTenant);
    }
    Ok(())
}
