"""
Pulumi infrastructure for the Cerebro rewrite runtime.

Deploys a private ECS service backed by:
- RDS Postgres for current state
- NATS JetStream for the append log
- Neo4j/Aura for graph projections
"""

import pulumi
import pulumi_aws as aws

import certificate as cert
import compute
import ecr
import infisical
import kms
import legacy
import load_balancer
import monitoring
import nats
import neo4j
import networking
import postgres
import tailscale as ts
import waf

config = pulumi.Config()


def _get_environment() -> str:
    if config.get("environment"):
        return config.get("environment")
    stack = pulumi.get_stack()
    if stack == "go-prod":
        return "go-production"
    if stack.startswith("go-"):
        return stack.replace("-prod", "-production")
    return "production"


def _config_int(key: str, default: int) -> int:
    value = config.get_int(key)
    return default if value is None else value


def _config_bool(key: str, default: bool) -> bool:
    value = config.get_bool(key)
    return default if value is None else value


def _env_ref(value) -> str:
    text = str(value).strip()
    if not text.startswith("env:"):
        return ""
    env_name = text.removeprefix("env:").strip()
    if not env_name:
        raise ValueError("source runtime env reference must include an environment variable name")
    return env_name


def _source_runtime_env_refs(source_runtimes: list[dict]) -> list[str]:
    refs = set()
    for runtime in source_runtimes:
        if not isinstance(runtime, dict):
            raise ValueError("sourceRuntimes entries must be objects")
        runtime_id = str(runtime.get("id", "")).strip()
        runtime_config = runtime.get("config") or {}
        if not isinstance(runtime_config, dict):
            raise ValueError(f"source runtime {runtime_id or '<unknown>'} config must be an object")
        for value in runtime_config.values():
            env_name = _env_ref(value)
            if env_name:
                refs.add(env_name)
    return sorted(refs)


def _secret_env_name(secret_key) -> str:
    if isinstance(secret_key, dict):
        return str(secret_key.get("name", "")).strip()
    return str(secret_key).strip()


def _append_missing_source_secrets(secret_keys: list, env_refs: list[str]) -> list:
    result = list(secret_keys or [])
    existing = {_secret_env_name(secret_key) for secret_key in result}
    for env_name in env_refs:
        if env_name not in existing:
            result.append(env_name)
            existing.add(env_name)
    return result


environment = _get_environment()
domain = config.get("domain") or ""
certificate_domain = config.get("certificateDomain") or ""
certificate_import_arn = config.get("certificateImportArn") or ""
ecr_base_uri = config.require("ecrBaseUri")
image_tag = config.get("imageTag") or "v1.0.0"
container_image = f"{ecr_base_uri}:{image_tag}"

alb_internal = _config_bool("albInternal", True)
configured_alb_ingress_cidrs = config.get_object("albIngressCidrs") or None
is_production = "prod" in environment.lower()

api_cpu = _config_int("apiCpu", 1024)
api_memory = _config_int("apiMemory", 2048)
api_min_instances = _config_int("apiMinInstances", 1)
api_max_instances = _config_int("apiMaxInstances", 1)
orchestrator_enabled = _config_bool("orchestratorEnabled", False)
orchestrator_schedule_expression = config.get("orchestratorScheduleExpression") or "rate(1 hour)"
orchestrator_cpu = _config_int("orchestratorCpu", api_cpu)
orchestrator_memory = _config_int("orchestratorMemory", api_memory)
orchestrator_command = config.get_object("orchestratorCommand") or ["orchestrator", "run"]
orchestrator_task_count = _config_int("orchestratorTaskCount", 1)
orchestrator_schedules = config.get_object("orchestratorSchedules") or []

if api_max_instances > 1:
    raise ValueError("Source runtime sync cursors are not cross-task locked yet; set cerebro:apiMaxInstances to 1.")

log_retention_days = _config_int("logRetentionDays", 30)
enable_waf = _config_bool("enableWaf", True)
enable_alb_access_logs = _config_bool("enableAlbAccessLogs", is_production)
enable_alb_deletion_protection = _config_bool("enableAlbDeletionProtection", is_production)
enable_kms_log_encryption = _config_bool("enableKmsLogEncryption", is_production)
nat_gateway_per_az = _config_bool("natGatewayPerAz", is_production)

# Infisical sync role remains for externally-managed source/API secrets. The
# Postgres DSN is generated by this stack into the same prefix.
enable_infisical = _config_bool("enableInfisicalSyncRole", False)
infisical_principal_arn = config.get("infisicalAssumeRolePrincipalArn")
infisical_external_id = config.get("infisicalExternalId")
external_secrets_prefix = config.get("externalSecretsPrefix") or f"cerebro-{environment}"

# Tailscale subnet router for internal access.
enable_tailscale = _config_bool("enableTailscale", False)
tailscale_hostname = config.get("tailscaleHostname") or f"cerebro-{environment}"
tailscale_advertise_routes = config.get_object("tailscaleAdvertiseRoutes") or []

# Existing VPC configuration.
use_existing_vpc = _config_bool("useExistingVpc", False)
existing_vpc_id = config.get("vpcId")
existing_private_subnet_ids = config.get_object("privateSubnetIds") or []
existing_public_subnet_ids = config.get_object("publicSubnetIds") or []
existing_vpc_cidr = config.get("vpcCidr") or "10.0.0.0/16"

# Runtime backing services.
postgres_instance_class = config.get("postgresInstanceClass") or ("db.t4g.small" if is_production else "db.t4g.micro")
postgres_allocated_storage = _config_int("postgresAllocatedStorage", 50 if is_production else 20)
postgres_backup_retention_days = _config_int("postgresBackupRetentionDays", 14 if is_production else 3)
postgres_deletion_protection = _config_bool("postgresDeletionProtection", is_production)
postgres_multi_az = _config_bool("postgresMultiAz", is_production)
retain_legacy_jobs_table = _config_bool("retainLegacyJobsTableForDeletionProtectionTransition", False)

nats_cpu = _config_int("natsCpu", 512)
nats_memory = _config_int("natsMemory", 1024)
jetstream_subject_prefix = config.get("jetstreamSubjectPrefix") or "events"
jetstream_stream_name = config.get("jetstreamStreamName") or "CEREBRO_EVENTS"
enable_jetstream_lag_probe = _config_bool("enableJetstreamLagProbe", True)
jetstream_lag_probe_interval_seconds = _config_int("jetstreamLagProbeIntervalSeconds", 60)
jetstream_lag_alarm_threshold = _config_int("jetstreamLagAlarmThreshold", 10000)

neo4j_database = config.get("neo4jDatabase")
neo4j_aura_enabled = _config_bool("neo4jAuraEnabled", False)
neo4j_aura_instance_id = config.get("neo4jAuraInstanceId") or ""
neo4j_aura_instance_name = config.get("neo4jAuraInstanceName") or f"cerebro-graphdb-{environment}-writer"
neo4j_aura_client_id = config.get_secret("neo4jAuraClientId")
neo4j_aura_client_secret = config.get_secret("neo4jAuraClientSecret")
neo4j_aura_project_id = config.get_secret("neo4jAuraProjectId")
neo4j_aura_password = config.get_secret("neo4jAuraPassword")
neo4j_aura_cloud_provider = config.get("neo4jAuraCloudProvider") or "gcp"
neo4j_aura_region = config.get("neo4jAuraRegion") or "us-central1"
neo4j_aura_memory = config.get("neo4jAuraMemory") or "8GB"
neo4j_aura_version = config.get("neo4jAuraVersion") or "5"
neo4j_aura_type = config.get("neo4jAuraType") or "professional-db"
neo4j_aura_vector_optimized = _config_bool("neo4jAuraVectorOptimized", True)
neo4j_secret_import_arns = config.get_object("neo4jSecretImportArns") or {}
api_keys = config.get_secret("apiKeys")
api_auth_enabled = _config_bool("apiAuthEnabled", is_production)
allowed_tenants = config.get_object("allowedTenants") or []
source_secret_keys = config.get_object("sourceSecretKeys") or []
source_runtimes = config.get_object("sourceRuntimes") or []
source_runtime_env_refs = _source_runtime_env_refs(source_runtimes)
source_secret_keys = _append_missing_source_secrets(source_secret_keys, source_runtime_env_refs)

# Optional IAM grants for S3-backed sources. Source configuration now lives in
# source runtimes, not process env; this only scopes task-role permissions.
s3_sources = config.get_object("s3Sources") or []
s3_source_iam_configs = []
for src in s3_sources:
    bucket = src.get("bucket")
    if not bucket:
        continue
    bucket_arn = src.get("bucketArn") or f"arn:aws:s3:::{bucket}"
    s3_source_iam_configs.append({
        "bucket_arn": bucket_arn,
        "prefixes": src.get("prefixes") or [],
        "role_arn": src.get("roleArn"),
    })

# =============================================================================
# KMS
# =============================================================================

kms_key = kms.create_kms_key(
    name=f"cerebro-{environment}",
    description="Cerebro runtime encryption key",
)

logs_kms_key = None
if enable_kms_log_encryption:
    logs_kms_key = kms.create_cloudwatch_logs_key(name=f"cerebro-{environment}")

if retain_legacy_jobs_table:
    legacy.retain_jobs_table_without_deletion_protection(
        name=f"cerebro-{environment}",
        kms_key_arn=kms_key["key_arn"],
    )

# =============================================================================
# NETWORKING
# =============================================================================

if use_existing_vpc and existing_vpc_id:
    vpc_cidr = existing_vpc_cidr
    alb_ingress_cidrs = (
        configured_alb_ingress_cidrs
        if configured_alb_ingress_cidrs is not None
        else ([vpc_cidr] if alb_internal else None)
    )
    vpc_stack = networking.use_existing_vpc(
        name=f"cerebro-{environment}",
        vpc_id=existing_vpc_id,
        public_subnet_ids=existing_public_subnet_ids,
        private_subnet_ids=existing_private_subnet_ids,
        alb_ingress_cidrs=alb_ingress_cidrs,
    )
else:
    vpc_cidr = "10.0.0.0/16"
    alb_ingress_cidrs = (
        configured_alb_ingress_cidrs
        if configured_alb_ingress_cidrs is not None
        else ([vpc_cidr] if alb_internal else None)
    )
    vpc_stack = networking.create_vpc(
        name=f"cerebro-{environment}",
        cidr_block=vpc_cidr,
        availability_zones=2,
        enable_nat_gateway=True,
        nat_gateway_per_az=nat_gateway_per_az,
        alb_ingress_cidrs=alb_ingress_cidrs,
        enable_flow_logs=True,
        flow_logs_retention_days=log_retention_days,
        flow_logs_kms_key_arn=logs_kms_key["key_arn"] if logs_kms_key else None,
    )

# =============================================================================
# RUNTIME BACKING SERVICES
# =============================================================================

postgres_stack = postgres.create_postgres(
    name=f"cerebro-{environment}",
    vpc_id=vpc_stack["vpc_id"],
    subnet_ids=vpc_stack["private_subnet_ids"],
    app_security_group_id=vpc_stack["app_security_group_id"],
    kms_key_arn=kms_key["key_arn"],
    secret_name=f"{external_secrets_prefix}/CEREBRO_POSTGRES_DSN",
    instance_class=postgres_instance_class,
    allocated_storage=postgres_allocated_storage,
    backup_retention_days=postgres_backup_retention_days,
    deletion_protection=postgres_deletion_protection,
    multi_az=postgres_multi_az,
)

nats_stack = nats.create_nats_service(
    name=f"cerebro-{environment}",
    vpc_id=vpc_stack["vpc_id"],
    subnet_ids=vpc_stack["private_subnet_ids"],
    app_security_group_id=vpc_stack["app_security_group_id"],
    kms_key_arn=kms_key["key_arn"],
    log_group_kms_key_id=logs_kms_key["key_arn"] if logs_kms_key else None,
    log_retention_days=log_retention_days,
    cpu=nats_cpu,
    memory=nats_memory,
    stream_name=jetstream_stream_name,
    subject_prefix=jetstream_subject_prefix,
    enable_lag_probe=enable_jetstream_lag_probe,
    lag_probe_interval_seconds=jetstream_lag_probe_interval_seconds,
)

neo4j_stack = None
neo4j_secret_stack = None
if neo4j_aura_enabled:
    if not all([neo4j_aura_client_id, neo4j_aura_client_secret, neo4j_aura_project_id]):
        raise ValueError("neo4jAuraClientId, neo4jAuraClientSecret, and neo4jAuraProjectId are required when neo4jAuraEnabled is true")

    neo4j_instance = neo4j.create_aura_instance(
        name=f"cerebro-{environment}",
        client_id=neo4j_aura_client_id,
        client_secret=neo4j_aura_client_secret,
        project_id=neo4j_aura_project_id,
        instance_name=neo4j_aura_instance_name,
        cloud_provider=neo4j_aura_cloud_provider,
        region=neo4j_aura_region,
        memory=neo4j_aura_memory,
        version=neo4j_aura_version,
        instance_type=neo4j_aura_type,
        vector_optimized=neo4j_aura_vector_optimized,
        import_instance_id=neo4j_aura_instance_id,
    )
    neo4j_stack = {"instance": neo4j_instance}

    if neo4j_aura_password is None:
        neo4j_aura_password = neo4j_instance.password

    neo4j_secret_stack = neo4j.create_runtime_secrets(
        name=f"cerebro-{environment}",
        external_secrets_prefix=external_secrets_prefix,
        neo4j_uri=neo4j_instance.connection_url,
        neo4j_password=neo4j_aura_password,
        api_keys=api_keys,
        kms_key_id=kms_key["key_arn"],
        import_arns=neo4j_secret_import_arns,
        tags={
            "ManagedBy": "Pulumi",
            "Environment": environment,
            "Service": "cerebro",
        },
    )

# =============================================================================
# LOAD BALANCER
# =============================================================================

certificate_stack = None
if certificate_domain:
    certificate_stack = cert.create_certificate(
        name=f"cerebro-{environment}",
        domain=certificate_domain,
        import_arn=certificate_import_arn,
        tags={
            "Environment": environment,
            "Service": "cerebro",
        },
    )

load_balancer_certificate_arn = None
if certificate_stack and certificate_domain == domain:
    load_balancer_certificate_arn = certificate_stack["certificate_arn"]

alb_stack = load_balancer.create_alb(
    name=f"cerebro-{environment}",
    vpc_id=vpc_stack["vpc_id"],
    subnet_ids=vpc_stack["private_subnet_ids"] if alb_internal else vpc_stack["public_subnet_ids"],
    security_group_id=vpc_stack["alb_security_group_id"],
    certificate_domain=domain or None,
    certificate_arn=load_balancer_certificate_arn,
    internal=alb_internal,
    health_check_path="/health",
    container_port=8080,
    enable_deletion_protection=enable_alb_deletion_protection,
    enable_access_logs=enable_alb_access_logs,
)

# =============================================================================
# ECS COMPUTE
# =============================================================================

secret_keys = [
    "CEREBRO_POSTGRES_DSN",
    "CEREBRO_NEO4J_URI",
    "CEREBRO_NEO4J_USERNAME",
    "CEREBRO_NEO4J_PASSWORD",
]
if api_auth_enabled:
    secret_keys.append("CEREBRO_API_KEYS")
    secret_keys.append({"name": "API_KEYS", "source": "CEREBRO_API_KEYS"})
secret_keys.extend(source_secret_keys)

app_environment = {
    "CEREBRO_HTTP_ADDR": ":8080",
    "CEREBRO_SHUTDOWN_TIMEOUT": config.get("shutdownTimeout") or "10s",
    "CEREBRO_API_AUTH_ENABLED": str(api_auth_enabled).lower(),
    "API_AUTH_ENABLED": str(api_auth_enabled).lower(),
    "CEREBRO_APPEND_LOG_DRIVER": "jetstream",
    "CEREBRO_JETSTREAM_URL": nats_stack["url"],
    "CEREBRO_JETSTREAM_SUBJECT_PREFIX": jetstream_subject_prefix,
    "CEREBRO_STATE_STORE_DRIVER": "postgres",
    "CEREBRO_GRAPH_STORE_DRIVER": "neo4j",
}
if not api_auth_enabled:
    app_environment["ALLOW_INSECURE_API"] = "true"
if neo4j_database:
    app_environment["CEREBRO_NEO4J_DATABASE"] = neo4j_database
if allowed_tenants:
    app_environment["CEREBRO_ALLOWED_TENANTS"] = ",".join(allowed_tenants)
    app_environment["ALLOWED_TENANTS"] = ",".join(allowed_tenants)
if source_runtime_env_refs:
    app_environment["CEREBRO_SOURCE_CONFIG_ENV_ALLOWLIST"] = ",".join(source_runtime_env_refs)

runtime_dependencies = [
    postgres_stack["secret_version"],
    nats_stack["service"],
]
if neo4j_secret_stack:
    runtime_dependencies.extend(neo4j_secret_stack["versions"])

ecs_stack = compute.create_ecs_cluster(
    name=f"cerebro-{environment}",
    vpc_id=vpc_stack["vpc_id"],
    subnet_ids=vpc_stack["private_subnet_ids"],
    security_group_id=vpc_stack["app_security_group_id"],
    kms_key_id=kms_key["key_id"],
    target_group_arn=alb_stack["target_group"].arn,
    container_image=container_image,
    api_cpu=api_cpu,
    api_memory=api_memory,
    api_min_instances=api_min_instances,
    api_max_instances=api_max_instances,
    log_retention_days=log_retention_days,
    environment=app_environment,
    secret_keys=secret_keys,
    external_secrets_prefix=external_secrets_prefix,
    log_group_kms_key_id=logs_kms_key["key_arn"] if logs_kms_key else None,
    s3_source_iam_configs=s3_source_iam_configs or None,
    depends_on=runtime_dependencies,
    orchestrator_enabled=orchestrator_enabled,
    orchestrator_schedule_expression=orchestrator_schedule_expression,
    orchestrator_cpu=orchestrator_cpu,
    orchestrator_memory=orchestrator_memory,
    orchestrator_command=orchestrator_command,
    orchestrator_task_count=orchestrator_task_count,
    orchestrator_schedules=orchestrator_schedules,
    source_runtimes=source_runtimes,
)

# =============================================================================
# MONITORING / EDGE
# =============================================================================

monitoring_stack = monitoring.create_monitoring(
    name=f"cerebro-{environment}",
    alb_arn_suffix=alb_stack["alb"].arn_suffix,
    target_group_arn_suffix=alb_stack["target_group"].arn_suffix,
    ecs_cluster_name=ecs_stack["cluster"].name,
    ecs_service_name=ecs_stack["api_service"].name,
    log_group_name=ecs_stack["log_group"].name,
    log_retention_days=log_retention_days,
    jetstream_stream_name=jetstream_stream_name,
    jetstream_lag_alarm_threshold=jetstream_lag_alarm_threshold,
)

waf_stack = None
if enable_waf:
    waf_stack = waf.create_waf(
        name=f"cerebro-{environment}",
        alb_arn=alb_stack["alb"].arn,
        rate_limit=2000,
        enable_logging=True,
        log_retention_days=log_retention_days,
        log_group_kms_key_id=logs_kms_key["key_arn"] if logs_kms_key else None,
    )

# =============================================================================
# TAILSCALE SUBNET ROUTER (optional)
# =============================================================================

tailscale_stack = None
if enable_tailscale:
    if not tailscale_advertise_routes:
        raise ValueError("cerebro:tailscaleAdvertiseRoutes must be configured when enableTailscale is true")

    tailscale_auth_key_secret_name = config.get("tailscaleAuthKeySecretName") or f"{external_secrets_prefix}/TAILSCALE_AUTH_KEY"
    tailscale_auth_key_secret = aws.secretsmanager.get_secret(name=tailscale_auth_key_secret_name)

    tailscale_stack = ts.create_tailscale_subnet_router(
        name=f"cerebro-{environment}",
        vpc_id=vpc_stack["vpc_id"],
        subnet_id=vpc_stack["private_subnet_ids"][0],
        advertise_routes=tailscale_advertise_routes,
        tailscale_hostname=tailscale_hostname,
        auth_key_secret_arn=tailscale_auth_key_secret.arn,
        kms_key_arn=kms_key["key_arn"],
    )

# =============================================================================
# INFISICAL / ECR
# =============================================================================

infisical_stack = None
if enable_infisical and infisical_principal_arn:
    infisical_stack = infisical.create_infisical_sync_role(
        name=f"cerebro-{environment}",
        assume_role_principal_arn=infisical_principal_arn,
        external_id=infisical_external_id,
        kms_key_arn=kms_key["key_arn"],
    )

repository = ecr.create_ecr_repository(
    name="cerebro",
    enable_immutable_tags=True,
    scan_on_push=True,
    lifecycle_policy_days=30,
    kms_key_arn=kms_key["key_arn"],
)

# =============================================================================
# OUTPUTS
# =============================================================================

pulumi.export("vpc_id", vpc_stack["vpc_id"])
pulumi.export("ecs_cluster_name", ecs_stack["cluster"].name)
pulumi.export("ecs_service_name", ecs_stack["api_service"].name)
if ecs_stack.get("orchestrator_task_definition"):
    pulumi.export("orchestrator_task_definition_arn", ecs_stack["orchestrator_task_definition"].arn)
if ecs_stack.get("orchestrator_task_definitions"):
    pulumi.export("orchestrator_task_definition_arns", [task.arn for task in ecs_stack["orchestrator_task_definitions"]])
if ecs_stack.get("orchestrator_rule"):
    pulumi.export("orchestrator_schedule_rule_name", ecs_stack["orchestrator_rule"].name)
if ecs_stack.get("orchestrator_rules"):
    pulumi.export("orchestrator_schedule_rule_names", [rule.name for rule in ecs_stack["orchestrator_rules"]])
pulumi.export("alb_dns_name", alb_stack["alb"].dns_name)
pulumi.export("api_url", pulumi.Output.concat("https://", domain) if domain else pulumi.Output.concat("http://", alb_stack["alb"].dns_name))
pulumi.export("kms_key_id", kms_key["key_id"])
pulumi.export("kms_key_alias", kms_key["alias"].name)
pulumi.export("postgres_endpoint", postgres_stack["instance"].address)
pulumi.export("postgres_secret_name", postgres_stack["secret"].name)
pulumi.export("nats_url", nats_stack["url"])
pulumi.export("jetstream_stream_name", nats_stack["stream_name"])
pulumi.export("jetstream_lag_probe_enabled", nats_stack["lag_probe_enabled"])
if neo4j_stack:
    pulumi.export("neo4j_instance_id", neo4j_stack["instance"].instance_id)
    pulumi.export("neo4j_connection_url", neo4j_stack["instance"].connection_url)
pulumi.export("ecr_repository_url", repository.repository_url)
pulumi.export("ecr_repository_arn", repository.arn)

if certificate_stack:
    pulumi.export("certificate_arn", certificate_stack["certificate_arn"])
    pulumi.export("certificate_validation_records", certificate_stack["validation_records"])
if waf_stack:
    pulumi.export("waf_web_acl_arn", waf_stack["web_acl"].arn)
if logs_kms_key:
    pulumi.export("logs_kms_key_arn", logs_kms_key["key_arn"])
if infisical_stack:
    pulumi.export("infisical_role_arn", infisical_stack["role_arn"])
if tailscale_stack:
    pulumi.export("tailscale_instance_id", tailscale_stack["instance_id"])
    pulumi.export("tailscale_private_ip", tailscale_stack["private_ip"])
