use std::collections::BTreeMap;
use std::io::Write;
use std::process::{Command, Stdio};

use crate::{ActionCatalog, ActionCatalogEntry, Error, Result};

#[derive(Clone, Debug, Eq, PartialEq)]
struct StringConstant {
    name: String,
    value: String,
}

pub fn render_catalog(catalog: &ActionCatalog) -> Result<Vec<u8>> {
    let mut output = String::new();
    output.push_str("// Code generated by make graph-action-generate; DO NOT EDIT.\n\n");
    output.push_str("package graphactions\n\n");
    write_string_constants(
        &mut output,
        "Action IDs",
        &action_constants(&catalog.actions),
    );
    write_string_constants(
        &mut output,
        "Target kinds",
        &target_kind_constants(&catalog.actions),
    );
    write_string_slice(
        &mut output,
        "generatedActionIDs",
        &action_constants(&catalog.actions),
    );
    write_string_slice(
        &mut output,
        "generatedProviderIDs",
        &provider_constants(&catalog.actions),
    );
    write_string_slice(
        &mut output,
        "generatedTargetKinds",
        &target_kind_constants(&catalog.actions),
    );
    output.push_str(
        "func DefaultRegistry() Registry {\n\
\tactions := make(map[string]ActionSpec, len(generatedActionSpecs))\n\
\tfor _, spec := range generatedActionSpecs {\n\
\t\tactions[spec.ID] = spec\n\
\t}\n\
\treturn Registry{actions: actions}\n\
}\n\n\
func KnownActionSpecs() []ActionSpec {\n\
\tout := make([]ActionSpec, len(generatedActionSpecs))\n\
\tcopy(out, generatedActionSpecs)\n\
\treturn out\n\
}\n\n\
func KnownActionMetadata() []ActionMetadata {\n\
\tout := make([]ActionMetadata, 0, len(generatedActionSpecs))\n\
\tfor _, spec := range generatedActionSpecs {\n\
\t\tout = append(out, spec.Metadata())\n\
\t}\n\
\treturn out\n\
}\n\n\
func KnownActionIDs() []string {\n\
\tout := make([]string, len(generatedActionIDs))\n\
\tcopy(out, generatedActionIDs)\n\
\treturn out\n\
}\n\n\
func KnownProviderIDs() []string {\n\
\tout := make([]string, len(generatedProviderIDs))\n\
\tcopy(out, generatedProviderIDs)\n\
\treturn out\n\
}\n\n\
func KnownTargetKinds() []string {\n\
\tout := make([]string, len(generatedTargetKinds))\n\
\tcopy(out, generatedTargetKinds)\n\
\treturn out\n\
}\n\n\
var generatedActionSpecs = []ActionSpec{\n",
    );
    for action in &catalog.actions {
        output.push_str("\t{\n");
        output.push_str(&format!("\t\tID: {},\n", action.const_name));
        output.push_str(&format!("\t\tProvider: {},\n", action.provider_const));
        output.push_str(&format!(
            "\t\tProviderAction: {},\n",
            action.provider_action_const
        ));
        output.push_str(&format!("\t\tTargetKind: {},\n", action.target_kind_const));
        output.push_str(&format!("\t\tEffect: {},\n", go_quote(&action.effect)?));
        output.push_str(&format!("\t\tDestructive: {},\n", action.destructive));
        output.push_str(&format!(
            "\t\tReversibleBy: {},\n",
            go_quote(&action.reversible_by)?
        ));
        output.push_str(&format!("\t\tResolveTarget: {},\n", action.target_resolver));
        output.push_str(&format!(
            "\t\tCheckEligibility: {},\n",
            action.eligibility_checker
        ));
        output.push_str("\t},\n");
    }
    output.push_str("}\n");
    gofmt(output.as_bytes())
}

fn go_quote(value: &str) -> Result<String> {
    serde_json::to_string(value).map_err(Error::Json)
}

fn gofmt(content: &[u8]) -> Result<Vec<u8>> {
    let mut child = Command::new("gofmt")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|source| Error::Formatter {
            operation: "start",
            source,
        })?;
    child
        .stdin
        .take()
        .ok_or(Error::FormatterInputUnavailable)?
        .write_all(content)
        .map_err(|source| Error::Formatter {
            operation: "write input to",
            source,
        })?;
    let result = child
        .wait_with_output()
        .map_err(|source| Error::Formatter {
            operation: "wait for",
            source,
        })?;
    if !result.status.success() {
        return Err(Error::FormatterFailed {
            stderr: String::from_utf8_lossy(&result.stderr).trim().to_owned(),
        });
    }
    Ok(result.stdout)
}

fn action_constants(actions: &[ActionCatalogEntry]) -> Vec<StringConstant> {
    actions
        .iter()
        .map(|action| StringConstant {
            name: action.const_name.clone(),
            value: action.id.clone(),
        })
        .collect()
}

fn provider_constants(actions: &[ActionCatalogEntry]) -> Vec<StringConstant> {
    let values: BTreeMap<_, _> = actions
        .iter()
        .map(|action| (action.provider_const.clone(), action.provider.clone()))
        .collect();
    values
        .into_iter()
        .map(|(name, value)| StringConstant { name, value })
        .collect()
}

fn target_kind_constants(actions: &[ActionCatalogEntry]) -> Vec<StringConstant> {
    let values: BTreeMap<_, _> = actions
        .iter()
        .map(|action| (action.target_kind_const.clone(), action.target_kind.clone()))
        .collect();
    values
        .into_iter()
        .map(|(name, value)| StringConstant { name, value })
        .collect()
}

fn write_string_constants(output: &mut String, title: &str, constants: &[StringConstant]) {
    if constants.is_empty() {
        return;
    }
    output.push_str(&format!("// {title}.\nconst (\n"));
    for constant in constants {
        output.push_str(&format!(
            "\t{} = {}\n",
            constant.name,
            serde_json::to_string(&constant.value).expect("string serialization cannot fail")
        ));
    }
    output.push_str(")\n\n");
}

fn write_string_slice(output: &mut String, name: &str, constants: &[StringConstant]) {
    if constants.is_empty() {
        return;
    }
    output.push_str(&format!("var {name} = []string{{\n"));
    for constant in constants {
        output.push_str(&format!("\t{},\n", constant.name));
    }
    output.push_str("}\n\n");
}
