use crate::{ActionCatalog, Result, definition_digest};

pub fn render_rust_catalog(catalog: &ActionCatalog) -> Result<Vec<u8>> {
    let mut output = String::new();
    output.push_str("// Code generated by make graph-action-generate; DO NOT EDIT.\n\n");
    output.push_str("use crate::ActionDefinition;\n\n");
    output.push_str("pub(crate) const ACTION_DEFINITIONS: &[ActionDefinition<'static>] = &[\n");
    for action in &catalog.actions {
        output.push_str("    ActionDefinition {\n");
        field(&mut output, "id", &action.id);
        field(&mut output, "provider", &action.provider);
        field(&mut output, "provider_action", &action.provider_action);
        field(&mut output, "target_kind", &action.target_kind);
        field(&mut output, "effect", &action.effect);
        output.push_str(&format!("        destructive: {},\n", action.destructive));
        field(&mut output, "reversible_by", &action.reversible_by);
        field(
            &mut output,
            "definition_digest",
            &definition_digest(action)?,
        );
        output.push_str("    },\n");
    }
    output.push_str("];\n");
    Ok(output.into_bytes())
}

fn field(output: &mut String, name: &str, value: &str) {
    output.push_str(&format!("        {name}: {value:?},\n"));
}
