// Code generated by tools/agentlifecyclegen from the LifecycleEventV1 JSON Schema. DO NOT EDIT.

package lifecyclecontract

import "encoding/json"

// LifecycleEventV1 Cloud- and interaction-surface-neutral lifecycle events for deployments, service availability, durable work, capability compatibility, delivery, installation, and migration.
type LifecycleEventV1 struct {
	Capabilities       *Capabilities       `json:"capabilities,omitempty"`
	CausationID        *Identifier         `json:"causation_id,omitempty"`
	CheckpointRef      *Reference          `json:"checkpoint_ref,omitempty"`
	CorrelationID      *Identifier         `json:"correlation_id,omitempty"`
	DeliveryReceiptRef *Reference          `json:"delivery_receipt_ref,omitempty"`
	Deployment         *DeploymentIdentity `json:"deployment,omitempty"`
	Diagnostics        map[string]string   `json:"diagnostics,omitempty"`
	DrainDeadline      *Timestamp          `json:"drain_deadline,omitempty"`
	EffectReceiptRef   *Reference          `json:"effect_receipt_ref,omitempty"`
	EventID            Identifier          `json:"event_id"`
	EventKind          string              `json:"event_kind"`
	IdempotencyKey     string              `json:"idempotency_key"`
	Interaction        *Interaction        `json:"interaction,omitempty"`
	Lease              *Lease              `json:"lease,omitempty"`
	ObservedAt         Timestamp           `json:"observed_at"`
	OccurredAt         Timestamp           `json:"occurred_at"`
	Producer           Producer            `json:"producer"`
	Reason             Reason              `json:"reason"`
	SchemaVersion      string              `json:"schema_version"`
	Scope              Scope               `json:"scope"`
	Sequence           int64               `json:"sequence"`
	SnapshotRef        *Reference          `json:"snapshot_ref,omitempty"`
	TraceID            *string             `json:"trace_id,omitempty"`
	Transition         json.RawMessage     `json:"transition"`
}

// Capabilities Capabilities is part of the AgentServiceLifecycle contract.
type Capabilities struct {
	ContractVersions map[string]string `json:"contract_versions,omitempty"`
	ManifestDigest   string            `json:"manifest_digest"`
	Missing          CapabilityIDs     `json:"missing"`
	Required         CapabilityIDs     `json:"required"`
	Supported        CapabilityIDs     `json:"supported"`
}

// CapabilityDecision CapabilityDecision is part of the AgentServiceLifecycle contract.
type CapabilityDecision struct {
	Axis     string `json:"axis"`
	Decision string `json:"decision"`
}

// CapabilityIDs CapabilityIDs is part of the AgentServiceLifecycle contract.
type CapabilityIDs []Identifier

// DeliveryState DeliveryState is part of the AgentServiceLifecycle contract.
type DeliveryState string

const (
	DeliveryStatePlanned    DeliveryState = "planned"
	DeliveryStatePending    DeliveryState = "pending"
	DeliveryStateDelivering DeliveryState = "delivering"
	DeliveryStateDelivered  DeliveryState = "delivered"
	DeliveryStatePaused     DeliveryState = "paused"
	DeliveryStateFailed     DeliveryState = "failed"
	DeliveryStateAbandoned  DeliveryState = "abandoned"
)

// DeliveryTransition DeliveryTransition is part of the AgentServiceLifecycle contract.
type DeliveryTransition struct {
	Attempt int64          `json:"attempt"`
	Axis    string         `json:"axis"`
	From    *DeliveryState `json:"from"`
	PartID  Identifier     `json:"part_id"`
	To      DeliveryState  `json:"to"`
}

// DeploymentIdentity DeploymentIdentity is part of the AgentServiceLifecycle contract.
type DeploymentIdentity struct {
	ArtifactDigest  string      `json:"artifact_digest"`
	DeploymentID    Identifier  `json:"deployment_id"`
	Generation      int64       `json:"generation"`
	InstanceID      *Identifier `json:"instance_id,omitempty"`
	RouteGeneration *int64      `json:"route_generation,omitempty"`
	Version         string      `json:"version"`
}

// DeploymentState DeploymentState is part of the AgentServiceLifecycle contract.
type DeploymentState string

const (
	DeploymentStateProposed     DeploymentState = "proposed"
	DeploymentStateProvisioning DeploymentState = "provisioning"
	DeploymentStateValidating   DeploymentState = "validating"
	DeploymentStateActive       DeploymentState = "active"
	DeploymentStateFailed       DeploymentState = "failed"
	DeploymentStateRolledBack   DeploymentState = "rolled_back"
	DeploymentStateSuperseded   DeploymentState = "superseded"
	DeploymentStateRetired      DeploymentState = "retired"
)

// DeploymentTransition DeploymentTransition is part of the AgentServiceLifecycle contract.
type DeploymentTransition struct {
	Axis string           `json:"axis"`
	From *DeploymentState `json:"from"`
	To   DeploymentState  `json:"to"`
}

// Identifier Identifier is part of the AgentServiceLifecycle contract.
type Identifier string

// InstallationState InstallationState is part of the AgentServiceLifecycle contract.
type InstallationState string

const (
	InstallationStateAuthorizing InstallationState = "authorizing"
	InstallationStateBinding     InstallationState = "binding"
	InstallationStateVerifying   InstallationState = "verifying"
	InstallationStateActive      InstallationState = "active"
	InstallationStateSuspended   InstallationState = "suspended"
	InstallationStateRevoked     InstallationState = "revoked"
	InstallationStateRetired     InstallationState = "retired"
)

// InstallationTransition InstallationTransition is part of the AgentServiceLifecycle contract.
type InstallationTransition struct {
	Axis string             `json:"axis"`
	From *InstallationState `json:"from"`
	To   InstallationState  `json:"to"`
}

// Interaction Interaction is part of the AgentServiceLifecycle contract.
type Interaction struct {
	ActorID        *Identifier `json:"actor_id,omitempty"`
	ConversationID Identifier  `json:"conversation_id"`
	MessageID      *Identifier `json:"message_id,omitempty"`
	Surface        Identifier  `json:"surface"`
	ThreadID       *Identifier `json:"thread_id,omitempty"`
	WorkspaceID    *Identifier `json:"workspace_id,omitempty"`
}

// Lease Lease is part of the AgentServiceLifecycle contract.
type Lease struct {
	AcquiredAt   Timestamp  `json:"acquired_at"`
	ExpiresAt    Timestamp  `json:"expires_at"`
	FencingToken int64      `json:"fencing_token"`
	Generation   int64      `json:"generation"`
	HeartbeatAt  *Timestamp `json:"heartbeat_at,omitempty"`
	LeaseID      Identifier `json:"lease_id"`
	OwnerID      Identifier `json:"owner_id"`
}

// MigrationState MigrationState is part of the AgentServiceLifecycle contract.
type MigrationState string

const (
	MigrationStatePlanned        MigrationState = "planned"
	MigrationStateValidating     MigrationState = "validating"
	MigrationStateShadowing      MigrationState = "shadowing"
	MigrationStateDrainingSource MigrationState = "draining_source"
	MigrationStateCutover        MigrationState = "cutover"
	MigrationStateReconciling    MigrationState = "reconciling"
	MigrationStateVerified       MigrationState = "verified"
	MigrationStateRollingBack    MigrationState = "rolling_back"
	MigrationStateRolledBack     MigrationState = "rolled_back"
	MigrationStateFailed         MigrationState = "failed"
)

// MigrationTransition MigrationTransition is part of the AgentServiceLifecycle contract.
type MigrationTransition struct {
	Axis string          `json:"axis"`
	From *MigrationState `json:"from"`
	To   MigrationState  `json:"to"`
}

// Producer Producer is part of the AgentServiceLifecycle contract.
type Producer struct {
	Component  Identifier  `json:"component"`
	InstanceID *Identifier `json:"instance_id,omitempty"`
	Version    string      `json:"version"`
}

// Reason Reason is part of the AgentServiceLifecycle contract.
type Reason struct {
	Code           string  `json:"code"`
	OperatorAction *string `json:"operator_action,omitempty"`
	Retryable      *bool   `json:"retryable,omitempty"`
	Summary        string  `json:"summary"`
}

// Reference Reference is part of the AgentServiceLifecycle contract.
type Reference string

// Scope Scope is part of the AgentServiceLifecycle contract.
type Scope struct {
	InstallationID *Identifier `json:"installation_id,omitempty"`
	ServiceID      Identifier  `json:"service_id"`
	SubjectID      Identifier  `json:"subject_id"`
	SubjectType    *string     `json:"subject_type,omitempty"`
	TenantID       Identifier  `json:"tenant_id"`
}

// ServiceState ServiceState is part of the AgentServiceLifecycle contract.
type ServiceState string

const (
	ServiceStateBooting    ServiceState = "booting"
	ServiceStateWarming    ServiceState = "warming"
	ServiceStateReady      ServiceState = "ready"
	ServiceStateDegraded   ServiceState = "degraded"
	ServiceStateDraining   ServiceState = "draining"
	ServiceStateOffline    ServiceState = "offline"
	ServiceStateRecovering ServiceState = "recovering"
	ServiceStateStopped    ServiceState = "stopped"
)

// ServiceTransition ServiceTransition is part of the AgentServiceLifecycle contract.
type ServiceTransition struct {
	Axis string        `json:"axis"`
	From *ServiceState `json:"from"`
	To   ServiceState  `json:"to"`
}

// Timestamp Timestamp is part of the AgentServiceLifecycle contract.
type Timestamp string

// WorkState WorkState is part of the AgentServiceLifecycle contract.
type WorkState string

const (
	WorkStateReceived   WorkState = "received"
	WorkStateAdmitted   WorkState = "admitted"
	WorkStateQueued     WorkState = "queued"
	WorkStateLeased     WorkState = "leased"
	WorkStateRunning    WorkState = "running"
	WorkStateWaiting    WorkState = "waiting"
	WorkStatePaused     WorkState = "paused"
	WorkStateDelivering WorkState = "delivering"
	WorkStateCompleted  WorkState = "completed"
	WorkStateBlocked    WorkState = "blocked"
	WorkStateCancelled  WorkState = "cancelled"
	WorkStateExpired    WorkState = "expired"
	WorkStateRejected   WorkState = "rejected"
)

// WorkTransition WorkTransition is part of the AgentServiceLifecycle contract.
type WorkTransition struct {
	Attempt int64      `json:"attempt"`
	Axis    string     `json:"axis"`
	From    *WorkState `json:"from"`
	To      WorkState  `json:"to"`
}
