package archtests

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRetiredGeneratedSourceArtifactsDoNotReturn(t *testing.T) {
	root := repoRoot(t)
	sourceRoot := filepath.Join(root, "sources")
	entries, err := os.ReadDir(sourceRoot)
	if err != nil {
		t.Fatalf("ReadDir(sources): %v", err)
	}
	for _, entry := range entries {
		if !entry.IsDir() || entry.Name() == "internal" {
			continue
		}
		sourceDir := filepath.Join(sourceRoot, entry.Name())
		for _, retired := range []string{"PR_BODY.md", "SOURCE_RUNTIME.md", "source_health_receipt.json"} {
			path := filepath.Join(sourceDir, retired)
			if _, err := os.Stat(path); err == nil {
				t.Fatalf("sources/%s/%s is retired; derive this artifact from the connector catalog instead", entry.Name(), retired)
			} else if !os.IsNotExist(err) {
				t.Fatalf("stat sources/%s/%s: %v", entry.Name(), retired, err)
			}
		}
		fixturePath := filepath.Join(sourceDir, "fixture.go")
		body, err := os.ReadFile(fixturePath)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			t.Fatalf("read sources/%s/fixture.go: %v", entry.Name(), err)
		}
		if strings.Contains(string(body), "Code generated by sourcegen") {
			t.Fatalf("sources/%s/fixture.go is a retired generated adapter; use sourcefixture.NewCatalogSource", entry.Name())
		}
	}
}
