apiVersion: cerebro.writer.com/v1alpha1
kind: PolicyFindingRule
metadata:
    id: vm-empty-password
    name: Internal VM with a local user that has an empty password
    description: A virtual machine has a local user account with an empty password
    lastModified: "0001-01-01T00:00:00Z"
    tags:
        - wiz
        - compute
        - password
        - authentication
spec:
    severity: critical
    effect: forbid
    resource: compute::instance
    match:
        conditions:
            - list_value(path(resource, "local_users")).exists(item, cmp_eq(path(item, "password_empty"), true))
        conditionFormat: cel
    remediation:
        summary: Set strong passwords for all local users. Disable unused accounts. Consider using centralized authentication.
    riskCategories:
        - IDENTITY_RISK
    frameworks:
        - name: NIST 800-53 r5
          controls:
            - IA-2
            - IA-5
        - name: PCI DSS v4.0.1
          controls:
            - "8.3"
            - "8.4"
        - name: CIS Controls v8
          controls:
            - "6"
    mitreAttack:
        - tactic: Persistence
          technique: T1098
        - tactic: Credential Access
          technique: T1552
