# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerebro/v1/source.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'cerebro/v1/source.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63\x65rebro/v1/source.proto\x12\ncerebro.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n\nSourceSpec\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12 \n\x0b\x64\x65scription\x18\x03 \x01(\tR\x0b\x64\x65scription\x12#\n\remitted_kinds\x18\x04 \x03(\tR\x0c\x65mittedKinds\"&\n\x0cSourceCursor\x12\x16\n\x06opaque\x18\x01 \x01(\tR\x06opaque\"q\n\x10SourceCheckpoint\x12\x38\n\twatermark\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\twatermark\x12#\n\rcursor_opaque\x18\x02 \x01(\tR\x0c\x63ursorOpaqueB4Z2github.com/writer/cerebro/gen/cerebro/v1;cerebrov1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerebro.v1.source_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/writer/cerebro/gen/cerebro/v1;cerebrov1'
  _globals['_SOURCESPEC']._serialized_start=72
  _globals['_SOURCESPEC']._serialized_end=191
  _globals['_SOURCECURSOR']._serialized_start=193
  _globals['_SOURCECURSOR']._serialized_end=231
  _globals['_SOURCECHECKPOINT']._serialized_start=233
  _globals['_SOURCECHECKPOINT']._serialized_end=346
# @@protoc_insertion_point(module_scope)
