# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cerebro/v1/tool.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'cerebro/v1/tool.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63\x65rebro/v1/tool.proto\x12\ncerebro.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x03\n\x10ToolRegistration\x12\x1b\n\ttool_name\x18\x01 \x01(\tR\x08toolName\x12\x18\n\x07service\x18\x02 \x01(\tR\x07service\x12\x1a\n\x08\x65ndpoint\x18\x03 \x01(\tR\x08\x65ndpoint\x12\x18\n\x07version\x18\x04 \x01(\tR\x07version\x12\"\n\x0c\x63\x61pabilities\x18\x05 \x03(\tR\x0c\x63\x61pabilities\x12!\n\x0coauth_scopes\x18\x06 \x03(\tR\x0boauthScopes\x12L\n\nattributes\x18\x07 \x03(\x0b\x32,.cerebro.v1.ToolRegistration.AttributesEntryR\nattributes\x12?\n\rregistered_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0cregisteredAt\x1a=\n\x0f\x41ttributesEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"\xa8\x03\n\nToolHealth\x12\x1b\n\ttool_name\x18\x01 \x01(\tR\x08toolName\x12\x18\n\x07service\x18\x02 \x01(\tR\x07service\x12\x1a\n\x08\x65ndpoint\x18\x03 \x01(\tR\x08\x65ndpoint\x12\x18\n\x07version\x18\x04 \x01(\tR\x07version\x12\x34\n\x06status\x18\x05 \x01(\x0e\x32\x1c.cerebro.v1.ToolHealthStatusR\x06status\x12\x16\n\x06\x64\x65tail\x18\x06 \x01(\tR\x06\x64\x65tail\x12\x1d\n\nlatency_ms\x18\x07 \x01(\x03R\tlatencyMs\x12\x39\n\nchecked_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcheckedAt\x12\x46\n\nattributes\x18\t \x03(\x0b\x32&.cerebro.v1.ToolHealth.AttributesEntryR\nattributes\x1a=\n\x0f\x41ttributesEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01*\x99\x01\n\x10ToolHealthStatus\x12\"\n\x1eTOOL_HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n\x1aTOOL_HEALTH_STATUS_HEALTHY\x10\x01\x12\x1f\n\x1bTOOL_HEALTH_STATUS_DEGRADED\x10\x02\x12 \n\x1cTOOL_HEALTH_STATUS_UNHEALTHY\x10\x03\x42\x34Z2github.com/writer/cerebro/gen/cerebro/v1;cerebrov1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cerebro.v1.tool_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/writer/cerebro/gen/cerebro/v1;cerebrov1'
  _globals['_TOOLREGISTRATION_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_TOOLREGISTRATION_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_TOOLHEALTH_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_TOOLHEALTH_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_TOOLHEALTHSTATUS']._serialized_start=905
  _globals['_TOOLHEALTHSTATUS']._serialized_end=1058
  _globals['_TOOLREGISTRATION']._serialized_start=71
  _globals['_TOOLREGISTRATION']._serialized_end=475
  _globals['_TOOLREGISTRATION_ATTRIBUTESENTRY']._serialized_start=414
  _globals['_TOOLREGISTRATION_ATTRIBUTESENTRY']._serialized_end=475
  _globals['_TOOLHEALTH']._serialized_start=478
  _globals['_TOOLHEALTH']._serialized_end=902
  _globals['_TOOLHEALTH_ATTRIBUTESENTRY']._serialized_start=414
  _globals['_TOOLHEALTH_ATTRIBUTESENTRY']._serialized_end=475
# @@protoc_insertion_point(module_scope)
