package findings

import (
	"context"
	"fmt"
	"regexp"
	"strings"
	"time"

	cerebrov1 "github.com/writer/cerebro/gen/cerebro/v1"
	"github.com/writer/cerebro/internal/ports"
	"github.com/writer/cerebro/internal/workflowevents"
)

const (
	panopticonThreatHuntActionType   = "panopticon-threat-hunt"
	panopticonThreatHuntInsightType  = "threat_hunt"
	panopticonThreatHuntSourceSystem = "findings"
)

var cveIDPattern = regexp.MustCompile(`(?i)\bCVE-\d{4}-\d{4,}\b`)

func (s *Service) projectFindingNewActionRecommendations(ctx context.Context, finding *ports.FindingRecord) error {
	if s == nil || s.graph == nil || finding == nil {
		return nil
	}
	event, err := panopticonThreatHuntActionEvent(finding)
	if err != nil || event == nil {
		return err
	}
	return s.recordAndProjectWorkflowEvent(ctx, event)
}

func panopticonThreatHuntActionEvent(finding *ports.FindingRecord) (*cerebrov1.EventEnvelope, error) {
	if !panopticonThreatHuntEligibleFinding(finding) {
		return nil, nil
	}
	cveID := panopticonThreatHuntCVEID(finding)
	if cveID == "" {
		return nil, nil
	}
	tenantID := strings.TrimSpace(finding.TenantID)
	if tenantID == "" {
		return nil, nil
	}
	observedAt := finding.LastObservedAt.UTC()
	if observedAt.IsZero() {
		observedAt = finding.FirstObservedAt.UTC()
	}
	if observedAt.IsZero() {
		observedAt = time.Now().UTC()
	}
	findingURN := findingGraphFindingURN(tenantID, finding)
	assetURN := firstNonEmpty(strings.TrimSpace(finding.Attributes["asset_urn"]), findingPrimaryResourceURN(finding))
	actionID := workflowevents.CanonicalWorkflowID(
		tenantID,
		"action",
		"panopticon-threat-hunt-"+strings.TrimSpace(finding.ID)+"-"+cveID,
		panopticonThreatHuntActionType,
		[]string{findingURN},
		time.Time{},
	)
	summaryTarget := firstNonEmpty(strings.TrimSpace(finding.Attributes["target"]), strings.TrimSpace(finding.Attributes["asset_host"]), assetURN, "the affected asset")
	return workflowevents.NewActionRecordedEvent(workflowevents.ActionRecorded{
		TenantID:         tenantID,
		ActionID:         actionID,
		ActionType:       panopticonThreatHuntActionType,
		Status:           "requested",
		RecommendationID: "vulnview-ioc-threat-hunt:" + cveID,
		InsightType:      panopticonThreatHuntInsightType,
		Title:            "Start Panopticon threat hunt for " + cveID,
		Summary:          fmt.Sprintf("VulnView reported %s on %s; resolve related IOCs and run SOC threat-hunt correlation in Panopticon.", cveID, summaryTarget),
		TargetIDs:        []string{findingURN},
		SourceSystem:     panopticonThreatHuntSourceSystem,
		SourceEventID:    strings.TrimSpace(finding.ID),
		ObservedAt:       observedAt.Format(time.RFC3339Nano),
		ValidFrom:        observedAt.Format(time.RFC3339Nano),
		AutoGenerated:    true,
		Metadata: map[string]any{
			"asset_urn":               assetURN,
			"cve_id":                  cveID,
			"event_id":                strings.TrimSpace(finding.Attributes["event_id"]),
			"event_kind":              strings.TrimSpace(finding.Attributes["event_kind"]),
			"finding_id":              strings.TrimSpace(finding.ID),
			"handoff_target":          "panopticon",
			"hunt_type":               "vulnview_cve_ioc_correlation",
			"ioc_lookup_required":     true,
			"panopticon_orchestrator": "soc-planner",
			"rule_id":                 strings.TrimSpace(finding.RuleID),
			"severity":                strings.TrimSpace(finding.Severity),
			"source_runtime_id":       strings.TrimSpace(finding.RuntimeID),
			"template_id":             strings.TrimSpace(finding.Attributes["template_id"]),
		},
	})
}

func panopticonThreatHuntEligibleFinding(finding *ports.FindingRecord) bool {
	if finding == nil || finding.Attributes == nil {
		return false
	}
	if !strings.EqualFold(strings.TrimSpace(finding.RuleID), vulnViewActionableExternalFindingRuleID) {
		return false
	}
	if strings.TrimSpace(finding.ID) == "" || !strings.EqualFold(strings.TrimSpace(finding.Status), findingStatusOpen) {
		return false
	}
	if eventKind := strings.TrimSpace(finding.Attributes["event_kind"]); eventKind != "" && !strings.EqualFold(eventKind, "vulnview.vulnerability") {
		return false
	}
	return true
}

func panopticonThreatHuntCVEID(finding *ports.FindingRecord) string {
	if finding == nil {
		return ""
	}
	for _, value := range []string{
		finding.PolicyID,
		finding.PolicyName,
		finding.Summary,
		finding.Attributes["template_id"],
		finding.Attributes["vulnerability_id"],
		finding.Attributes["name"],
		finding.Attributes["external_id"],
	} {
		if match := cveIDPattern.FindString(value); match != "" {
			return strings.ToUpper(match)
		}
	}
	return ""
}
