// Code generated by make graph-action-generate; DO NOT EDIT.

package graphactions

// Action IDs.
const (
	ActionIdentityOktaSuspendUser     = "identity.okta.suspend_user"
	ActionIdentityOktaUnsuspendUser   = "identity.okta.unsuspend_user"
	ActionEndpointCerebroRevokeDevice = "endpoint.cerebro.revoke_device"
)

// Target kinds.
const (
	TargetKindCerebroDevice = "endpoint.cerebro.device"
	TargetKindOktaUser      = "identity.okta.user"
)

var generatedActionIDs = []string{
	ActionIdentityOktaSuspendUser,
	ActionIdentityOktaUnsuspendUser,
	ActionEndpointCerebroRevokeDevice,
}

var generatedProviderIDs = []string{
	ProviderAccessApprovals,
	ProviderCerebroDeviceAuth,
}

var generatedTargetKinds = []string{
	TargetKindCerebroDevice,
	TargetKindOktaUser,
}

func DefaultRegistry() Registry {
	actions := make(map[string]ActionSpec, len(generatedActionSpecs))
	for _, spec := range generatedActionSpecs {
		actions[spec.ID] = spec
	}
	return Registry{actions: actions}
}

func KnownActionSpecs() []ActionSpec {
	out := make([]ActionSpec, len(generatedActionSpecs))
	copy(out, generatedActionSpecs)
	return out
}

func KnownActionMetadata() []ActionMetadata {
	out := make([]ActionMetadata, 0, len(generatedActionSpecs))
	for _, spec := range generatedActionSpecs {
		out = append(out, spec.Metadata())
	}
	return out
}

func KnownActionIDs() []string {
	out := make([]string, len(generatedActionIDs))
	copy(out, generatedActionIDs)
	return out
}

func KnownProviderIDs() []string {
	out := make([]string, len(generatedProviderIDs))
	copy(out, generatedProviderIDs)
	return out
}

func KnownTargetKinds() []string {
	out := make([]string, len(generatedTargetKinds))
	copy(out, generatedTargetKinds)
	return out
}

var generatedActionSpecs = []ActionSpec{
	{
		ID:               ActionIdentityOktaSuspendUser,
		DefinitionDigest: "8786cfc15b5984021508b1ff90e9693e9d305e1b58e33a10760baddefde9871f",
		Provider:         ProviderAccessApprovals,
		ProviderAction:   AccessApprovalsActionSuspend,
		TargetKind:       TargetKindOktaUser,
		Effect:           "deny_access",
		Destructive:      true,
		ReversibleBy:     "identity.okta.unsuspend_user",
		ResolveTarget:    OktaUserTargetForFinding,
		CheckEligibility: FindingAllowsAction,
	},
	{
		ID:               ActionIdentityOktaUnsuspendUser,
		DefinitionDigest: "492f24f7b5fdf5679777201441ea963a54357d3f658359e2f554130e7797e605",
		Provider:         ProviderAccessApprovals,
		ProviderAction:   AccessApprovalsActionUnsuspend,
		TargetKind:       TargetKindOktaUser,
		Effect:           "restore_access",
		Destructive:      false,
		ReversibleBy:     "identity.okta.suspend_user",
		ResolveTarget:    OktaUserTargetForFinding,
		CheckEligibility: FindingAllowsAction,
	},
	{
		ID:               ActionEndpointCerebroRevokeDevice,
		DefinitionDigest: "bfe050dbcc8e237d27996d459c12185f94ee9f4a857e6286f87455536d6a9bb8",
		Provider:         ProviderCerebroDeviceAuth,
		ProviderAction:   CerebroDeviceActionRevoke,
		TargetKind:       TargetKindCerebroDevice,
		Effect:           "deny_device_access",
		Destructive:      true,
		ReversibleBy:     "",
		ResolveTarget:    CerebroDeviceTargetForFinding,
		CheckEligibility: FindingAllowsAction,
	},
}
