package kolide

import "github.com/writer/cerebro/sources/internal/jsonapi"

// families returns the Kolide family configurations for all supported
// resource types (devices, checks, issues, software, user-devices,
// vulnerabilities).
func families() []jsonapi.Family {
	return []jsonapi.Family{
		{
			Name:           familyDevice,
			Path:           "/devices",
			PageSizeParams: []string{"per_page"},
			URNKind:        "kolide_device",
			IDKeys:         []string{"id", "device_id", "hardware_uuid", "uuid", "serial", "serial_number", "hardware.serial"},
			TimestampKeys: []string{
				"updated_at", "last_seen_at", "last_authenticated_at", "registered_at", "last_seen", "last_check_in", "lastCheckIn",
			},
			Attributes: map[string]string{
				"device_id":             "id|device_id",
				"device_uuid":           "hardware_uuid|uuid",
				"device_name":           "name",
				"hostname":              "hostname|name",
				"serial_number":         "serial|serial_number",
				"hardware_serial":       "serial|hardware.serial",
				"platform":              "device_type|platform",
				"form_factor":           "form_factor",
				"os":                    "operating_system|os.name|os",
				"os_name":               "operating_system|os.name",
				"os_version":            "os.version",
				"status":                "status",
				"auth_state":            "auth_state",
				"authentication_mode":   "auth_configuration.authentication_mode",
				"registered_at":         "registered_at",
				"last_authenticated_at": "last_authenticated_at",
				"will_block_at":         "will_block_at",
				"compliance_status":     "compliance_status|auth_state",
				"failure_count":         "failure_count|failing_checks_count|failures|open_issues_count",
				"resolved_at":           "resolved_at",
				"registered":            "registered|enrolled|is_registered",
				"mdm_enabled":           "mdm.enabled|mdm_enabled",
				"last_seen_at":          "last_seen_at",
				"owner_email":           "owner.email",
				"user_email":            "user.email",
				"primary_email":         "primary_email",
			},
			StaticAttributes: map[string]string{"source_product": "kolide"},
		},
		{
			Name:           familyCheck,
			Path:           "/checks",
			PageSizeParams: []string{"per_page"},
			URNKind:        "kolide_check",
			IDKeys:         []string{"id", "check_id", "slug", "name"},
			TimestampKeys: []string{
				"updated_at", "last_run_at", "timestamp",
			},
			Attributes: map[string]string{
				"check_id":             "id|check_id",
				"slug":                 "slug",
				"name":                 "name",
				"title":                "issue_title|title|name",
				"status":               "status",
				"result":               "result",
				"severity":             "severity",
				"description":          "description",
				"compatible_platforms": "compatible_platforms",
				"check_tags":           "check_tags",
				"kolide_provided":      "kolide_provided",
				"percent_passing":      "percent_passing",
				"type":                 "type",
				"device_id":            "device_id|device.id",
				"device_name":          "device.name",
				"hostname":             "hostname",
				"user_email":           "user.email",
				"owner_email":          "owner.email",
				"remediation":          "fix_instructions_template|remediation",
				"rationale":            "rationale_template",
				"blocking_enabled":     "blocks_auth_configuration.blocking_enabled",
				"grace_period_days":    "blocks_auth_configuration.grace_period_days",
				"last_observed_at":     "last_run_at",
				"compliance_status":    "compliance_status",
			},
			StaticAttributes: map[string]string{"source_product": "kolide"},
		},
		{
			Name:           familyIssue,
			Path:           "/issues",
			PageSizeParams: []string{"per_page"},
			URNKind:        "kolide_issue",
			IDKeys:         []string{"id", "issue_id"},
			TimestampKeys: []string{
				"last_rechecked_at", "detected_at", "resolved_at",
			},
			Attributes: map[string]string{
				"issue_id":           "id|issue_id",
				"issue_key":          "issue_key",
				"issue_value":        "issue_value",
				"title":              "title",
				"check_id":           "check_id|check_information.identifier",
				"check_url":          "check_information.location",
				"device_id":          "device_id|device_information.identifier",
				"device_name":        "device_name|device.name|device_information.name|device_information.display_name",
				"hostname":           "hostname|device.hostname|device_information.hostname",
				"serial_number":      "serial_number|device.serial_number|device_information.serial_number",
				"device_url":         "device_information.location",
				"resolved_at":        "resolved_at",
				"detected_at":        "detected_at",
				"last_rechecked_at":  "last_rechecked_at",
				"blocks_device_at":   "blocks_device_at",
				"exempted":           "exempted",
				"check_result_value": "value",
			},
			StaticAttributes: map[string]string{"source_product": "kolide"},
		},
		{
			Name:           familySoftware,
			Path:           "/packages",
			PageSizeParams: []string{"per_page"},
			URNKind:        "kolide_software",
			IDKeys:         []string{"id", "package_id", "software_id", "application_id"},
			TimestampKeys: []string{
				"built_at", "updated_at", "installed_at", "last_seen_at",
			},
			Attributes: map[string]string{
				"software_id":       "id|package_id",
				"package_id":        "id|package_id",
				"device_id":         "device_id|device.id",
				"device_name":       "device.name",
				"hostname":          "hostname",
				"application_name":  "name|id",
				"app_name":          "name|id",
				"package_name":      "name|id",
				"bundle_identifier": "bundle_identifier",
				"version":           "version",
				"installed_version": "version",
				"built_at":          "built_at",
				"download_url":      "url",
				"publisher":         "publisher",
				"platform":          "platform",
				"ecosystem":         "ecosystem",
				"installed_at":      "installed_at",
				"purl":              "purl",
				"owner_email":       "owner.email",
				"user_email":        "user.email",
			},
			StaticAttributes: map[string]string{"source_product": "kolide"},
		},
		{
			Name:           familyUserDevice,
			Path:           "/devices",
			PageSizeParams: []string{"per_page"},
			URNKind:        "kolide_user_device",
			IDKeys:         []string{"id", "device_id", "hardware_uuid", "uuid", "serial", "serial_number"},
			TimestampKeys: []string{
				"updated_at", "last_seen_at", "last_authenticated_at", "registered_at", "last_check_in",
			},
			Attributes: map[string]string{
				"device_id":             "id|device_id",
				"device_uuid":           "hardware_uuid|uuid",
				"device_name":           "name",
				"hostname":              "hostname|name",
				"serial_number":         "serial|serial_number",
				"user_id":               "registered_owner_info.identifier|user.id",
				"user_email":            "user.email",
				"owner_id":              "registered_owner_info.identifier|owner.id",
				"owner_email":           "owner.email",
				"owner_url":             "registered_owner_info.location",
				"primary_email":         "primary_email",
				"registered_at":         "registered_at",
				"last_authenticated_at": "last_authenticated_at",
				"last_seen_at":          "last_seen_at",
			},
			StaticAttributes: map[string]string{"source_product": "kolide"},
		},
		{
			Name:           familyVulnerability,
			Path:           "/issues",
			PageSizeParams: []string{"per_page"},
			URNKind:        "kolide_vulnerability",
			IDKeys:         []string{"id", "vulnerability_id", "value.cve_id", "cve_id", "package_id"},
			TimestampKeys: []string{
				"updated_at", "detected_at", "last_observed_at", "last_rechecked_at", "published_at",
			},
			Attributes: map[string]string{
				"vulnerability_id":  "id",
				"cve_id":            "cve_id|value.cve_id|value.cve|issue_value",
				"advisory_id":       "advisory_id|value.advisory_id",
				"ghsa_id":           "ghsa_id|value.ghsa_id",
				"aliases":           "aliases|value.aliases",
				"severity":          "severity|value.severity",
				"title":             "title",
				"description":       "description|value.description",
				"device_id":         "device_id|device.id|device_information.identifier",
				"device_name":       "device.name",
				"hostname":          "hostname",
				"serial_number":     "serial_number",
				"application_name":  "software.name|package_name|name|value.software.name|value.package_name|value.package|issue_value",
				"app_name":          "software.name|package_name|name|value.software.name|value.package_name|value.package|issue_value",
				"package_name":      "package_name|software.name|name|value.package_name|value.software.name|value.package|issue_value",
				"package":           "package_name|software.name|name|value.package_name|value.software.name|value.package|issue_value",
				"version":           "installed_version|value.installed_version|value.version",
				"installed_version": "installed_version|value.installed_version|value.version",
				"fixed_version":     "fixed_version|value.fixed_version|value.patched_version",
				"purl":              "purl",
				"ecosystem":         "ecosystem|value.ecosystem",
				"remediation":       "remediation|value.remediation",
				"last_observed_at":  "last_observed_at|last_rechecked_at|detected_at",
				"known_exploited":   "known_exploited|value.known_exploited",
			},
			StaticAttributes: map[string]string{"source_product": "kolide"},
		},
	}
}
