"""Enforce regression baselines using benchmark scorecards."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Check regression tournament baselines"
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=Path("benchmarks/tournaments/regression.json"),
        help="Tournament configuration describing baseline thresholds",
    )
    parser.add_argument(
        "--scorecard",
        type=Path,
        default=Path("benchmarks/results/scorecard.json"),
        help="Scorecard generated by run_benchmarks.py",
    )
    return parser.parse_args()


def _load_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def main() -> int:
    args = _parse_args()

    if not args.scorecard.exists():
        print(f"Scorecard not found: {args.scorecard}")
        return 1

    config = _load_json(args.config)
    scorecard = _load_json(args.scorecard)

    alerts = []
    for scenario_cfg in config.get("scenarios", []):
        scenario_id = scenario_cfg["scenario_id"]
        metrics = scorecard.get(scenario_id)
        if metrics is None:
            alerts.append(f"Scorecard missing scenario {scenario_id}")
            continue

        success_rate = 1.0 if metrics.get("passed") else 0.0
        min_success = scenario_cfg.get("min_success_rate", 0.0)
        if success_rate < min_success:
            alerts.append(
                f"Scenario {scenario_id} success rate {success_rate:.2f} below baseline {min_success:.2f}"
            )

        max_turns = scenario_cfg.get("max_allowed_turns")
        if max_turns is not None and metrics.get("turn_count", 0) > max_turns:
            alerts.append(
                f"Scenario {scenario_id} exceeded turn ceiling ({metrics['turn_count']} > {max_turns})"
            )

    if alerts:
        print("Regression drift detected:")
        for alert in alerts:
            print(f" - {alert}")
        return 1

    print("Regression baselines satisfied")
    return 0


if __name__ == "__main__":
    sys.exit(main())
