apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cerebro-production

resources:
  - ../base

patchesStrategicMerge:
  - production-config.yaml

images:
  - name: cerebro
    newTag: v1.0.0

replicas:
  - name: cerebro-api
    count: 4
  - name: cerebro-worker-collection
    count: 3
  - name: cerebro-worker-findings
    count: 2
