apiVersion: v1
kind: ServiceAccount
metadata:
  name: cerebro
  labels:
    app.kubernetes.io/name: cerebro
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/cerebro-service-role
