package proactivetriage

import (
	"context"
	"errors"
	"fmt"
	"math"
	"strings"
	"time"

	"github.com/writer/cerebro/internal/agentplatform"
	"github.com/writer/cerebro/internal/findingmemory"
	"github.com/writer/cerebro/internal/jobs"
	"github.com/writer/cerebro/internal/knowledge"
	"github.com/writer/cerebro/internal/ports"
)

var (
	ErrInvalidRequest      = errors.New("invalid proactive triage request")
	ErrRuntimeUnavailable  = errors.New("proactive triage runtime is unavailable")
	ErrTenantScopeMismatch = errors.New("proactive triage tenant scope mismatch")
)

const SourceSystem = "cerebro:proactive_triage"

type FindingReader interface {
	GetFinding(context.Context, string) (*ports.FindingRecord, error)
	ListFindings(context.Context, ports.ListFindingsRequest) ([]*ports.FindingRecord, error)
}

type MemorySearcher interface {
	SimilarFindingMemory(context.Context, ports.SimilarFindingMemoryRequest) ([]ports.ScoredFindingMemoryRecord, error)
}

type Recommender interface {
	Recommend(context.Context, RecommendationRequest) (*Recommendation, error)
}

type ActionWriter interface {
	WriteAction(context.Context, knowledge.ActionWriteRequest) (*knowledge.ActionWriteResult, error)
}

type Service struct {
	Findings    FindingReader
	Memory      MemorySearcher
	Embedder    findingmemory.Embedder
	Recommender Recommender
	Actions     ActionWriter
	Now         func() time.Time
}

type RunRequest struct {
	TenantID  string
	FindingID string
	Limit     uint32
}

type RecommendationRequest struct {
	Finding *ports.FindingRecord
	Packet  agentplatform.AgentEvidencePacket
	Memory  []agentplatform.SecurityMemoryHint
}

type Recommendation struct {
	Title      string
	Summary    string
	Confidence float64
	TraceID    string
}

type FindingTriageResult struct {
	FindingID      string
	ActionID       string
	Confidence     float64
	MemoryHints    []agentplatform.SecurityMemoryHint
	Packet         agentplatform.AgentEvidencePacket
	Recommendation Recommendation
}

type RunResult struct {
	Findings []FindingTriageResult
}

func (s Service) Run(ctx context.Context, request RunRequest) (*RunResult, error) {
	if s.Findings == nil || s.Recommender == nil {
		return nil, ErrRuntimeUnavailable
	}
	tenantID := strings.TrimSpace(request.TenantID)
	if tenantID == "" {
		return nil, fmt.Errorf("%w: tenant_id is required", ErrInvalidRequest)
	}
	findings, err := s.loadFindings(ctx, request, tenantID)
	if err != nil {
		return nil, err
	}
	result := &RunResult{}
	for _, finding := range findings {
		if finding == nil {
			continue
		}
		if strings.TrimSpace(finding.TenantID) != tenantID {
			return nil, fmt.Errorf("%w: finding %q does not belong to the requested tenant", ErrTenantScopeMismatch, finding.ID)
		}
		memoryHints, err := s.memoryHints(ctx, finding)
		if err != nil {
			return nil, err
		}
		packet := agentplatform.BuildEvidencePacket(agentplatform.EvidencePacketRequest{
			TenantID:     tenantID,
			Question:     triageQuestion(finding),
			ScopeURN:     primaryScopeURN(finding),
			EvidenceURNs: evidenceURNs(finding),
			MemoryHints:  memoryHints,
			Action: agentplatform.EvidencePacketAction{
				Stage:      agentplatform.ActionStageRecommend,
				TargetURNs: actionTargets(finding),
			},
		})
		recommendation, err := s.Recommender.Recommend(ctx, RecommendationRequest{
			Finding: finding,
			Packet:  packet,
			Memory:  memoryHints,
		})
		if err != nil {
			return nil, err
		}
		if recommendation == nil {
			recommendation = &Recommendation{Title: "Triage recommendation", Summary: "Review this finding with the cited evidence before taking action."}
		}
		item := FindingTriageResult{
			FindingID:      strings.TrimSpace(finding.ID),
			Confidence:     recommendation.Confidence,
			MemoryHints:    memoryHints,
			Packet:         packet,
			Recommendation: *recommendation,
		}
		if s.Actions != nil {
			writeResult, err := s.Actions.WriteAction(ctx, knowledge.ActionWriteRequest{
				ID:            "proactive-triage-" + strings.TrimSpace(finding.ID),
				InsightType:   "triage_recommendation",
				Title:         firstNonEmpty(recommendation.Title, "Triage recommendation"),
				Summary:       strings.TrimSpace(recommendation.Summary),
				TargetIDs:     actionTargets(finding),
				SourceSystem:  SourceSystem,
				SourceEventID: strings.TrimSpace(recommendation.TraceID),
				ObservedAt:    s.now(),
				Confidence:    recommendation.Confidence,
				AutoGenerated: true,
				Metadata: map[string]any{
					"tenant_id":                   tenantID,
					"finding_id":                  strings.TrimSpace(finding.ID),
					"agent_packet_confidence":     packet.Confidence.Level,
					"agent_packet_confidence_why": strings.Join(packet.Confidence.Reasons, ","),
				},
			})
			if err != nil {
				return nil, err
			}
			if writeResult != nil {
				item.ActionID = writeResult.ActionID
			}
		}
		result.Findings = append(result.Findings, item)
	}
	return result, nil
}

func Runner(service *Service) jobs.Runner {
	return func(ctx context.Context, job *ports.Job, _ *jobs.Service) (map[string]any, map[string]string, error) {
		if service == nil || job == nil {
			return nil, nil, ErrRuntimeUnavailable
		}
		request := RunRequest{
			TenantID:  strings.TrimSpace(job.TenantID),
			FindingID: strings.TrimSpace(job.SubjectID),
			Limit:     payloadUint32(job.Payload, "limit"),
		}
		if value := payloadString(job.Payload, "tenant_id"); value != "" {
			request.TenantID = value
		}
		if value := payloadString(job.Payload, "finding_id"); value != "" {
			request.FindingID = value
		}
		result, err := service.Run(ctx, request)
		if err != nil {
			return nil, nil, err
		}
		refs := map[string]string{}
		payload := map[string]any{"triaged": len(result.Findings)}
		for _, item := range result.Findings {
			if item.ActionID != "" {
				refs[item.FindingID] = item.ActionID
			}
		}
		return payload, refs, nil
	}
}

func (s Service) loadFindings(ctx context.Context, request RunRequest, tenantID string) ([]*ports.FindingRecord, error) {
	if findingID := strings.TrimSpace(request.FindingID); findingID != "" {
		finding, err := s.Findings.GetFinding(ctx, findingID)
		if err != nil {
			return nil, err
		}
		return []*ports.FindingRecord{finding}, nil
	}
	limit := request.Limit
	if limit == 0 || limit > 25 {
		limit = 10
	}
	return s.Findings.ListFindings(ctx, ports.ListFindingsRequest{
		TenantID: tenantID,
		Status:   "open",
		Limit:    limit,
	})
}

func (s Service) memoryHints(ctx context.Context, finding *ports.FindingRecord) ([]agentplatform.SecurityMemoryHint, error) {
	if s.Memory == nil || s.Embedder == nil || finding == nil {
		return nil, nil
	}
	embedding, err := s.Embedder.EmbedText(ctx, findingmemory.FindingEmbeddingText(finding))
	if err != nil {
		return nil, err
	}
	matches, err := s.Memory.SimilarFindingMemory(ctx, ports.SimilarFindingMemoryRequest{
		TenantID:  finding.TenantID,
		Embedding: embedding,
		Limit:     5,
	})
	if err != nil {
		return nil, err
	}
	hints := make([]agentplatform.SecurityMemoryHint, 0, len(matches))
	for _, match := range matches {
		if match.Record == nil {
			continue
		}
		hints = append(hints, agentplatform.SecurityMemoryHint{
			Type: match.Record.Type,
			URN:  "urn:cerebro:" + safeURNPart(match.Record.TenantID) + ":security-memory:" + safeURNPart(match.Record.ID),
			Note: strings.TrimSpace(match.Record.Summary),
		})
	}
	return hints, nil
}

func (s Service) now() time.Time {
	if s.Now != nil {
		return s.Now().UTC()
	}
	return time.Now().UTC()
}

func triageQuestion(finding *ports.FindingRecord) string {
	return "Triage this finding and recommend the next safe action: " + firstNonEmpty(finding.Title, finding.RuleID, finding.ID)
}

func primaryScopeURN(finding *ports.FindingRecord) string {
	if finding == nil {
		return ""
	}
	if finding.Attributes != nil {
		if value := strings.TrimSpace(finding.Attributes["primary_resource_urn"]); value != "" {
			return value
		}
	}
	if len(finding.ResourceURNs) > 0 {
		return strings.TrimSpace(finding.ResourceURNs[0])
	}
	return ""
}

func evidenceURNs(finding *ports.FindingRecord) []string {
	if finding == nil {
		return nil
	}
	out := []string{}
	out = append(out, finding.ResourceURNs...)
	return normalizedStrings(out)
}

func actionTargets(finding *ports.FindingRecord) []string {
	targets := evidenceURNs(finding)
	if len(targets) == 0 && finding != nil && strings.TrimSpace(finding.ID) != "" {
		targets = append(targets, strings.TrimSpace(finding.ID))
	}
	return targets
}

func payloadString(payload map[string]any, key string) string {
	if payload == nil {
		return ""
	}
	value, _ := payload[key].(string)
	return strings.TrimSpace(value)
}

func payloadUint32(payload map[string]any, key string) uint32 {
	if payload == nil {
		return 0
	}
	switch v := payload[key].(type) {
	case uint32:
		return v
	case float64:
		if v >= 0 && v <= float64(math.MaxUint32) {
			return uint32(v)
		}
	case int:
		if v >= 0 && uint64(v) <= math.MaxUint32 {
			return uint32(v)
		}
	case int64:
		if v >= 0 && uint64(v) <= math.MaxUint32 {
			return uint32(v)
		}
	}
	return 0
}

func normalizedStrings(values []string) []string {
	seen := map[string]struct{}{}
	out := []string{}
	for _, value := range values {
		trimmed := strings.TrimSpace(value)
		if trimmed == "" {
			continue
		}
		if _, ok := seen[trimmed]; ok {
			continue
		}
		seen[trimmed] = struct{}{}
		out = append(out, trimmed)
	}
	return out
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if trimmed := strings.TrimSpace(value); trimmed != "" {
			return trimmed
		}
	}
	return ""
}

func safeURNPart(value string) string {
	value = strings.TrimSpace(value)
	var b strings.Builder
	for _, r := range value {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == '_' || r == '-' || r == '.':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	if b.Len() == 0 {
		return "unknown"
	}
	return b.String()
}
