package proactivetriage

import (
	"context"
	"testing"
	"time"

	"github.com/writer/cerebro/internal/findingmemory"
	"github.com/writer/cerebro/internal/knowledge"
	"github.com/writer/cerebro/internal/ports"
)

type stubFindingReader struct {
	finding *ports.FindingRecord
	listed  bool
}

func (r *stubFindingReader) GetFinding(_ context.Context, id string) (*ports.FindingRecord, error) {
	if r.finding != nil {
		r.finding.ID = id
	}
	return r.finding, nil
}

func (r *stubFindingReader) ListFindings(_ context.Context, _ ports.ListFindingsRequest) ([]*ports.FindingRecord, error) {
	r.listed = true
	return []*ports.FindingRecord{r.finding}, nil
}

type stubMemorySearcher struct {
	matches []ports.ScoredFindingMemoryRecord
	called  bool
}

func (s *stubMemorySearcher) SimilarFindingMemory(_ context.Context, request ports.SimilarFindingMemoryRequest) ([]ports.ScoredFindingMemoryRecord, error) {
	s.called = true
	if request.TenantID != "tenant-a" {
		return nil, nil
	}
	return s.matches, nil
}

type stubRecommender struct {
	request RecommendationRequest
}

func (r *stubRecommender) Recommend(_ context.Context, request RecommendationRequest) (*Recommendation, error) {
	r.request = request
	return &Recommendation{Title: "Review related identity drift", Summary: "Prior similar findings suggest owner review before remediation.", Confidence: 0.72, TraceID: "trace-1"}, nil
}

type stubActionWriter struct {
	request knowledge.ActionWriteRequest
}

func (w *stubActionWriter) WriteAction(_ context.Context, request knowledge.ActionWriteRequest) (*knowledge.ActionWriteResult, error) {
	w.request = request
	return &knowledge.ActionWriteResult{ActionID: "action-1", TargetCount: 1}, nil
}

func TestRunBuildsEvidencePacketAndWritesAutoGeneratedRecommendation(t *testing.T) {
	finding := &ports.FindingRecord{
		ID:           "finding-1",
		TenantID:     "tenant-a",
		RuleID:       "identity-drift",
		Title:        "Privileged identity drift",
		Summary:      "A privileged account is active after offboarding.",
		Status:       "open",
		ResourceURNs: []string{"urn:cerebro:tenant-a:identity:user:alice"},
		Attributes:   map[string]string{"primary_resource_urn": "urn:cerebro:tenant-a:identity:user:alice"},
	}
	memory := &stubMemorySearcher{matches: []ports.ScoredFindingMemoryRecord{{
		Record: &ports.FindingMemoryRecord{
			ID:       "memory-1",
			TenantID: "tenant-a",
			Type:     findingmemory.TypePriorInvestigation,
			Summary:  "A prior case was resolved by confirming lifecycle ownership.",
		},
		Score: 0.91,
	}}}
	recommender := &stubRecommender{}
	writer := &stubActionWriter{}
	result, err := (Service{
		Findings:    &stubFindingReader{finding: finding},
		Memory:      memory,
		Embedder:    findingmemory.HashEmbedder{Dimensions: 8},
		Recommender: recommender,
		Actions:     writer,
		Now:         func() time.Time { return time.Unix(100, 0).UTC() },
	}).Run(context.Background(), RunRequest{TenantID: "tenant-a", FindingID: "finding-1"})
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}
	if len(result.Findings) != 1 || result.Findings[0].ActionID != "action-1" {
		t.Fatalf("result = %#v", result)
	}
	if !memory.called {
		t.Fatalf("memory search was not called")
	}
	if recommender.request.Packet.TenantID != "tenant-a" || recommender.request.Packet.ActionLadder[2].Stage.ID != "recommend" {
		t.Fatalf("packet = %#v", recommender.request.Packet)
	}
	if writer.request.SourceSystem != SourceSystem || !writer.request.AutoGenerated {
		t.Fatalf("write request = %#v", writer.request)
	}
	if got := writer.request.TargetIDs; len(got) != 1 || got[0] != "urn:cerebro:tenant-a:identity:user:alice" {
		t.Fatalf("target ids = %#v", got)
	}
}
