[package]
name = "cerebro-security-path-kernel-fuzz"
version = "0.0.0"
publish = false
edition = "2024"
license = "Apache-2.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
cerebro-security-path-kernel = { path = "..", version = "0.1.0" }
libfuzzer-sys = "0.4"
serde_json = "1.0.150"

[[bin]]
name = "evaluate"
path = "fuzz_targets/evaluate.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
