import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { buildCoverageReport } from "../src/coverageReport.js";
import { writeEditorMcpConfig, writeMcpLauncher } from "../src/editorConfig.js";
import { lintPractices } from "../src/practiceLint.js";
import { PracticeRegistry } from "../src/registry.js";
import { scanDiff as scanDiffWithSemgrep } from "../src/scan.js";

let tempDir: string;
let registry: PracticeRegistry;

beforeEach(() => {
  tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "practice-registry-"));
  registry = new PracticeRegistry({
    practicesRoot: path.resolve("practices"),
    dbPath: path.join(tempDir, "practices.db"),
  });
});

afterEach(() => {
  registry.close();
  fs.rmSync(tempDir, { recursive: true, force: true });
});

describe("practice registry", () => {
  it("indexes the seed practice pack", () => {
    const records = registry.rebuild();

    expect(records.length).toBeGreaterThanOrEqual(76);
    expect(records.map((record) => record.id)).toContain("python.subprocess.no-shell-true");
    expect(records.map((record) => record.id)).toContain("scala.effects.no-await-result-in-services");
    expect(records.map((record) => record.id)).toContain("python.writer.typed-settings");
    expect(records.map((record) => record.id)).toContain("scala.writer.eventunit-startup-injection");
    expect(records.map((record) => record.id)).toContain("python.security.unsafe-deserialization");
    expect(records.map((record) => record.id)).toContain("scala.security.java-deserialization");
    expect(records.map((record) => record.id)).toContain("python.security.no-eval-exec");
    expect(records.map((record) => record.id)).toContain("scala.security.no-runtime-exec");
    expect(records.map((record) => record.id)).toContain("python.defaults.no-mutable-defaults");
    expect(records.map((record) => record.id)).toContain("typescript.db.parameterized-sql");
    expect(records.map((record) => record.id)).toContain("typescript.fs.single-descriptor-updates");
    expect(records.map((record) => record.id)).toContain("typescript.react.no-dangerous-html");
    expect(records.map((record) => record.id)).toContain("typescript.api.zod-request-boundaries");
    expect(records.map((record) => record.id)).toContain("typescript.react.bounded-list-projections");
    expect(records.map((record) => record.id)).toContain("rust.process.no-shell-command");
    expect(records.map((record) => record.id)).toContain("rust.tooling.cargo-quality-gates");
    expect(records.map((record) => record.id)).toContain("rust.testing.fuzz-parsers-and-invariants");
  });

  it("merges an existing editor config without replacing unrelated servers", () => {
    const outputPath = path.join(tempDir, ".cursor", "mcp.json");
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, `${JSON.stringify({ mcpServers: { existing: { command: "existing-server" } } })}\n`);

    writeEditorMcpConfig({
      client: "cursor",
      registryRoot: tempDir,
      launcherPath: ".practice-registry/run-mcp",
      outputPath,
    });

    const config = JSON.parse(fs.readFileSync(outputPath, "utf8")) as { mcpServers: Record<string, unknown> };
    expect(config.mcpServers.existing).toEqual({ command: "existing-server" });
    expect(config.mcpServers["practice-registry"]).toEqual({
      type: "stdio",
      command: ".practice-registry/run-mcp",
      args: [],
    });
  });

  it("does not replace an unowned launcher without overwrite", () => {
    const outputPath = path.join(tempDir, ".practice-registry", "run-mcp");
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, "#!/bin/sh\necho user-owned\n");

    expect(() => writeMcpLauncher({ outputPath, registryRoot: tempDir })).toThrow(
      "exists and was not generated by Practice Registry",
    );
    expect(fs.readFileSync(outputPath, "utf8")).toBe("#!/bin/sh\necho user-owned\n");
  });

  it("guides generated file updates through one descriptor", () => {
    registry.rebuild();

    const result = registry.check("plan", {
      language: "typescript",
      files: ["src/editorConfig.ts"],
      intent: "repair a file system race while updating a generated launcher",
      planned_approach: "Use openSync once, validate through the descriptor, then update with ftruncateSync and fstatSync on that descriptor.",
    });

    expect(result.passed).toBe(true);
    expect(result.decision).toBe("follow_guidance");
    expect(result.matched_practices.map((practice) => practice.id)).toContain("typescript.fs.single-descriptor-updates");
    expect(result.matched_practices.map((practice) => practice.id)).not.toContain("typescript.db.parameterized-sql");
  });

  it("blocks shell execution in Python plans", () => {
    registry.rebuild();

    const result = registry.check("plan", {
      language: "python",
      files: ["services/sync/git_worker.py"],
      intent: "run a command in a worker",
      planned_approach: "Use subprocess.run(command, shell=True)",
    });

    expect(result.blocking).toBe(true);
    expect(result.decision).toBe("change_code");
    expect(result.passed).toBe(false);
    expect(result.action_required).toBe(true);
    expect(result.rerun_required).toBe(true);
    expect(result.matched_practices[0]?.id).toBe("python.subprocess.no-shell-true");
    expect(result.next_steps).toContain("Use instead: Pass an argument list to subprocess.run.");
  });

  it("infers Python language from diff paths", () => {
    registry.rebuild();

    const result = registry.check("diff", {
      diff: [
        "diff --git a/services/sync/git_worker.py b/services/sync/git_worker.py",
        "+++ b/services/sync/git_worker.py",
        "+subprocess.run(command, shell=True)",
      ].join("\n"),
    });

    expect(result.blocking).toBe(true);
    expect(result.matched_practices[0]?.id).toBe("python.subprocess.no-shell-true");
  });

  it("infers Rust language from diff paths", () => {
    registry.rebuild();

    const result = registry.check("diff", {
      diff: [
        "diff --git a/src/release.rs b/src/release.rs",
        "+++ b/src/release.rs",
        '+Command::new("sh").arg("-c").arg(command).status()?;',
      ].join("\n"),
    });

    expect(result.blocking).toBe(true);
    expect(result.matched_practices.map((match) => match.id)).toContain("rust.process.no-shell-command");
  });

  it("infers Rust language from Cargo manifests", () => {
    registry.rebuild();

    const result = registry.check("plan", {
      files: ["Cargo.toml"],
      intent: "add a Rust crate and its CI checks",
      planned_approach: "Run cargo fmt, cargo test, cargo clippy with warnings denied, and cargo doc.",
    });

    expect(result.passed).toBe(true);
    expect(result.decision).toBe("follow_guidance");
    expect(result.matched_practices.map((match) => match.id)).toContain("rust.tooling.cargo-quality-gates");
  });

  it("blocks Await.result in Scala diffs", () => {
    registry.rebuild();

    const result = registry.check("diff", {
      language: "scala",
      diff: [
        "diff --git a/services/users/UserService.scala b/services/users/UserService.scala",
        "+++ b/services/users/UserService.scala",
        "+val user = Await.result(userRepo.fetch(id), 5.seconds)",
      ].join("\n"),
    });

    expect(result.blocking).toBe(true);
    expect(result.matched_practices.map((match) => match.id)).toContain(
      "scala.effects.no-await-result-in-services",
    );
  });

  it("scans concrete Python findings from changed lines", () => {
    registry.rebuild();

    const result = registry.scanDiff(
      [
        "diff --git a/services/sync/git_worker.py b/services/sync/git_worker.py",
        "+++ b/services/sync/git_worker.py",
        "@@ -1,1 +1,2 @@",
        " import subprocess",
        "+subprocess.run(command, shell=True)",
      ].join("\n"),
      { useSemgrep: false },
    );

    expect(result.blocking).toBe(true);
    expect(result.decision).toBe("change_code");
    expect(result.passed).toBe(false);
    expect(result.findings[0]?.practice_id).toBe("python.subprocess.no-shell-true");
    expect(result.findings[0]?.engine).toBe("semgrep-rule-fallback");
    expect(result.next_steps).toContain("Use instead: Pass an argument list to subprocess.run.");
    expect(result.next_steps).toContain("Change services/sync/git_worker.py:2 before continuing.");
  });

  it("keeps multi-line Semgrep findings when an added line overlaps the match range", () => {
    const records = registry.rebuild();
    const sourceDir = path.join(tempDir, "src");
    const sourcePath = path.join(sourceDir, "release.rs");
    const semgrepBin = path.join(tempDir, "fake-semgrep.mjs");
    fs.mkdirSync(sourceDir, { recursive: true });
    fs.writeFileSync(
      sourcePath,
      [
        "use std::process::Command;",
        "",
        "fn run(command: &str) -> std::io::Result<()> {",
        "    Command::new(",
        '        "sh",',
        "    )",
        '    .arg("-c")',
        "    .arg(command)",
        "    .status()?;",
        "    Ok(())",
        "}",
      ].join("\n"),
    );
    const semgrepOutput = JSON.stringify({
      results: [
        {
          check_id: "rust.process.no-shell-command",
          path: "src/release.rs",
          start: { line: 4 },
          end: { line: 6 },
          extra: {
            message: "Execute Rust child processes without a shell",
            severity: "ERROR",
            metadata: { practice_id: "rust.process.no-shell-command" },
          },
        },
        {
          check_id: "rust.process.no-shell-command",
          path: "src/release.rs",
          start: { line: 7 },
          end: { line: 9 },
          extra: {
            message: "Unchanged match outside the added line",
            severity: "ERROR",
            metadata: { practice_id: "rust.process.no-shell-command" },
          },
        },
      ],
    });
    fs.writeFileSync(
      semgrepBin,
      `#!/usr/bin/env node\nprocess.stdout.write(${JSON.stringify(semgrepOutput)});\n`,
    );
    fs.chmodSync(semgrepBin, 0o755);

    const result = scanDiffWithSemgrep(
      records,
      [
        "diff --git a/src/release.rs b/src/release.rs",
        "+++ b/src/release.rs",
        "@@ -4,3 +4,3 @@",
        "     Command::new(",
        '-        "git",',
        '+        "sh",',
        "     )",
      ].join("\n"),
      {
        cwd: tempDir,
        rulesPath: path.resolve("semgrep/practice-rules.yml"),
        semgrepBin,
      },
    );

    expect(result.blocking).toBe(true);
    expect(result.findings).toHaveLength(1);
    expect(result.findings[0]?.practice_id).toBe("rust.process.no-shell-command");
    expect(result.findings[0]?.engine).toBe("semgrep");
    expect(result.findings[0]?.line).toBe(5);
    expect(result.findings[0]?.code).toBe('        "sh",');
  });

  it("finds multi-line blocker ranges when Semgrep is unavailable", () => {
    const records = registry.rebuild();
    const sourceDir = path.join(tempDir, "src");
    const sourcePath = path.join(sourceDir, "release.rs");
    fs.mkdirSync(sourceDir, { recursive: true });
    fs.writeFileSync(
      sourcePath,
      [
        "use std::process::Command;",
        "",
        "fn run(command: &str) -> std::io::Result<()> {",
        "    Command::new(",
        '        "sh",',
        "    )",
        '    .arg("-c")',
        "    .arg(command)",
        "    .status()?;",
        "    Command::new(",
        '        "bash",',
        "    )",
        '    .arg("-c")',
        "    .arg(command)",
        "    .status()?;",
        "    Ok(())",
        "}",
      ].join("\n"),
    );

    const result = scanDiffWithSemgrep(
      records,
      [
        "diff --git a/src/release.rs b/src/release.rs",
        "+++ b/src/release.rs",
        "@@ -4,3 +4,3 @@",
        "     Command::new(",
        '-        "git",',
        '+        "sh",',
        "     )",
      ].join("\n"),
      {
        cwd: tempDir,
        rulesPath: path.resolve("semgrep/practice-rules.yml"),
        useSemgrep: false,
      },
    );

    expect(result.blocking).toBe(true);
    expect(result.findings).toHaveLength(1);
    expect(result.findings[0]?.practice_id).toBe("rust.process.no-shell-command");
    expect(result.findings[0]?.engine).toBe("semgrep-rule-fallback");
    expect(result.findings[0]?.line).toBe(5);
    expect(result.findings[0]?.code).toBe('        "sh",');
  });

  it("matches rustfmt-style multi-line Rust blocker calls", () => {
    registry.rebuild();
    const shellPattern = registry.explain("rust.process.no-shell-command")?.semgrep?.pattern_regex;
    const tlsPattern = registry.explain("rust.http.no-insecure-tls-verification")?.semgrep?.pattern_regex;

    expect(shellPattern).toBeDefined();
    expect(tlsPattern).toBeDefined();
    expect(
      new RegExp(shellPattern!).test(
        ['Command::new(', '    "sh",', ")"].join("\n"),
      ),
    ).toBe(true);
    expect(
      new RegExp(tlsPattern!).test(
        [".danger_accept_invalid_certs(", "    true,", ")"].join("\n"),
      ),
    ).toBe(true);
    expect(new RegExp(shellPattern!).test('Command::new("git")')).toBe(false);
    expect(new RegExp(tlsPattern!).test(".danger_accept_invalid_certs(false)")).toBe(false);
  });

  it("tracks observation outcome fields and stats", () => {
    registry.rebuild();

    registry.check("plan", {
      language: "python",
      files: ["services/sync/git_worker.py"],
      intent: "run a command in a worker",
      planned_approach: "Use subprocess.run(command, shell=True)",
    });
    registry.check("plan", {
      language: "scala",
      files: ["modules/proto/generated/UserProto.scala"],
      intent: "generated protobuf null interop",
      planned_approach: "Keep generated null handling contained at the boundary",
    });

    const recent = registry.recentObservations({ limit: 5 });
    const stats = registry.observationStats();

    expect(recent[0]?.kind).toBe("plan");
    expect(recent.some((observation) => observation.action_required)).toBe(true);
    expect(stats.total).toBe(2);
    expect(stats.action_required).toBe(2);
    expect(stats.top_practices.map((entry) => entry.practice_id)).toContain("python.subprocess.no-shell-true");
  });

  it("finalize_change requires a passing plan check by default", () => {
    registry.rebuild();

    const result = registry.finalizeChange({
      language: "python",
      use_semgrep: false,
      diff: [
        "diff --git a/src/api/users.py b/src/api/users.py",
        "+++ b/src/api/users.py",
        "@@ -1,1 +1,2 @@",
        " from fastapi import APIRouter",
        "+router = APIRouter()",
      ].join("\n"),
    });

    expect(result.decision).toBe("needs_review");
    expect(result.passed).toBe(false);
    expect(result.observations.passing_plan_found).toBe(false);
    expect(result.next_steps).toContain("Call check_plan with the implementation approach for the same files or language as the final diff.");
  });

  it("finalize_change passes after a passing plan and clean scan", () => {
    registry.rebuild();

    const plan = registry.check("plan", {
      language: "scala",
      framework: "cats-effect",
      files: [path.join(process.cwd(), "server/src/com/writer/reporting/SessionInternalService.scala")],
      intent: "publish an audit log event",
      planned_approach: "Create an EventUnit in the application loader and inject it into the service.",
    });
    const result = registry.finalizeChange({
      language: "scala",
      use_semgrep: false,
      diff: [
        "diff --git a/server/src/com/writer/reporting/SessionInternalService.scala b/server/src/com/writer/reporting/SessionInternalService.scala",
        "+++ b/server/src/com/writer/reporting/SessionInternalService.scala",
        "@@ -1,1 +1,2 @@",
        " final class SessionInternalService",
        "+def publishAuditLog(): Unit = ()",
      ].join("\n"),
    });

    expect(plan.passed).toBe(true);
    expect(plan.observation_id).toBeGreaterThan(0);
    expect(result.decision).toBe("allowed");
    expect(result.passed).toBe(true);
    expect(result.observations.passing_plan_found).toBe(true);
    expect(result.observations.plan_check.matched_observation_id).toBe(plan.observation_id);
  });

  it("finalize_change rejects stale passing plans for different files", () => {
    registry.rebuild();

    registry.check("plan", {
      language: "scala",
      framework: "cats-effect",
      files: ["server/src/com/writer/reporting/SessionInternalService.scala"],
      intent: "publish an audit log event",
      planned_approach: "Create an EventUnit in the application loader and inject it into the service.",
    });
    const result = registry.finalizeChange({
      language: "python",
      use_semgrep: false,
      diff: [
        "diff --git a/src/api/users.py b/src/api/users.py",
        "+++ b/src/api/users.py",
        "@@ -1,1 +1,2 @@",
        " from fastapi import APIRouter",
        "+router = APIRouter()",
      ].join("\n"),
    });

    expect(result.decision).toBe("needs_review");
    expect(result.passed).toBe(false);
    expect(result.observations.passing_plan_found).toBe(false);
    expect(result.observations.plan_check.reason).toContain("No recent passing check_plan matched");
  });

  it("finalize_change accepts an explicit matching plan observation id", () => {
    registry.rebuild();

    const plan = registry.check("plan", {
      language: "scala",
      framework: "cats-effect",
      files: ["server/src/com/writer/reporting/SessionInternalService.scala"],
      intent: "publish an audit log event",
      planned_approach: "Create an EventUnit in the application loader and inject it into the service.",
    });
    const result = registry.finalizeChange({
      plan_observation_id: plan.observation_id,
      language: "scala",
      use_semgrep: false,
      diff: [
        "diff --git a/server/src/com/writer/reporting/SessionInternalService.scala b/server/src/com/writer/reporting/SessionInternalService.scala",
        "+++ b/server/src/com/writer/reporting/SessionInternalService.scala",
        "@@ -1,1 +1,2 @@",
        " final class SessionInternalService",
        "+def publishAuditLog(): Unit = ()",
      ].join("\n"),
    });

    expect(result.passed).toBe(true);
    expect(result.observations.plan_check.match_type).toBe("provided");
    expect(result.observations.plan_check.matched_observation_id).toBe(plan.observation_id);
  });

  it("lints practice records without publication blockers", () => {
    const result = lintPractices(registry.rebuild());

    expect(result.decision).toBe("allowed");
    expect(result.passed).toBe(true);
    expect(result.findings.filter((finding) => finding.severity === "error")).toEqual([]);
  });

  it("normalizes absolute no-index diff paths before scanning", () => {
    registry.rebuild();

    const absoluteFile = path.join(tempDir, "src/api/users.py");
    const droidDiffPath = absoluteFile.replace(/^\/+/, "");
    const result = registry.scanDiff(
      [
        `diff --git a/${droidDiffPath} b/${droidDiffPath}`,
        `+++ b/${droidDiffPath}`,
        "@@ -1,1 +1,2 @@",
        " import os",
        '+feature_flag = os.environ.get("FEATURE_FLAG", "")',
      ].join("\n"),
      { cwd: tempDir, useSemgrep: false },
    );

    expect(result.decision).toBe("revise_or_justify");
    expect(result.findings[0]?.practice_id).toBe("python.writer.typed-settings");
    expect(result.findings[0]?.path).toBe("src/api/users.py");
  });

  it("normalizes absolute no-index diff paths before matching", () => {
    registry.rebuild();

    const absoluteFile = path.join(process.cwd(), "src/api/users.py");
    const droidDiffPath = absoluteFile.replace(/^\/+/, "");
    const result = registry.check("diff", {
      framework: "fastapi",
      diff: [
        `diff --git a/${droidDiffPath} b/${droidDiffPath}`,
        `+++ b/${droidDiffPath}`,
        "@@ -1,1 +1,2 @@",
        " import os",
        '+feature_flag = os.environ.get("FEATURE_FLAG", "")',
      ].join("\n"),
    });

    expect(result.decision).toBe("revise_or_justify");
    expect(result.matched_practices.map((match) => match.id)).toContain("python.writer.typed-settings");
  });

  it("keeps diff-only semantic checks from inventing unrelated blockers", () => {
    registry.rebuild();

    const absoluteFile = path.join(process.cwd(), "src/api/users.py");
    const droidDiffPath = absoluteFile.replace(/^\/+/, "");
    const result = registry.check("diff", {
      framework: "fastapi",
      diff: [
        `diff --git a/${droidDiffPath} b/${droidDiffPath}`,
        `+++ b/${droidDiffPath}`,
        "@@ -1,1 +1,8 @@",
        "+from __future__ import annotations",
        "+import os",
        "+from fastapi import APIRouter",
        "+router = APIRouter()",
        "+@router.get(\"/users\")",
        "+def get_users() -> dict[str, bool]:",
        '+    feature_flag = os.environ.get("FEATURE_FLAG", "")',
        "+    return {\"ok\": True}",
      ].join("\n"),
    });

    const matchedIds = result.matched_practices.map((match) => match.id);
    expect(result.blocking).toBe(false);
    expect(matchedIds).toContain("python.writer.typed-settings");
    expect(matchedIds).not.toContain("python.security.jwt-signature-verification");
    expect(matchedIds).not.toContain("python.defaults.no-mutable-defaults");
  });

  it("scans proposed apply_patch text before edits land", () => {
    registry.rebuild();

    const result = registry.scanDiff(
      [
        "*** Begin Patch",
        "*** Update File: services/users/UserService.scala",
        "@@",
        "+val user = Await.result(userRepo.fetch(id), 5.seconds)",
        "*** End Patch",
      ].join("\n"),
      { useSemgrep: false },
    );

    expect(result.blocking).toBe(true);
    expect(result.findings[0]?.practice_id).toBe("scala.effects.no-await-result-in-services");
  });

  it("returns guidance for structured Python logging", () => {
    registry.rebuild();

    const result = registry.check("plan", {
      language: "python",
      framework: "fastapi",
      files: ["services/api/users.py"],
      intent: "add logging for a request handler",
      planned_approach: "Add print statements while handling requests",
    });

    expect(result.decision).toBe("revise_or_justify");
    expect(result.matched_practices.map((match) => match.id)).toContain("python.logging.no-print-in-services");
  });

  it("does not flag Python logging replacements as print usage", () => {
    registry.rebuild();

    const result = registry.check("plan", {
      language: "python",
      framework: "fastapi",
      files: ["src/api/health.py"],
      intent: "add a FastAPI health check route with structured logging",
      planned_approach:
        "Use APIRouter, return a typed status response, and log a stable health_check event through a module logger with structured fields.",
    });

    const matchedIds = result.matched_practices.map((match) => match.id);
    expect(result.passed).toBe(true);
    expect(result.decision).toBe("follow_guidance");
    expect(matchedIds).toContain("observability.structured-logs");
    expect(matchedIds).not.toContain("python.logging.no-print-in-services");
    expect(matchedIds).not.toContain("python.logging.no-fstring-logs");
  });

  it("returns Writer Python configuration guidance", () => {
    registry.rebuild();

    const result = registry.check("plan", {
      language: "python",
      framework: "fastapi",
      files: ["src/orders/api/routes.py"],
      intent: "read an environment variable in a request handler",
      planned_approach: "Call os.getenv(\"FEATURE_FLAG\") in the handler before choosing a response.",
    });

    expect(result.decision).toBe("revise_or_justify");
    expect(result.matched_practices.map((match) => match.id)).toContain("python.writer.typed-settings");
  });

  it("does not block compliant plans that name avoided risks", () => {
    registry.rebuild();

    const result = registry.check("plan", {
      repo: "droid-tmux-e2e",
      language: "python",
      framework: "fastapi",
      files: ["src/api/users.py"],
      dependencies: ["fastapi", "httpx", "pydantic-settings"],
      intent:
        "Create a FastAPI GET /users route that reads FEATURE_FLAG, logs the request id, calls an external users API, and returns an ok response.",
      planned_approach:
        "Create an APIRouter with a module logger, constants for the external URL and timeout, and a typed Settings class using pydantic_settings.BaseSettings. Use httpx.AsyncClient with an explicit timeout and default TLS verification. Do not use print, f-string logging, mutable defaults, shell/subprocess calls, request-controlled URLs, disabled TLS verification, or os.getenv in the handler.",
    });

    const matchedIds = result.matched_practices.map((match) => match.id);
    expect(result.blocking).toBe(false);
    expect(result.decision).toBe("follow_guidance");
    expect(matchedIds).not.toContain("python.subprocess.no-shell-true");
    expect(matchedIds).not.toContain("python.security.insecure-tls-verification");
    expect(matchedIds).not.toContain("python.writer.typed-settings");
    expect(matchedIds).not.toContain("python.http.client-timeout");
  });

  it("flags Python settings reads planned at module import", () => {
    registry.rebuild();

    const result = registry.check("plan", {
      language: "python",
      framework: "fastapi",
      files: ["src/api/users.py"],
      intent: "Create a route that reads FEATURE_FLAG.",
      planned_approach:
        "Read FEATURE_FLAG from the environment once at module import and reuse that value inside the request handler.",
    });

    expect(result.decision).toBe("revise_or_justify");
    expect(result.matched_practices.map((match) => match.id)).toContain("python.writer.typed-settings");
  });

  it("returns Writer Scala EventUnit guidance", () => {
    registry.rebuild();

    const result = registry.check("plan", {
      language: "scala",
      framework: "cats-effect",
      files: ["server/src/com/writer/reporting/SessionInternalService.scala"],
      intent: "publish an audit log event",
      planned_approach: "Create an EventUnit in the service method and call save for each request.",
    });

    expect(result.decision).toBe("follow_guidance");
    expect(result.matched_practices.map((match) => match.id)).toContain("scala.writer.eventunit-startup-injection");
  });

  it("blocks unsafeRunSync in Scala service diffs", () => {
    registry.rebuild();

    const result = registry.scanDiff(
      [
        "diff --git a/server/src/com/writer/users/UserService.scala b/server/src/com/writer/users/UserService.scala",
        "+++ b/server/src/com/writer/users/UserService.scala",
        "@@ -1,1 +1,2 @@",
        " final class UserService",
        "+val user = userRepo.fetch(id).unsafeRunSync()",
      ].join("\n"),
      { useSemgrep: false },
    );

    expect(result.blocking).toBe(true);
    expect(result.findings.map((finding) => finding.practice_id)).toContain("scala.effects.no-unsafe-run-sync-in-services");
  });

  it("does not block compliant Scala effect composition plans", () => {
    registry.rebuild();

    const result = registry.check("plan", {
      language: "scala",
      framework: "cats-effect",
      files: ["services/UserService.scala"],
      intent: "add user lookup with database call and audit log",
      planned_approach:
        "Use IO, no Await.result, inject Resource-backed clients, use EventUnit for audit events, and return typed errors.",
    });

    expect(result.passed).toBe(true);
    expect(result.decision).toBe("follow_guidance");
    expect(result.matched_practices.map((match) => match.id)).toContain("scala.writer.eventunit-startup-injection");
    expect(result.matched_practices.map((match) => match.id)).not.toContain("scala.effects.no-unsafe-run-sync-in-services");
    expect(result.matched_practices.map((match) => match.id)).not.toContain("scala.effects.no-await-result-in-services");
  });

  it("treats generated Scala null handling as legacy accepted", () => {
    registry.rebuild();

    const result = registry.check("plan", {
      language: "scala",
      files: ["modules/proto/generated/UserProto.scala"],
      intent: "generated protobuf null interop",
      planned_approach: "Keep generated null handling contained at the boundary",
    });

    expect(result.blocking).toBe(false);
    expect(result.decision).toBe("revise_or_justify");
    expect(result.matched_practices[0]?.id).toBe("scala.generated.null-legacy-accepted");
  });

  it("does not block generated Scala null findings", () => {
    registry.rebuild();

    const result = registry.scanDiff(
      [
        "diff --git a/modules/proto/generated/UserProto.scala b/modules/proto/generated/UserProto.scala",
        "+++ b/modules/proto/generated/UserProto.scala",
        "@@ -1,1 +1,2 @@",
        " final class UserProto",
        "+val email: String = null",
      ].join("\n"),
      { useSemgrep: false },
    );

    expect(result.blocking).toBe(false);
    expect(result.findings.map((finding) => finding.practice_id)).not.toContain("scala.values.no-null");
  });

  it("scans secure coding findings for Python and Scala", () => {
    registry.rebuild();

    const cases = [
      {
        practiceId: "security.logging.no-sensitive-values",
        blocking: true,
        diff: [
          "diff --git a/src/auth/session.py b/src/auth/session.py",
          "+++ b/src/auth/session.py",
          "@@ -1,1 +1,2 @@",
          " logger.info(\"login\")",
          "+logger.info(\"token=%s\", token)",
        ],
      },
      {
        practiceId: "python.security.unsafe-deserialization",
        blocking: true,
        diff: [
          "diff --git a/src/jobs/payloads.py b/src/jobs/payloads.py",
          "+++ b/src/jobs/payloads.py",
          "@@ -1,1 +1,2 @@",
          " import pickle",
          "+payload = pickle.loads(raw_payload)",
        ],
      },
      {
        practiceId: "python.security.insecure-tls-verification",
        blocking: true,
        diff: [
          "diff --git a/src/vendors/client.py b/src/vendors/client.py",
          "+++ b/src/vendors/client.py",
          "@@ -1,1 +1,2 @@",
          " import requests",
          "+response = requests.get(url, verify=False)",
        ],
      },
      {
        practiceId: "python.security.jwt-signature-verification",
        blocking: true,
        diff: [
          "diff --git a/src/auth/jwt.py b/src/auth/jwt.py",
          "+++ b/src/auth/jwt.py",
          "@@ -1,1 +1,2 @@",
          " import jwt",
          "+claims = jwt.decode(token, options={\"verify_signature\": False})",
        ],
      },
      {
        practiceId: "python.security.crypto-random-for-secrets",
        blocking: true,
        diff: [
          "diff --git a/src/auth/tokens.py b/src/auth/tokens.py",
          "+++ b/src/auth/tokens.py",
          "@@ -1,1 +1,2 @@",
          " import random",
          "+reset_token = \"\".join(random.choice(alphabet) for _ in range(32))",
        ],
      },
      {
        practiceId: "scala.security.java-deserialization",
        blocking: true,
        diff: [
          "diff --git a/server/src/com/writer/auth/SessionCodec.scala b/server/src/com/writer/auth/SessionCodec.scala",
          "+++ b/server/src/com/writer/auth/SessionCodec.scala",
          "@@ -1,1 +1,2 @@",
          " final class SessionCodec",
          "+val payload = new ObjectInputStream(input).readObject()",
        ],
      },
      {
        practiceId: "scala.security.insecure-tls-trust-all",
        blocking: true,
        diff: [
          "diff --git a/server/src/com/writer/http/TlsClient.scala b/server/src/com/writer/http/TlsClient.scala",
          "+++ b/server/src/com/writer/http/TlsClient.scala",
          "@@ -1,1 +1,2 @@",
          " final class TlsClient",
          "+val verifier = NoopHostnameVerifier.INSTANCE",
        ],
      },
      {
        practiceId: "scala.security.weak-message-digest",
        blocking: false,
        diff: [
          "diff --git a/server/src/com/writer/security/Digest.scala b/server/src/com/writer/security/Digest.scala",
          "+++ b/server/src/com/writer/security/Digest.scala",
          "@@ -1,1 +1,2 @@",
          " object Digest",
          "+val digest = MessageDigest.getInstance(\"MD5\")",
        ],
      },
    ];

    for (const entry of cases) {
      const result = registry.scanDiff(entry.diff.join("\n"), { useSemgrep: false });

      expect(result.findings.map((finding) => finding.practice_id)).toContain(entry.practiceId);
      expect(result.blocking).toBe(entry.blocking);
      expect(result.findings[0]?.engine).toBe("semgrep-rule-fallback");
    }
  });

  it("scans expanded secure coding findings for Python and Scala", () => {
    registry.rebuild();

    const cases = [
      {
        practiceId: "security.cookies.no-insecure-flags",
        blocking: true,
        diff: [
          "diff --git a/src/auth/session.py b/src/auth/session.py",
          "+++ b/src/auth/session.py",
          "@@ -1,1 +1,2 @@",
          " def issue_cookie(response, session_id):",
          "+    response.set_cookie(\"session\", session_id, secure=False)",
        ],
      },
      {
        practiceId: "security.cors.no-wildcard-credentials",
        blocking: true,
        diff: [
          "diff --git a/src/api/app.py b/src/api/app.py",
          "+++ b/src/api/app.py",
          "@@ -1,1 +1,2 @@",
          " app = FastAPI()",
          "+app.add_middleware(CORSMiddleware, allow_origins=[\"*\"], allow_credentials=True)",
        ],
      },
      {
        practiceId: "python.security.no-debug-mode",
        blocking: true,
        diff: [
          "diff --git a/src/api/app.py b/src/api/app.py",
          "+++ b/src/api/app.py",
          "@@ -1,1 +1,2 @@",
          " app = create_app()",
          "+app.run(debug=True)",
        ],
      },
      {
        practiceId: "python.security.no-eval-exec",
        blocking: true,
        diff: [
          "diff --git a/src/api/expressions.py b/src/api/expressions.py",
          "+++ b/src/api/expressions.py",
          "@@ -1,1 +1,2 @@",
          " def evaluate(request):",
          "+    value = eval(request.args[\"expr\"])",
        ],
      },
      {
        practiceId: "python.security.no-fast-password-hash",
        blocking: true,
        diff: [
          "diff --git a/src/auth/passwords.py b/src/auth/passwords.py",
          "+++ b/src/auth/passwords.py",
          "@@ -1,1 +1,2 @@",
          " import hashlib",
          "+password_hash = hashlib.sha256(password.encode()).hexdigest()",
        ],
      },
      {
        practiceId: "python.security.no-request-path-file-access",
        blocking: true,
        diff: [
          "diff --git a/src/files/downloads.py b/src/files/downloads.py",
          "+++ b/src/files/downloads.py",
          "@@ -1,1 +1,2 @@",
          " def download(request):",
          "+    return send_file(request.args[\"path\"])",
        ],
      },
      {
        practiceId: "python.security.no-sqlalchemy-text-fstring",
        blocking: true,
        diff: [
          "diff --git a/src/users/repository.py b/src/users/repository.py",
          "+++ b/src/users/repository.py",
          "@@ -1,1 +1,2 @@",
          " def find_user(session, user_id):",
          "+    rows = session.execute(f\"select * from users where id = {user_id}\")",
        ],
      },
      {
        practiceId: "python.security.no-request-url-fetch",
        blocking: true,
        diff: [
          "diff --git a/src/integrations/fetch.py b/src/integrations/fetch.py",
          "+++ b/src/integrations/fetch.py",
          "@@ -1,1 +1,2 @@",
          " import requests",
          "+response = requests.get(request.args[\"url\"])",
        ],
      },
      {
        practiceId: "python.security.no-template-autoescape-off",
        blocking: true,
        diff: [
          "diff --git a/src/web/templates.py b/src/web/templates.py",
          "+++ b/src/web/templates.py",
          "@@ -1,1 +1,2 @@",
          " from jinja2 import Environment",
          "+env = Environment(loader=loader, autoescape=False)",
        ],
      },
      {
        practiceId: "python.security.no-tempfile-mktemp",
        blocking: true,
        diff: [
          "diff --git a/src/files/tmp.py b/src/files/tmp.py",
          "+++ b/src/files/tmp.py",
          "@@ -1,1 +1,2 @@",
          " import tempfile",
          "+name = tempfile.mktemp()",
        ],
      },
      {
        practiceId: "python.security.unsafe-xml-parsing",
        blocking: true,
        diff: [
          "diff --git a/src/imports/xml.py b/src/imports/xml.py",
          "+++ b/src/imports/xml.py",
          "@@ -1,1 +1,2 @@",
          " from xml.etree import ElementTree",
          "+root = ElementTree.fromstring(payload)",
        ],
      },
      {
        practiceId: "scala.security.no-fast-password-hash",
        blocking: true,
        diff: [
          "diff --git a/server/src/com/writer/auth/Passwords.scala b/server/src/com/writer/auth/Passwords.scala",
          "+++ b/server/src/com/writer/auth/Passwords.scala",
          "@@ -1,1 +1,2 @@",
          " object Passwords",
          "+val passwordHash = MessageDigest.getInstance(\"SHA-256\").digest(password.getBytes)",
        ],
      },
      {
        practiceId: "scala.security.no-request-path-file-access",
        blocking: true,
        diff: [
          "diff --git a/server/src/com/writer/files/Downloads.scala b/server/src/com/writer/files/Downloads.scala",
          "+++ b/server/src/com/writer/files/Downloads.scala",
          "@@ -1,1 +1,2 @@",
          " final class Downloads",
          "+val file = Source.fromFile(request.getParameter(\"path\"))",
        ],
      },
      {
        practiceId: "scala.security.no-request-url-fetch",
        blocking: true,
        diff: [
          "diff --git a/server/src/com/writer/integrations/Fetcher.scala b/server/src/com/writer/integrations/Fetcher.scala",
          "+++ b/server/src/com/writer/integrations/Fetcher.scala",
          "@@ -1,1 +1,2 @@",
          " final class Fetcher",
          "+val body = requests.get(request.getParameter(\"url\"))",
        ],
      },
      {
        practiceId: "scala.security.no-runtime-exec",
        blocking: true,
        diff: [
          "diff --git a/server/src/com/writer/jobs/Runner.scala b/server/src/com/writer/jobs/Runner.scala",
          "+++ b/server/src/com/writer/jobs/Runner.scala",
          "@@ -1,1 +1,2 @@",
          " final class Runner",
          "+Runtime.getRuntime().exec(command)",
        ],
      },
      {
        practiceId: "scala.security.no-sql-interpolation",
        blocking: true,
        diff: [
          "diff --git a/server/src/com/writer/users/UserRepository.scala b/server/src/com/writer/users/UserRepository.scala",
          "+++ b/server/src/com/writer/users/UserRepository.scala",
          "@@ -1,1 +1,2 @@",
          " final class UserRepository",
          "+statement.executeQuery(s\"select * from users where id = $userId\")",
        ],
      },
      {
        practiceId: "scala.security.no-unsafe-xml-load",
        blocking: true,
        diff: [
          "diff --git a/server/src/com/writer/imports/XmlImport.scala b/server/src/com/writer/imports/XmlImport.scala",
          "+++ b/server/src/com/writer/imports/XmlImport.scala",
          "@@ -1,1 +1,2 @@",
          " import scala.xml.XML",
          "+val doc = XML.loadString(payload)",
        ],
      },
      {
        practiceId: "scala.security.crypto-random-for-secrets",
        blocking: true,
        diff: [
          "diff --git a/server/src/com/writer/auth/Tokens.scala b/server/src/com/writer/auth/Tokens.scala",
          "+++ b/server/src/com/writer/auth/Tokens.scala",
          "@@ -1,1 +1,2 @@",
          " import scala.util.Random",
          "+val resetToken = Random.alphanumeric.take(32).mkString",
        ],
      },
    ];

    for (const entry of cases) {
      const result = registry.scanDiff(entry.diff.join("\n"), { useSemgrep: false });
      const finding = result.findings.find((item) => item.practice_id === entry.practiceId);

      expect(finding?.practice_id).toBe(entry.practiceId);
      expect(finding?.engine).toBe("semgrep-rule-fallback");
      expect(result.blocking).toBe(entry.blocking);
    }
  });

  it("scans everyday Python, Scala, TypeScript, and Rust practice findings", () => {
    registry.rebuild();

    const cases = [
      {
        practiceId: "python.defaults.no-mutable-defaults",
        blocking: true,
        diff: [
          "diff --git a/src/users/helpers.py b/src/users/helpers.py",
          "+++ b/src/users/helpers.py",
          "@@ -1,1 +1,2 @@",
          " from typing import Any",
          "+def add_user(user: Any, users=[]):",
        ],
      },
      {
        practiceId: "python.http.client-timeout",
        blocking: false,
        diff: [
          "diff --git a/src/vendors/client.py b/src/vendors/client.py",
          "+++ b/src/vendors/client.py",
          "@@ -1,1 +1,2 @@",
          " import requests",
          "+response = requests.get(url)",
        ],
      },
      {
        practiceId: "python.logging.no-fstring-logs",
        blocking: false,
        diff: [
          "diff --git a/src/jobs/sync.py b/src/jobs/sync.py",
          "+++ b/src/jobs/sync.py",
          "@@ -1,1 +1,2 @@",
          " logger.info(\"sync_start\")",
          "+logger.info(f\"synced user {user_id}\")",
        ],
      },
      {
        practiceId: "scala.execution-context.no-global-in-services",
        blocking: false,
        diff: [
          "diff --git a/server/src/com/writer/users/UserService.scala b/server/src/com/writer/users/UserService.scala",
          "+++ b/server/src/com/writer/users/UserService.scala",
          "@@ -1,1 +1,2 @@",
          " final class UserService",
          "+import scala.concurrent.ExecutionContext.Implicits.global",
        ],
      },
      {
        practiceId: "scala.values.no-null",
        blocking: true,
        diff: [
          "diff --git a/server/src/com/writer/users/User.scala b/server/src/com/writer/users/User.scala",
          "+++ b/server/src/com/writer/users/User.scala",
          "@@ -1,1 +1,2 @@",
          " final case class User(email: Option[String])",
          "+val email = user.email.getOrElse(null)",
        ],
      },
      {
        practiceId: "typescript.node.no-shell-exec",
        blocking: true,
        diff: [
          "diff --git a/scripts/release.mjs b/scripts/release.mjs",
          "+++ b/scripts/release.mjs",
          "@@ -1,1 +1,2 @@",
          " import { execSync } from \"node:child_process\";",
          "+execSync(`git checkout ${branch}`)",
        ],
      },
      {
        practiceId: "security.secrets.no-hardcoded-secrets",
        blocking: true,
        diff: [
          "diff --git a/src/config.ts b/src/config.ts",
          "+++ b/src/config.ts",
          "@@ -1,1 +1,2 @@",
          " export const config = {};",
          "+export const apiKey = \"sk_" + "live_1234567890\";",
        ],
      },
      {
        practiceId: "typescript.db.parameterized-sql",
        blocking: true,
        diff: [
          "diff --git a/src/routes/users.ts b/src/routes/users.ts",
          "+++ b/src/routes/users.ts",
          "@@ -1,1 +1,2 @@",
          " const query = \"select 1\";",
          "+const rows = db.query(`SELECT * FROM users WHERE id = ${userId}`);",
        ],
      },
      {
        practiceId: "typescript.react.no-dangerous-html",
        blocking: true,
        diff: [
          "diff --git a/src/components/Profile.tsx b/src/components/Profile.tsx",
          "+++ b/src/components/Profile.tsx",
          "@@ -1,1 +1,2 @@",
          " export function Profile() {",
          "+return <div dangerouslySetInnerHTML={{ __html: body }} />;",
        ],
      },
      {
        practiceId: "typescript.security.no-eval-function",
        blocking: true,
        diff: [
          "diff --git a/src/runtime/expressions.ts b/src/runtime/expressions.ts",
          "+++ b/src/runtime/expressions.ts",
          "@@ -1,1 +1,2 @@",
          " export const handlers = {};",
          "+const fn = new Function(userExpression);",
        ],
      },
      {
        practiceId: "rust.process.no-shell-command",
        blocking: true,
        diff: [
          "diff --git a/src/release.rs b/src/release.rs",
          "+++ b/src/release.rs",
          "@@ -1,1 +1,2 @@",
          " use std::process::Command;",
          '+Command::new("sh").arg("-c").arg(command).status()?;',
        ],
      },
      {
        practiceId: "rust.http.no-insecure-tls-verification",
        blocking: true,
        diff: [
          "diff --git a/src/client.rs b/src/client.rs",
          "+++ b/src/client.rs",
          "@@ -1,1 +1,2 @@",
          " let builder = reqwest::Client::builder();",
          "+let client = builder.danger_accept_invalid_certs(true).build()?;",
        ],
      },
      {
        practiceId: "rust.safety.document-unsafe-invariants",
        blocking: false,
        diff: [
          "diff --git a/src/buffer.rs b/src/buffer.rs",
          "+++ b/src/buffer.rs",
          "@@ -1,1 +1,2 @@",
          " let len = buffer.len();",
          "+let bytes = unsafe { std::slice::from_raw_parts(ptr, len) };",
        ],
      },
    ];

    for (const entry of cases) {
      const result = registry.scanDiff(entry.diff.join("\n"), { useSemgrep: false });
      const finding = result.findings.find((item) => item.practice_id === entry.practiceId);

      expect(finding?.practice_id).toBe(entry.practiceId);
      expect(result.blocking).toBe(entry.blocking);
    }
  });

  it("does not treat regular-expression or database exec methods as shell execution", () => {
    registry.rebuild();

    const result = registry.scanDiff(
      [
        "diff --git a/plugins/practice-registry-mcp/src/matcher.ts b/plugins/practice-registry-mcp/src/matcher.ts",
        "+++ b/plugins/practice-registry-mcp/src/matcher.ts",
        "@@ -1,1 +1,3 @@",
        " export function matchLine() {",
        "+  regex.exec(line);",
        "+  db.exec(\"CREATE TABLE observations (id INTEGER)\");",
      ].join("\n"),
      { useSemgrep: false },
    );

    expect(result.findings.map((finding) => finding.practice_id)).not.toContain("typescript.node.no-shell-exec");
  });

  it("keeps diff guidance scoped to changed files and SQL-shaped templates", () => {
    registry.rebuild();

    const result = registry.check("diff", {
      diff: [
        "diff --git a/plugins/practice-registry-mcp/src/doctor.ts b/plugins/practice-registry-mcp/src/doctor.ts",
        "+++ b/plugins/practice-registry-mcp/src/doctor.ts",
        "@@ -1,1 +1,2 @@",
        " export function status() {",
        "+  return `${records.length} records loaded from ${practicesRoot}`;",
        "diff --git a/plugins/practice-registry-mcp/practices/typescript/db-parameterized-sql.yml b/plugins/practice-registry-mcp/practices/typescript/db-parameterized-sql.yml",
        "+++ b/plugins/practice-registry-mcp/practices/typescript/db-parameterized-sql.yml",
        "@@ -1,1 +1,2 @@",
        " bad_examples:",
        "+  - db.query(`SELECT * FROM users WHERE id = ${userId}`)",
      ].join("\n"),
    });

    expect(result.matched_practices.map((practice) => practice.id)).not.toContain("typescript.db.parameterized-sql");
  });

  it("returns TypeScript MCP guidance for this server", () => {
    registry.rebuild();

    const result = registry.check("plan", {
      language: "typescript",
      framework: "mcp",
      files: ["src/mcpServer.ts", "scripts/mcp-smoke-test.mjs"],
      intent: "add a new MCP tool argument and result field",
      planned_approach:
        "Update registerTool inputSchema and outputSchema, add server_info contract metadata, update smoke tests, and document the contract version.",
    });

    expect(result.passed).toBe(true);
    expect(result.decision).toBe("follow_guidance");
    expect(result.matched_practices.map((practice) => practice.id)).toContain("typescript.mcp.versioned-tool-contracts");
    expect(result.matched_practices.map((practice) => practice.id)).toContain("typescript.mcp.explicit-zod-tool-schemas");
  });

  it("returns everyday TypeScript API guidance", () => {
    registry.rebuild();

    const sqlPlan = registry.check("plan", {
      language: "typescript",
      framework: "express",
      files: ["src/routes/users.ts"],
      intent: "add an endpoint that reads user id and queries postgres",
      planned_approach: "Build SQL with a template string, run it through the db client, log the user id, and return JSON.",
    });
    const reactPlan = registry.check("plan", {
      language: "typescript",
      framework: "react",
      files: ["src/components/ProfileForm.tsx"],
      intent: "add a profile form that calls the API and handles validation",
      planned_approach: "Use useEffect, fetch without AbortController, store raw API response in state, and show errors inline.",
    });

    expect(sqlPlan.decision).toBe("change_code");
    expect(sqlPlan.matched_practices.map((practice) => practice.id)).toContain("typescript.db.parameterized-sql");
    expect(reactPlan.decision).toBe("revise_or_justify");
    expect(reactPlan.matched_practices.map((practice) => practice.id)).toContain("typescript.http.fetch-timeouts");
    expect(reactPlan.matched_practices.map((practice) => practice.id)).toContain("typescript.react.async-effect-cleanup");
  });

  it("returns Rust tooling, error, and parser guidance", () => {
    registry.rebuild();

    const result = registry.check("plan", {
      language: "rust",
      framework: "cargo",
      files: ["Cargo.toml", "src/parser.rs", "tests/parser.rs"],
      intent: "add a parser for untrusted binary records",
      planned_approach:
        "Return a typed Result with operation context, add property tests for arbitrary bytes and a regression corpus, then run cargo fmt, cargo test, cargo clippy with warnings denied, and cargo doc.",
    });

    expect(result.passed).toBe(true);
    expect(result.decision).toBe("follow_guidance");
    expect(result.matched_practices.map((practice) => practice.id)).toContain("rust.tooling.cargo-quality-gates");
    expect(result.matched_practices.map((practice) => practice.id)).toContain("rust.errors.context-at-boundaries");
    expect(result.matched_practices.map((practice) => practice.id)).toContain("rust.testing.fuzz-parsers-and-invariants");
  });

  it("keeps Rust blockers scoped to the recorded risky calls", () => {
    registry.rebuild();

    const safeProcessPlan = registry.check("plan", {
      language: "rust",
      files: ["src/release.rs"],
      intent: "run git without a shell",
      planned_approach: 'Use Command::new("git").args(["diff", "--name-only"]) and propagate the status error.',
    });
    const safeClientPlan = registry.check("plan", {
      language: "rust",
      files: ["src/client.rs"],
      intent: "build an outbound HTTP client",
      planned_approach: "Use reqwest with certificate verification, connect_timeout, and an overall request deadline.",
    });
    const riskyInputPlan = registry.check("plan", {
      language: "rust",
      files: ["src/api.rs"],
      intent: "parse request input",
      planned_approach: "Parse the request id and call .unwrap() on the result.",
    });

    expect(safeProcessPlan.blocking).toBe(false);
    expect(safeProcessPlan.matched_practices.map((practice) => practice.id)).not.toContain("rust.process.no-shell-command");
    expect(safeClientPlan.blocking).toBe(false);
    expect(safeClientPlan.matched_practices.map((practice) => practice.id)).not.toContain("rust.http.no-insecure-tls-verification");
    expect(riskyInputPlan.decision).toBe("revise_or_justify");
    expect(riskyInputPlan.matched_practices.map((practice) => practice.id)).toContain("rust.errors.no-unwrap-on-untrusted-input");
  });

  it("requires concrete risk evidence before blocking pattern-backed plans", () => {
    registry.rebuild();

    const genericPlan = registry.check("plan", {
      language: "typescript",
      files: ["src/example.ts"],
      intent: "add a pure helper",
      planned_approach: "Export a typed function that returns its input.",
    });
    const riskyPlan = registry.check("plan", {
      language: "typescript",
      files: ["src/runtime/expressions.ts"],
      intent: "evaluate a user expression",
      planned_approach: "Compile the expression with new Function(userExpression).",
    });

    expect(genericPlan.blocking).toBe(false);
    expect(genericPlan.matched_practices.map((practice) => practice.id)).not.toContain(
      "typescript.security.no-eval-function",
    );
    expect(riskyPlan.decision).toBe("change_code");
    expect(riskyPlan.matched_practices.map((practice) => practice.id)).toContain(
      "typescript.security.no-eval-function",
    );
  });

  it("returns only topical guardrails when preflight has an intent", () => {
    registry.rebuild();

    const genericPreflight = registry.preflight({
      language: "typescript",
      files: ["src/example.ts"],
      intent: "add a pure helper",
      planned_approach: "Export a typed function that returns its input.",
    });

    expect(genericPreflight.guardrails.practices).toEqual([]);
    expect(genericPreflight.plan_check?.blocking).toBe(false);
    expect(genericPreflight.plan_check?.matched_practices.map((practice) => practice.id)).not.toContain(
      "typescript.security.no-eval-function",
    );
  });

  it("preflights generation with required calls and optional plan check", () => {
    registry.rebuild();

    const result = registry.preflight({
      language: "typescript",
      framework: "express",
      files: ["src/routes/users.ts"],
      intent: "add an endpoint that reads user id and queries postgres",
      planned_approach: "Build SQL with a template string and pass it to the db client.",
    });

    expect(result.decision).toBe("change_code");
    expect(result.passed).toBe(false);
    expect(result.required_calls).toEqual(["check_plan", "finalize_change"]);
    expect(result.guardrails.practices.map((practice) => practice.id)).toContain("typescript.db.parameterized-sql");
    expect(result.plan_check?.matched_practices.map((practice) => practice.id)).toContain("typescript.db.parameterized-sql");
    expect(result.observation_id).toBeGreaterThan(0);
  });

  it("records practice proposals and exception requests in the review queue", () => {
    registry.rebuild();

    const proposal = registry.proposePractice({
      title: "Use repository helpers for analytics reads",
      summary: "Analytics reads should go through the package repository helper instead of ad hoc SQL.",
      owner: "data-platform",
      language: "typescript",
      framework: "node",
      files: ["src/analytics/report.ts"],
      evidence: "Repeated needs_review observations in analytics routes.",
      suggested_status: "preferred",
      suggested_enforcement: "advisory",
    });
    const exception = registry.recordException({
      practice_id: "typescript.db.parameterized-sql",
      reason: "Legacy migration script has static seed data.",
      accepted_context: "Only the one-time migration script may keep static SQL text.",
      owner: "data-platform",
      expires_at: "2026-12-31",
      files: ["scripts/migrate-seed.ts"],
      replacement_plan: "Delete the script after the migration is complete.",
    });
    const queue = registry.reviewQueue({ limit: 10 });

    expect(proposal.decision).toBe("needs_review");
    expect(exception.exception.practice_id).toBe("typescript.db.parameterized-sql");
    expect(queue.decision).toBe("needs_review");
    expect(queue.items.map((item) => item.kind)).toContain("practice_proposal");
    expect(queue.items.map((item) => item.kind)).toContain("practice_exception");
    expect(queue.items.find((item) => item.kind === "practice_exception")?.practice_ids).toContain("typescript.db.parameterized-sql");
  });

  it("accepts independent research approval and resolves linked review observations", () => {
    registry.rebuild();
    const proposal = registry.proposePractice({
      title: "Bound connector catalog list responses",
      summary: "Connector list screens should request compact bounded pages.",
      owner: "cerebro-web",
      language: "typescript",
      files: ["src/app/connectors/page.tsx"],
    });

    const approval = registry.recordApproval({
      practice_id: "typescript.react.bounded-list-projections",
      method: "research",
      approved_by: "cerebro-web",
      conclusion: "Independent specifications support sparse fields and bounded pagination.",
      related_observation_ids: [proposal.observation_id!],
      sources: [
        {
          title: "JSON:API Sparse Fieldsets",
          publisher: "JSON:API",
          url: "https://jsonapi.org/format/#fetching-sparse-fieldsets",
          direct_support: "Restricted fieldsets omit additional response fields.",
        },
        {
          title: "GraphQL Pagination",
          publisher: "GraphQL Foundation",
          url: "https://graphql.org/learn/pagination/",
          direct_support: "Large list fields should use bounded pagination.",
        },
      ],
    });
    const queue = registry.reviewQueue({ limit: 10 });
    const repeatedQueue = registry.reviewQueue({ limit: 10 });

    expect(approval.passed).toBe(true);
    expect(approval.decision).toBe("allowed");
    expect(queue.items.some((item) => item.observation_ids.includes(proposal.observation_id!))).toBe(false);
    expect(repeatedQueue.items).toEqual([]);
  });

  it("rejects research approval without independent publishers and domains", () => {
    registry.rebuild();
    const approval = registry.recordApproval({
      practice_id: "typescript.react.bounded-list-projections",
      method: "research",
      approved_by: "cerebro-web",
      conclusion: "Two pages from one publisher repeat the same recommendation.",
      sources: [
        {
          title: "Page one",
          publisher: "Example",
          url: "https://docs.example.com/one",
          direct_support: "The page recommends bounded responses.",
        },
        {
          title: "Page two",
          publisher: "Example",
          url: "https://docs.example.com/two",
          direct_support: "The page recommends response projections.",
        },
      ],
    });

    expect(approval.passed).toBe(false);
    expect(approval.next_steps).toContain("Use sources from at least two independent publishers.");
    expect(approval.next_steps).toContain("Use sources from at least two independent domains.");
  });

  it("lints research approval evidence on durable practice records", () => {
    registry.rebuild();
    const practice = registry.explain("typescript.react.bounded-list-projections")!;
    const lint = lintPractices([
      {
        ...practice,
        approval: {
          ...practice.approval!,
          sources: practice.approval!.sources.map((source, index) => ({
            ...source,
            publisher: "One publisher",
            url: `https://docs.example.com/${index}`,
          })),
        },
      },
    ]);

    expect(lint.passed).toBe(false);
    expect(lint.findings.map((finding) => finding.message)).toContain(
      "Use sources from at least two independent publishers.",
    );
  });

  it("builds a coverage report from practices and observations", () => {
    registry.rebuild();
    registry.check("plan", {
      language: "typescript",
      framework: "react",
      files: ["src/components/UnknownWidget.tsx"],
      intent: "use an unrecorded UI library pattern",
      planned_approach: "Use the custom widget lifecycle from a library with no indexed practice.",
    });

    const report = buildCoverageReport(registry.all(), registry.recentObservations({ limit: 10 }));

    expect(report.total_practices).toBeGreaterThanOrEqual(76);
    expect(report.language_coverage.find((item) => item.language === "typescript")?.dedicated_practices).toBeGreaterThanOrEqual(10);
    expect(report.language_coverage.find((item) => item.language === "rust")?.dedicated_practices).toBeGreaterThanOrEqual(10);
    expect(report.by_framework.map((item) => item.name)).toContain("react");
    expect(report.next_steps).toContain("Add eval cases for every new blocking practice and every false-positive fix.");
  });
});
