import fs from "node:fs";
import path from "node:path";
import process from "node:process";

export type EditorClient = "cursor";

export type EditorConfigOptions = {
  client: EditorClient;
  registryRoot: string;
  dbPath?: string;
  inlineEnv?: boolean;
  launcherPath?: string;
  serverName?: string;
  nodePath?: string;
};

export type EditorConfigResult = {
  client: EditorClient;
  outputPath: string;
  serverName: string;
  rulePath?: string;
};

type McpServerConfig = {
  type: "stdio";
  command: string;
  args: string[];
  env?: Record<string, string>;
};

type McpConfigFile = {
  mcpServers: Record<string, McpServerConfig | unknown>;
};

const DEFAULT_SERVER_NAME = "practice-registry";
const GENERATED_LAUNCHER_MARKER = "Generated by Practice Registry";

export function createEditorMcpConfig(options: EditorConfigOptions): McpConfigFile {
  if (options.client !== "cursor") {
    throw new Error(`Unsupported editor client: ${options.client}`);
  }

  const root = path.resolve(options.registryRoot);
  const serverName = options.serverName ?? DEFAULT_SERVER_NAME;
  const server = options.inlineEnv === true ? inlineServerConfig(options, root) : launcherServerConfig(options);

  return {
    mcpServers: {
      [serverName]: server,
    },
  };
}

export function writeEditorMcpConfig(options: EditorConfigOptions & { outputPath: string; overwrite?: boolean }): void {
  const generated = createEditorMcpConfig(options);
  const existing = options.overwrite ? {} : readJsonObject(options.outputPath);
  const merged = {
    ...existing,
    mcpServers: {
      ...asRecord(existing.mcpServers),
      ...generated.mcpServers,
    },
  };

  fs.mkdirSync(path.dirname(options.outputPath), { recursive: true });
  fs.writeFileSync(options.outputPath, `${JSON.stringify(merged, null, 2)}\n`);
}

export function writeMcpLauncher(options: { outputPath: string; registryRoot: string; overwrite?: boolean }): void {
  const launcher = launcherText(path.resolve(options.registryRoot));
  if (fs.existsSync(options.outputPath) && !options.overwrite) {
    const existing = fs.readFileSync(options.outputPath, "utf8");
    if (!existing.includes(GENERATED_LAUNCHER_MARKER)) {
      throw new Error(`${options.outputPath} exists and was not generated by Practice Registry. Pass --overwrite to replace it.`);
    }
  }

  fs.mkdirSync(path.dirname(options.outputPath), { recursive: true });
  fs.writeFileSync(options.outputPath, launcher);
  fs.chmodSync(options.outputPath, 0o755);
}

export function writeEditorRule(options: { outputPath: string; serverName?: string }): void {
  fs.mkdirSync(path.dirname(options.outputPath), { recursive: true });
  fs.writeFileSync(options.outputPath, cursorRuleText(options.serverName ?? DEFAULT_SERVER_NAME));
}

export function cursorRuleText(serverName: string): string {
  return `---
description: Check Scala, Python, TypeScript, JavaScript, and Rust code against recorded practices.
globs: **/*.py,**/*.scala,**/*.sc,**/*.ts,**/*.tsx,**/*.js,**/*.jsx,**/*.mjs,**/*.cjs,**/*.rs,**/Cargo.toml,**/Cargo.lock
alwaysApply: false
---

Before generating or editing non-trivial Scala, Python, TypeScript, JavaScript, or Rust code, call ${serverName}.preflight when intent or files are known. Then call ${serverName}.check_plan with the intended approach, affected files, language, framework, and dependencies.

Before the final response, call ${serverName}.finalize_change with the final diff. Pass plan_observation_id from the matching check_plan result when it is available.

Trust the passed field on Practice Registry results. Do not treat blocking: false as a pass by itself. The pass decisions are allowed and follow_guidance. If check_plan, scan_diff, or finalize_change returns change_code, revise_or_justify, ask_owner, or needs_review, take the listed next_steps and rerun the check before finalizing.

Treat banned findings as blockers. Treat discouraged and legacy_accepted findings as changes to make unless a recorded context applies. Resolve needs_review through the named owner or a research approval for an indexed practice with at least two directly supporting HTTPS sources from independent publishers and domains. Research approval does not approve an exception. If you keep a discouraged or legacy_accepted pattern, name the accepted context in the final response.

When no durable practice covers a repeated decision, use ${serverName}.propose_practice. When an exception is needed, use ${serverName}.record_exception; this records the request but does not approve it. After an approved practice record exists, use ${serverName}.record_approval to resolve the related review observations.
`;
}

export function defaultEditorConfigPath(client: EditorClient): string {
  if (client !== "cursor") {
    throw new Error(`Unsupported editor client: ${client}`);
  }
  return path.join(".cursor", "mcp.json");
}

export function defaultEditorRulePath(client: EditorClient): string {
  if (client !== "cursor") {
    throw new Error(`Unsupported editor client: ${client}`);
  }
  return path.join(".cursor", "rules", "practice-registry.mdc");
}

export function defaultEditorLauncherPath(client: EditorClient): string {
  if (client !== "cursor") {
    throw new Error(`Unsupported editor client: ${client}`);
  }
  return path.join(".practice-registry", "run-mcp");
}

export function normalizeEditorClient(value: string | undefined): EditorClient {
  if (!value || value === "cursor") {
    return "cursor";
  }
  throw new Error(`Unsupported editor client: ${value}`);
}

function launcherServerConfig(options: EditorConfigOptions): McpServerConfig {
  if (!options.launcherPath) {
    throw new Error("launcherPath is required unless inlineEnv is true.");
  }
  return {
    type: "stdio",
    command: options.launcherPath,
    args: [],
  };
}

function inlineServerConfig(options: EditorConfigOptions, registryRoot: string): McpServerConfig {
  if (!options.dbPath) {
    throw new Error("dbPath is required when inlineEnv is true.");
  }

  return {
    type: "stdio",
    command: options.nodePath ?? process.execPath,
    args: [path.join(registryRoot, "dist", "index.js")],
    env: {
      PRACTICE_REGISTRY_ROOT: path.join(registryRoot, "practices"),
      PRACTICE_SEMGREP_RULES: path.join(registryRoot, "semgrep", "practice-rules.yml"),
      PRACTICE_REGISTRY_DB: path.resolve(options.dbPath),
    },
  };
}

function launcherText(registryRoot: string): string {
  return `#!/bin/sh
# ${GENERATED_LAUNCHER_MARKER}. Re-run practice setup to update this file.
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
REGISTRY_ROOT=${shellQuote(registryRoot)}

NODE_BIN="\${PRACTICE_NODE:-}"
if [ -z "$NODE_BIN" ]; then
  for candidate in node /opt/homebrew/bin/node /usr/local/bin/node /usr/bin/node; do
    if command -v "$candidate" >/dev/null 2>&1; then
      NODE_BIN=$(command -v "$candidate")
      break
    fi
    if [ -x "$candidate" ]; then
      NODE_BIN="$candidate"
      break
    fi
  done
fi

if [ -z "$NODE_BIN" ]; then
  echo "Practice Registry MCP could not find Node.js 22 or newer." >&2
  exit 127
fi

NODE_MAJOR=$("$NODE_BIN" -p "process.versions.node.split('.')[0]" 2>/dev/null || printf '0')
case "$NODE_MAJOR" in
  ''|*[!0-9]*) NODE_MAJOR=0 ;;
esac

if [ "$NODE_MAJOR" -lt 22 ]; then
  echo "Practice Registry MCP needs Node.js 22 or newer. Found $("$NODE_BIN" --version 2>/dev/null || printf 'unknown')." >&2
  exit 1
fi

export PRACTICE_REGISTRY_DB="\${PRACTICE_REGISTRY_DB:-$REPO_ROOT/.practice-registry/practices.db}"

exec "$NODE_BIN" "$REGISTRY_ROOT/dist/index.js"
`;
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\"'\"'")}'`;
}

function readJsonObject(filePath: string): Record<string, unknown> {
  if (!fs.existsSync(filePath)) {
    return {};
  }
  const parsed = JSON.parse(fs.readFileSync(filePath, "utf8")) as unknown;
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error(`${filePath} must contain a JSON object.`);
  }
  return parsed as Record<string, unknown>;
}

function asRecord(value: unknown): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    return {};
  }
  return value as Record<string, unknown>;
}
